### ISSUE TITLE
specify values that determine scale motion

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#10]
There are many parameters associated with the scale that affect it's range of motion, including:

• height of the fulcrum
• height of the platform supports
• length of the balance beam
• weights of the items
• range of the balance beam's rotation on the fulcrum
• amount of horizontal and vertical space available in the play area

In order to fine-tune how the scale responds to items place on plates (or removed from plates), it's going to be necessary to play with some of these parameters, and will potentially involve trying many different values.  Query parameters seems like the best way to allow designers to do this.

**Comment by pixelzoom** [comment]
I've added the following query parameters:

`fruitWeights` - the weights of the items in the "Fruit" scene of the "Basics" screen. Default is `fruitWeights =3,2,1` (apples, oranges, ones).  The largest weight determines how much the scale moves for 1 unit of weight.  The larger the difference between largest and smallest weights, the less movement will occur for 1 unit of weight. 

`scaleY` - y coordinate of the scale's location, the point where the fulcrum meets the balance beam.  Note that the positive y axis points _down_ in screen coordinates, so larger values will move the scale _down_. Default is `scaleY=420`.

`fulcrumHeight` - height of the fulcrum that the scale's balance beam sits on. Default is `fulcrumHeight=40`

`plateSupportHeight` - height of the vertical support that connects a plate to the balance beam. Default is `plateSupportHeight=50`

`maxScaleAngle` - the maximum angle (in degrees) that the scale can move (up or down) from the balanced position. Default is `maxScaleAngle=12`

**Comment by pixelzoom** [comment]
Examples....

Here's what the defaults look like, with `?showGrid&leftItems=36,0,0` (scale fully loaded):

![screenshot_391](https://user-images.githubusercontent.com/3046552/30787460-2fa5161c-a146-11e7-8c95-fe1c02efb3b5.png)

Here's a configuration that maximizes use of vertical space:
`?&showGrid&leftItems=36,0,0&fulcrumHeight=60&plateSupportHeight=70&maxScaleAngle=20`

![screenshot_392](https://user-images.githubusercontent.com/3046552/30787467-4fb3f7f2-a146-11e7-8956-baff550c6ce1.png)

Before we make any decisions here, also keep in mind that the height of the grid will be determined by the heights of the item icons.  So we need to resolve #6 (items for Basics screen).
 
[EDIT: I revised this comment after adding the `scaleY` query parameter.]

**Comment by pixelzoom** [comment]
@amanda-phet You now have full control over the item weights and how the scale's balance beam moves.  This should allow you to tune the sim to the desired behavior.  After addressing #6, let me know what default values you want for each of the query parameters described above.

**Comment by pixelzoom** [comment]
Here's a dev version with support for the new query parameters:
http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.16/equality-explorer_en.html

**Comment by pixelzoom** [comment]
In Slack conversation with @amanda-phet, a new requirement was provided: for all screens, make the scale bottom out at a weight of 30 units.   So that you can experiment with this, I've added query parameter `maxWeight`, which defaults to 30.

I've also tweaked the default values for the other query parameters so that use of the vertical space is maximized, and the scale looks "bottomed out".   When bottomed out, the beam contacts the base, and the plate is very close to the beam but not quite making contact.

The defaults values are now as follows:

> fruitWeights=[3,2,1]
fulcrumHeight=52
plateSupportHeight=70
maxScaleAngle=22
maxWeight=30
scaleY=420

You can experiment with this in [1.0.0-dev.17](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.17/equality-explorer_en.html).  Note that the "Numbers" screen is also "in progress" in this version, but obeys the query parameters.

**Comment by pixelzoom** [comment]
Here's [1.0.0-dev.17](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.17/equality-explorer_en.html) with `?leftItems=12,5,4&showGrid`, a scenario where the scale is bottomed out.  Note that the arrow also turns 'red' when the scale is bottomed out.

![screenshot_394](https://user-images.githubusercontent.com/3046552/30828965-aca84a06-a1fc-11e7-89f3-ccea504e9187.png)

**Comment by pixelzoom** [comment]
`fruitWeights` query parameter has been deleted.

**Comment by pixelzoom** [comment]
Since weights were provided in #6, `fruitWeights` query parameter has been deleted.

**Comment by pixelzoom** [comment]
To summarize, we now have these query parameters:

> `scaleY=420` - y coordinate of the scale's location, the point where the fulcrum meets the balance beam. Note that the positive y axis points down in screen coordinates, so larger values will move the scale down.
>
> `fulcrumHeight=52` - height of the fulcrum that the scale's balance beam sits on.
>
> `plateSupportHeight=70` - height of the vertical support that connects a plate to the balance beam.
> 
> `maxScaleAngle=22` - the maximum angle (in degrees) that the scale can move (up or down) from the balanced position.

@amanda-phet Let me know if you'd like to change any of the defaults values, then assign this issue back to me.  I'm planning to delete these query parameters when we resolve this issue.

**Comment by amanda-phet** [comment]
I think the current values look great. I played around a little and can't find any changes that make sense.

**Comment by pixelzoom** [comment]
Query parameters deleted. Closing.

**Comment by pixelzoom** [comment]
Oops. We still have a problem, so I've restored the query parameters. 

In the Solving screen, the grid overlaps the Universal Operation control.  Screenshot:

![screenshot_407](https://user-images.githubusercontent.com/3046552/31444253-e9e6684a-ae58-11e7-8406-f9c95cfbdfca.png)

I don't think that scaling down the Universal Operation control is the right answer, it would need to be 65% of it's current size, too tiny.  Screenshot:

![screenshot_408](https://user-images.githubusercontent.com/3046552/31444352-40304f0e-ae59-11e7-95f9-8231251170f9.png)

@amanda-phet How do you want to address this?

**Comment by amanda-phet** [comment]
The solving screen uses a different grid, right? It's just a grid of two objects. So first I'd rather see how it looks with just the two composite objects, then consider scaling those down to fit.

**Comment by amanda-phet** [comment]
Just a quick attempt at how large the composite objects will be, and this looks like it will be fine: 

<img width="632" alt="screen shot 2017-10-11 at 9 41 21 am" src="https://user-images.githubusercontent.com/7852916/31451115-77711296-ae68-11e7-86c3-694f2030146f.png">
<img width="616" alt="screen shot 2017-10-11 at 9 41 35 am" src="https://user-images.githubusercontent.com/7852916/31451116-77833f34-ae68-11e7-8f33-779a2add9377.png">

**Comment by pixelzoom** [comment]
Ah, right, no grid in the Solving screen.  Thanks for the mockups, looks like we'll be fine.

**Comment by pixelzoom** [comment]
Re-removed query parameters. Closing.
