### ISSUE TITLE
document testing scenarios for lock feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#100]
The lock feature is incredibly complicated to describe, since there are so many user scenarios. As noted in https://github.com/phetsims/equality-explorer/issues/19#issuecomment-385856336, there are a minimum of 30 scenarios (15 for Numbers/Variables, 15 for Operations) that require testing every time a change is made to the lock feature, and will require QA testing.  I have my own cryptic notes that describe these scenarios, but I think it will be useful (critical?) to have well-documented scenarios and a checklist to run through during QA.

**Comment by pixelzoom** [comment]
Here are my "cryptic notes" on the test scenarios.

_Numbers and Variables screens_:

scenarios: term dragged from toolbox, equivalent comes out of other toolbox
(1) term released below plate, term and equivalent return to toolbox
(2) term released above inverse on plate, term and inverse sum to zero, equivalent goes to plate
(3) term released above plate, term plate full (or becomes full), term and equivalent return to toolbox
(4) term released above plate, ghost plate full (or becomes full), term and equivalent return to toolbox
(5) term released about plate, room on both plates, term and equivalent go to plates

scenarios: term dragged from plate, equivalent obtained from other plate
(6-10) same as (1-5) above, but with different behavior

scenarios: term dragged from plate, equivalent must be created and requires creating inverse on other plate
(11) opposite plate is full, don't start term drag, display Oops! dialog
(12) term released below plate, term and equivalent return to toolbox, inverse remains on plate
(13) term released above plate, term plate full (or becomes full), term and equivalent return to toolbox
(14) term released above plate, ghost plate full (or becomes full), term and equivalent return to toolbox
(15) term released above plate, room on both plates, term goes to plate, equivalent for to plate and replaces inverse

_Operations screen_:

Same 15 scenarios as above, but behavior is different because like terms are combined on the plates.

**Comment by phet-steele** [comment]
@pixelzoom #87?

**Comment by pixelzoom** [comment]
The hazards of creating issues before finishing my coffee.  I'll keep this issue open (since it has more detail) and close #87 as a duplicate.

**Comment by pixelzoom** [comment]
Documentation will appear in [lock-scenarios.md](https://github.com/phetsims/equality-explorer/blob/master/doc/lock-scenarios.md).

**Comment by pixelzoom** [comment]
Done. There are currently 22 scenarios.  I tested the document, but expect that the descriptions are not error-free, and will be debugged during dev and RC testing.  

Closing.
