### ISSUE TITLE
model description

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#101]
Complete the model description in [model.md](https://github.com/phetsims/equality-explorer/blob/master/doc/model.md).

**Comment by pixelzoom** [comment]
First pass at model description is completed. @amanda-phet please review, let me know if you have any suggestions.  Keep in mind that this is supposed to be a very high-level overview, not a comprehensive description of the sim.

**Comment by amanda-phet** [comment]
Should I edit it directly? 

The only change I'd like to make at the moment is in this line:

The Basics screen introduces equations using terms that correspond to real-world objects (shapes, fruits, coins and animals) whose ~~weights~~ values are hidden.

**Comment by pixelzoom** [comment]
Requested change made in above commit.

Closing.
