### ISSUE TITLE
Add padding to images to simplify layout

### ISSUE THREAD

**Issue by samreid** [phetsims/equality-explorer#106]
Discovered in https://github.com/phetsims/sun/issues/360, the lock images look like so:

![image](https://user-images.githubusercontent.com/679486/40066697-ee78dcd0-5821-11e8-9dfa-d91ad838dbf6.png)
![image](https://user-images.githubusercontent.com/679486/40066719-f8d81ccc-5821-11e8-8a84-3fdd49ec1be6.png)

This leads to layout code like this:

```js
      // This is dependent on the specific image files, and aligns the body of the lock in both images.
      alignChildren: function( children ) {
        children[ 0 ].leftBottom = children[ 1 ].leftBottom;
      },
```

and 

```js
      var lockControl = new LockControl( scene.lockedProperty, {
        x: scale.location.x,
        y: leftTermsToolbox.centerY - 5 // offset determined empirically
      } );
```

Generally, for patterns like this, it is preferable to add padding to the images so that they "line up", like this:

![image](https://user-images.githubusercontent.com/679486/40067348-36d2a1cc-5823-11e8-8408-e9f4998da308.png)
![image](https://user-images.githubusercontent.com/679486/40067378-43946e5e-5823-11e8-8b82-96051eb9b402.png)

This way, the lock can be placed exactly between the surrounding panels and there is no need for layout tweaks like the above and for maintenance it means (a) if the lock graphics change, no layout tweaking will be necessary and (b) if the surrounding panels layout changes, no layout tweaking will be necessary.

**Comment by pixelzoom** [comment]
> Generally, for patterns like this, it is preferable to add padding to the images

I disagree.

**Comment by pixelzoom** [comment]
While I disagree with the "generally" part of this issue...  In this case, adding padding to the images does make for a more pleasing touchArea dilation, so I've done that in the above commit.   And I've added an assertion that the 2 images must have identical dimensions.

**Comment by pixelzoom** [comment]
Touch area before:

![screenshot_630](https://user-images.githubusercontent.com/3046552/40069029-5148bf74-5827-11e8-8a42-04dd236db957.png)

Touch area after:

![screenshot_631](https://user-images.githubusercontent.com/3046552/40069057-6d0b9ace-5827-11e8-9d11-c59a9ceefb8e.png)
