### ISSUE TITLE
X & Y / Two Variables sim: change to snapshots display

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/equality-explorer#108]
I think it would be a good idea to put the variable values *under* the equation when in the snapshots panel, just like you did with the Lab screen of Equality Explorer: Basics. We settled on a font size for equations back when we only had one variable, and this scenario in the Two Variables sim is unpleasant. 
![image](https://user-images.githubusercontent.com/7852916/40438124-7cef47b2-5e74-11e8-8e32-162ef091d1f1.png)

Can you align those under the equation, like you did here in the Lab screen?
![image](https://user-images.githubusercontent.com/7852916/40438213-b838dc7a-5e74-11e8-88ae-02a58731fad8.png)

**Comment by pixelzoom** [comment]
Done, you can test drive in master.   The snapshot equations now seem a bit small to me, see screenshot below.   Options are (1) live with it, or (2) reduce the number of snapshots.  @amanda-phet let me know how you want to proceed.
  
![screenshot_638](https://user-images.githubusercontent.com/3046552/40439634-ba67add8-5e78-11e8-89c2-2c2feefec1a9.png)

**Comment by pixelzoom** [comment]
I could also investigate option (3) reduce the amount of vertical space between snapshots.  That will affect _all_ screens.

**Comment by pixelzoom** [comment]
I'm going to proceed with option (3), reducing the amount of vertical space between snapshots.

**Comment by amanda-phet** [comment]
I assumed we'd need fewer snapshots, just like we have in the Lab screen. Sorry for not being clear about that.

**Comment by pixelzoom** [comment]
OK, option (2) it is.

**Comment by pixelzoom** [comment]
I made the following related changes:
- reduced the number of snapshots in the XY screen to 4
- optimized the height and spacing of snapshots for the XY and Lab screens
- removed the horizontal separator between the "Snapshots" accordion box title and the top snapshot. This was a non-standard place for a separator, and buys us a significant amount of vertical space. (The horizontal separator above the buttons is appropriate and necessary.)

@amanda-phet please verify in master for all screens, in EqEx and EqEx:Basics.

**Comment by amanda-phet** [comment]
All of these tweaks look great to me! Thanks. I think we can close this issue, unless you want to wait to close this once you publish a dev version.

**Comment by pixelzoom** [comment]
No need to wait for a dev version.  
The changes will appear in EqEx >= 1.0.0-dev.119 and  EqEx:Basics >= 1.0.0-dev.6.
