### ISSUE TITLE
snapshots: display variable values smaller than equation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#110]
Change request... Use a smaller font for variable values in snapshots so that they are smaller than the snapshot equation, and therefore deemphasized.   Definitely do this when values are shown below equation (e.g. Lab and Two Variables screens), make it optional when values are shown to the right of equation (e.g. Variables screen).

**Comment by pixelzoom** [comment]
This got complicated very quickly.  I have some design questions, so labeling with "meeting:design".

**Comment by pixelzoom** [comment]
5/24/18 design meeting:

Make the values scale relative to the equation.

**Comment by pixelzoom** [comment]
This has been implemented in master. @amanda-phet please review.

When variable values are on the same line as equations in snapshots, the variable values are the same size, e.g.:

Variables screen:
![screenshot_648](https://user-images.githubusercontent.com/3046552/40672323-b53b6cfc-632b-11e8-9979-d46f8610ec13.png)

When variable values are _below_ the equations in snapshots, the variable values are the reduce in size, currently 75%.  E.g.:

Lab screen:
![screenshot_649](https://user-images.githubusercontent.com/3046552/40672367-da44a234-632b-11e8-9d3f-70b7b4b43fc4.png)

Two Variables screen:
![screenshot_650](https://user-images.githubusercontent.com/3046552/40672407-f9310246-632b-11e8-816d-f48364bfe18e.png)

**Comment by amanda-phet** [comment]
I'm very happy with it! @kathy-phet please take a look too!

**Comment by kathy-phet** [comment]
I really like the two line ones with the smaller font below. If easy, I would like to see the one line one have the same smaller font for the (x=1) part when inline just for comparison before closing this issue. I kind of like forefronting the equation over the variable value, as opposed to equal weights. I don't have a strong opinion but it seems worth seeing how it feels at least.

**Comment by pixelzoom** [comment]
@kathy-phet said:
> ...  If easy, I would like to see the one line one have the same smaller font for the (x=1) part when inline just for comparison ...

See [1.0.0-dev.121](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.121/phet/equality-explorer_en_phet.html), comparison screenshots below.  This is committed to master, so let me know whether to keep it or revert it. 

![screenshot_648](https://user-images.githubusercontent.com/3046552/40672323-b53b6cfc-632b-11e8-9979-d46f8610ec13.png)
![screenshot_653](https://user-images.githubusercontent.com/3046552/40742975-7224ee9c-640d-11e8-98bf-839cc848d364.png)

**Comment by kathy-phet** [comment]
Adding full screen shots in context: 
![image](https://user-images.githubusercontent.com/5096804/40743320-6dce19c6-640e-11e8-9d4a-bd3cbe15434d.png)
![image](https://user-images.githubusercontent.com/5096804/40743344-7d2dca74-640e-11e8-91ec-5480c25cf0eb.png)

**Comment by kathy-phet** [comment]
My soft preference is the smaller font to distinguish it, but I can go either way here. The larger will be read better from the back of the room.

**Comment by kathy-phet** [comment]
And as I try it on my phone, the larger will be easier to read on a phone. The smaller is readable, but small.

**Comment by pixelzoom** [comment]
I have a slight preference for smaller too, especially when the equations get longer:

![screenshot_654](https://user-images.githubusercontent.com/3046552/40743784-b4deae42-640f-11e8-8523-0f55121a3319.png)

**Comment by pixelzoom** [comment]
5/31/18 design meeting:  Smaller variable values in all cases.  Closing.
