### ISSUE TITLE
deemphasize variable values in Lab screen snapshots

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#113]
`opacity: 0.75` for variable values in snapshots shown in Lab screen.

**Comment by pixelzoom** [comment]
Done in master.   I did this only for the Lab screen, example below.  It looked odd and was ineffective for situations where we're using symbolic variables (x, y).  @amanda-phet please review.

![screenshot_647](https://user-images.githubusercontent.com/3046552/40570913-24a024b6-604d-11e8-9f3e-147d731d5f28.png)

**Comment by amanda-phet** [comment]
This seems like a duplicate of #110 . @pixelzoom can we close this?

**Comment by pixelzoom** [comment]
It's not a duplicate -- #110 dealt with size, this one deals with opacity.  If the level of opacity is OK with you, feel free to close.

**Comment by amanda-phet** [comment]
I see, thanks. Yes 0.75 looks best to me.
