### ISSUE TITLE
make Snapshots accordion box collapsed by default.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#116]
From https://github.com/phetsims/equality-explorer/issues/107#issuecomment-393244027, as the result of interviews:

> (2) Change the Snapshots accordion box to be collapsed by default.

**Comment by pixelzoom** [comment]
Snapshots accordion box is now collapsed by default, in all screens. 

If this resolves interview/usability issues, I can live with it.  But aesthetically...

(1) The initial state of the sim now has a lot of negative space on the right and looks lopsided.  See for example "Numbers" screenshot below.   

(2) The different widths of the Values and Snapshots accordion boxes also bothers me a bit in the "Lab" screen. It didn't bother me when Snapshots was initially expanded. See screenshot below.  

But like I said... I can live with it if others think it's OK.

![screenshot_651](https://user-images.githubusercontent.com/3046552/40737216-5b6efc98-63fd-11e8-812c-10777667d07b.png)

![screenshot_652](https://user-images.githubusercontent.com/3046552/40737219-5ef223ae-63fd-11e8-8da9-a4cdef609d10.png)

**Comment by amanda-phet** [comment]
Aesthetically, I 100% agree, it's not great. But it proved to help students find the pickers more readily so I think it's worth the tradeoff. The Lab screen is the worst, IMO.

**Comment by pixelzoom** [comment]
5/31/18 design meeting:  Everyone is OK with default state of Snapshots being collapsed.
