### ISSUE TITLE
shadows on dragged items

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#12]
When an item is being dragged, it should have a drop shadow.  

In Slack, @amanda-phet proposed two "looks" for the shadow:

(1) Adobe Illustrator shadow effect:

![pasted image at 2017_09_28 12_56 pm](https://user-images.githubusercontent.com/3046552/31042041-623d5412-a55c-11e7-9991-04c2065c1d08.png)

(2) Simple shadow, ala Area Builder sim:

![pasted image at 2017_09_28 12_57 pm](https://user-images.githubusercontent.com/3046552/31042032-3cd1b2d6-a55c-11e7-9fcf-614ab524a0df.png)

We suspect that for the purposed of this sim, (2) will be fine.  (1) would also be problematic for items that are programmatically created (x, -x, 1, -1), since it would be difficult to match the Adobe Illustrator "look".

**Comment by pixelzoom** [comment]
[1.0.0-dev.28](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.28/equality-explorer_en.html) implements simple shadows ala Area Builder.  Shadows have xOffset=3, yOffset=3, and opacity=40%.  @amanda-phet your thoughts?

**Comment by pixelzoom** [comment]
@amanda-phet I was playing around with Area Builder some more, and noticed that it's requirements for the shadow are different.  The shadow is shown while dragging _and while animating_.   Showing the shadow while animating seems a bit unnecessary to me in Equality Explorer, and it's certainly more complicated.  Let me know your thoughts on this.

**Comment by amanda-phet** [comment]
I played around with it a bunch and really like it! I would like to try an offset of 4px each way, but I like the opacity where it is. 

The behavior you describe in Area Builder makes a lot of sense, because the shadow is there whenever the objects is *not* on the plate, but if you release the object and it is already animating toward the plate or the panel, I think it is fine to not have the shadow because it's moving fairly quickly and it's obvious that it's about to land somewhere.

**Comment by pixelzoom** [comment]
Offset of 4px for both x and y axes:
http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.29/equality-explorer_en.html

**Comment by amanda-phet** [comment]
Thanks, I like that a lot! I think this issue can be closed since we have the shadow implemented, or do you want to wait until you have all of the artwork?

**Comment by pixelzoom** [comment]
OK to close. Tracking artwork in #6.
