### ISSUE TITLE
make expanded/collapsed state of Snapshots accordion box specific to Screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#124]
Make the expanded/collapsed state of the Snapshots accordion box specific to each _Screen_, rather than to each _Scene_.   This is relevant to the _Basics_ and _Solve It!_ screens.

Email discussion:
 
@kathy-phet:
> When I was demoing equality explorer I noticed that snapshots menu - while default closed which I like - also closed again on the first intro screen when I switched between the different “scenes” of apples and such even if I had opened it on the first scene. 
> 
> I found it unexpected and a bit annoying to have to reopen the snapshots panel in each of these scenes. It seems normal to have to reopen it for different screens, but on the one screen when switching between scenes it seemed like it should remain In the state I put it. 
> 
> Thoughts? 
 
@pixelzoom:
> Each scene has it’s own set of snapshots and snapshots accordion box.  And each accordion box has it’s own expanded/collapsed state.   If you’d like all accordion boxes on a screen to share the same expanded/collapsed state, its relatively easy to do that. But FYI, in general it is not the default implementation.   Amanda, if you decide to change, please create an issue.

@amanda-phet:
> I like Kathy’s suggestion to keep the state of the snapshots consistent while on a specific screen. On the Basics screen this makes sense to me. Should we do the same for the Game screen? Within a single level, the snapshots accordion box stays open or closed as you go through challenges, but when you go to a new level it starts up minimized again. 

@pixelzoom:
> +1 to do the same for Solve It screen.

@kathy-phet:
> In the game screen, I would make it universal, not reset at a different level because it seems like it would be the same user.

**Comment by pixelzoom** [comment]
@amanda-phet Since this is a non-trivial change, I'm proceeding, so that it's done prior to code review.

**Comment by pixelzoom** [comment]
@amanda-phet @kathy-phet This is done.

@amanda-phet please review and close if all looks well.

Equality Explorer [1.0.0-dev.124](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.124/phet/equality-explorer_en_phet.html)

Equality Explorer: Basics [1.0.0-dev.11](https://phet-dev.colorado.edu/html/equality-explorer-basics/1.0.0-dev.11/phet/equality-explorer-basics_en_phet.html)

**Comment by amanda-phet** [comment]
Looks good to me and is working well.

**Comment by pixelzoom** [comment]
Reopening. We decided to do the same for the "Equality or Inequality" according box.

**Comment by pixelzoom** [comment]
Moved "Equality or Inequality" according box work to https://github.com/phetsims/equality-explorer/issues/137.
