### ISSUE TITLE
create screenshots

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#125]
These are the screenshots that will be used on the PhET website, in sim lists and on sim pages. We'll need one screenshot for each of the 3 sims in the Equality Explorer family.

@amanda-phet Please put each sim in the configuration that you'd like, take screenshots, and attached the screenshots to this issue.  I'll handle creating the final/processed screenshots that will get checked into GitHub.

**Comment by amanda-phet** [comment]
OK, here are the three I like best. Equality Explorer will need the screenshot to be taken while the +x is animating. 

![screen shot 2018-07-06 at 12 05 49 pm 2](https://user-images.githubusercontent.com/7852916/42396364-97df1968-811e-11e8-9456-6b53289af120.png)

![screen shot 2018-07-06 at 1 12 55 pm](https://user-images.githubusercontent.com/7852916/42396371-9d1df1b0-811e-11e8-82cd-0014c1418118.png)

![screen shot 2018-07-06 at 1 13 03 pm](https://user-images.githubusercontent.com/7852916/42396375-a152ab04-811e-11e8-9896-9050e2f8b1ad.png)

**Comment by pixelzoom** [comment]
@amanda-phet said:
> Equality Explorer will need the screenshot to be taken while the +x is animating.

Is the +x really necessary?  At the size that these screenshots are displayed, the +x operations are barely visible.   I.e.:

![eqex-thumb](https://user-images.githubusercontent.com/3046552/42396685-fc55ac9e-811f-11e8-848f-5db7665bfb29.png)

![eqex-page](https://user-images.githubusercontent.com/3046552/42396687-fd4b487a-811f-11e8-901c-aeaa1112c893.png)

**Comment by phet-steele** [comment]
> Is the +x really necessary? At the size that these screenshots are displayed, the +x operations are barely visible.

No it's not necessary, but it's not harmful either.

**Comment by pixelzoom** [comment]
Creating a screenshot while things are animating is a tad trickier.  But since I'm delegating that task, if you want it, you'll have it.

**Comment by pixelzoom** [comment]
... and it does make me wonder whether the screenshots were evaluated at the size that they will be displayed (thumbnail and sim webpage).  But I'll assume that you've done that.

**Comment by amanda-phet** [comment]
@phet-steele is a pro at screenshots like this but I'm not sure he is equipped to take screenshots right now. 

I did see how they look when small, and that's why I have pretty exaggerated inequalities and objects that aren't too messy on each plate. Down the road we will have larger screenshots on the sim pages so I was thinking the +x would be more visible then, but we will have additional screenshots at that time as well. So, I'm fine either way. We don't have to include the animating +x.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> @phet-steele is a pro at screenshots like this but I'm not sure he is equipped to take screenshots right now.

@phet-steele is not currently equipped.  But he tells me that @lmulhall-phet has been trained on how to create screenshots.   So assigning to @lmulhall-phet -- if you have questions, please consult with @phet-steele (process) or @amanda-phet (content).  Feel free to either check the PNG files into their respective repositories, or email them to me.

**Comment by pixelzoom** [comment]
@lmulhall-phet Reminder that if we do complete RC testing and are able to publish (tomorrow 7/18?), then we will need these screenshots in order to publish.   So raising the priority.

**Comment by pixelzoom** [comment]
We are ready to publish sims when screenshots are completed.

**Comment by KatieWoe** [comment]
How does this look instead for the operations screenshot?
![equality-explorer](https://user-images.githubusercontent.com/41024075/42898520-a019419c-8a80-11e8-8521-58c7a40855a5.png)

**Comment by amanda-phet** [comment]
@KatieWoe I'm fine showing a few snapshots, but the equation I set up was intentional so I'd like to keep that. I also want the lock to be locked.

**Comment by phet-steele** [comment]
> How does this look instead for the operations screenshot?

@KatieWoe I suppose this could be used when we need alternates.

**Comment by KatieWoe** [comment]
Sorry, miscommunication.  I misunderstood what was wanted in the screenshot.  My bad, I'll fix it.

**Comment by pixelzoom** [comment]
Screenshots received from @lmulhall-phet, approved by @amanda-phet, pushed to master and 1.0 branches. 

Closing.
