### ISSUE TITLE
close issues that are blocking publication

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#126]
This issue will attempt to list the common-code issues that must be addressed before the 1.0 branch is created for RC testing.  RC testing is scheduled to begin on July 11.  

- [x] https://github.com/phetsims/joist/issues/470
- [x] https://github.com/phetsims/joist/issues/413
- [x] https://github.com/phetsims/twixt/issues/11
- [x] https://github.com/phetsims/sun/issues/304 (@jonathanolson added as a result of dev meeting)

Assigning to @ariel-phet to ensure that this happens, since I'll be on vacation until shortly before RC testing begins.

**Comment by andrealin** [comment]
@jonathanolson will look at the first issue, https://github.com/phetsims/joist/issues/470, and @jessegreenberg will review the second, https://github.com/phetsims/joist/issues/413

**Comment by ariel-phet** [comment]
All issues addressed, assigning to @pixelzoom so he is aware.

**Comment by pixelzoom** [comment]
👍
