### ISSUE TITLE
pointer area issues

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#127]
I pulled these comments from @mbarlow12 out of https://github.com/phetsims/equality-explorer/issues/123, where he also said:

>  The only issue I found has to do with the pointer areas as noted above. This may be standard behavior (I don't have much experience with optimizing/handling/debugging pointer areas), and if so, please disregard those comments.

---

- [ ] Are pointer areas optimized, especially for touch? (run with query parameter `showPointerAreas`)
// REVIEW
  - **There appear to be some discrepancies between draggable/clickable areas and their associated sim elements. The terms in the toolboxes have non-interactive space between the pointer area lines and the objects themselves:**
<p float="left">
<img width="141" alt="ee-pointer1" src="https://user-images.githubusercontent.com/5711147/41502753-a4c34154-717e-11e8-800d-4330ada523fe.png">
<img width="131" alt="ee-pointer2" src="https://user-images.githubusercontent.com/5711147/41502754-a4d94db4-717e-11e8-874f-5c27016762a1.png">
</p>

  - **While this is most prominent in the term toolboxes, it also appears in the equation accordion toggle button, all clickable items in the snapshots accordion box, the organize button, the universal operator buttons, and the lock control.**

  - **There is also a discrepancy between the blue and red pointer area outlines for the following components: accordion box toggles, universal operator buttons, snapshot icons (incl. the delete & restore buttons), the organize button, and the variable number tweaker (incl. EE, EETwoVariables, and EEBasics Lab).**
<p float="left">
<img width="420" alt="screen shot 2018-06-16 at 4 30 14 pm" src="https://user-images.githubusercontent.com/5711147/41502915-a441bcb6-7182-11e8-8088-569fa12e6902.png">
<img width="344" alt="screen shot 2018-06-16 at 4 30 27 pm" src="https://user-images.githubusercontent.com/5711147/41502916-a4573320-7182-11e8-8be8-4efa7e6ea4de.png">
</p>

---

- [x] Do pointer areas overlap? (run with query parameter `showPointerAreas`) Some overlap may be OK depending on the z-ordering (if the frontmost object is supposed to occlude touch/mouse areas)

**Comment by pixelzoom** [comment]
> There appear to be some discrepancies between draggable/clickable areas and their associated sim elements. 

Yes, this is the purpose of pointerAreas. We typically expand the interactive (draggable/clickable) areas of an element to make it easier to drag.   The red dashed line indicates the interactive area for touch devices (aka `touchArea`), the blue dashed line indicates the interactive area for mouse devices (aka `mouseArea`).   

> While this is most prominent in the term toolboxes, it also appears in the equation accordion toggle button, all clickable items in the snapshots accordion box, the organize button, the universal operator buttons, and the lock control.

Yes, these are all as requested.  For example, here's the request for the terms in toolboxes: https://github.com/phetsims/equality-explorer/issues/68#issuecomment-387211462

> There is also a discrepancy between the blue and red pointer area outlines for the following components: 

mouseAreas (blue) and touchAreas(red) are almost always different, with touchAreas being larger.  That's what you're seeing here.

> Some overlap may be OK depending on the z-ordering (if the frontmost object is supposed to occlude touch/mouse areas)

The code review items doesn't make this clear.  But we're looking for cases where mouseAreas (blue) overlap with other mouseAreas, and ditto for touchAreas.  I took another look, and I don't see any overlap.

**Comment by pixelzoom** [comment]
@mbarlow12 Review my comment above and let me know if you have any questions.  If you're confident that there is no problem here, feel free to close.

**Comment by mbarlow12** [comment]
@pixelzoom That makes sense, and thanks for clarifying the color mapping. Closing.
