### ISSUE TITLE
Remove RichText bounds workaround

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/equality-explorer#128]
For https://github.com/phetsims/scenery/issues/769 `var RICH_TEXT_SPACE = '\u00A0'` was added to ChallengeDerivationNode, but it can be removed now.

**Comment by jessegreenberg** [comment]
I removed it and verified that there were no bounds issues with an empty string with query parameter `showAnswers`, but would still be good for @pixelzoom to be aware/review of the commit.

**Comment by pixelzoom** [comment]
OK, thanks.  This sim is now in dev testing (with the workaround), so I'll be sure to review before RC testing begins.

**Comment by pixelzoom** [comment]
Verified, closing.
