### ISSUE TITLE
colors for the scale's arrow

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#13]
The arrow on the scale is currently color coded to represent the 3 possible states of the scale, as shown below. Because the arrow is always a bright color (in all 3 states), the color change isn't very noticeable.  

green → balanced

![screenshot_399](https://user-images.githubusercontent.com/3046552/31101723-232b7614-a78c-11e7-9c4c-ecadcc91254d.png)

red → bottomed out

![screenshot_400](https://user-images.githubusercontent.com/3046552/31101748-3f4efa14-a78c-11e7-8dca-f1d4a4b0fa17.png)

orange → unbalanced (but not bottomed out)

![screenshot_401](https://user-images.githubusercontent.com/3046552/31101790-70e9be10-a78c-11e7-91c5-d364b24b3b94.png)

**Comment by pixelzoom** [comment]
[1.0.0-dev.30](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.30/equality-explorer_en.html) uses 'black' for the "unbalanced" state. Playing around with it, this seems to make the 'red' and 'green' color changes much more noticeable.  (Note that I also tried 'white' and it looked too bright.)

@amanda-phet your thought? 

![screenshot_402](https://user-images.githubusercontent.com/3046552/31102056-9ed77d7a-a78d-11e7-814a-7982dc6087a5.png)

**Comment by amanda-phet** [comment]
I've played around with it and I like the black arrow a lot. Good choice.

**Comment by pixelzoom** [comment]
Great, then closing.

**Comment by pixelzoom** [comment]
Reopening. In a request for feedback on [1.0.0-dev.48](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.48/equality-explorer_en.html), Argenta Price said via email:

> 1) When the two sides are close to, but not quite, equal, I find it difficult to tell that the balance is off balance.  When I first interacted with the sim, I put a circle on one side and a square on the other, and my reaction was "wait, are a circle and square the same weight?" because I was focusing on the scale, not looking at the equation above, and the difference is quite subtle. 
I'm not sure how to fix this. Maybe you can exaggerate the differences if they're nearly equal, but that's not great because then the amount of scale-tilt wouldn't be linearly related to the difference in weights? Or maybe you could switch the color of the arrow so that instead of being green when it's balanced and black when it's off, you make it black when it's balanced and red when it's off? I didn't notice that the arrow was green before I put anything up, so the black arrow when I was wondering "are they the same?" didn't provide me with helpful feedback. 

My reply:

> The decision process for the arrow colors is documented in https://github.com/phetsims/equality-explorer/issues/13.  I’ll reopen that issue and add your feedback.  In a nutshell, the arrow is currently ‘green’ when balanced, ‘red’ when the scale has “bottomed out”, and we formerly used ‘orange’ where we’re currently using ‘black’.
> 
> Trying to "exaggerate the differences" in some way is a slippery slope, likely to cause other problems (both implementation and conceptual), not recommended.

**Comment by pixelzoom** [comment]
@amanda-phet I'm reluctant to change our decision on colors here.  There's so much color going on in this sim, and I still think that using 'black' makes the 'red' and 'green' cases more noticeable.  The arrow is also not the sole indicator of "balanced".  Putting a single '1' on the scale is the "least movement" scenario, and the scale is still obviously not balanced.  (Solving screen will have smaller "least moment" scenarios when division operator is applied.)

**Comment by amanda-phet** [comment]
The colors make the most sense to me right now, and until we have interviews we should wait on changing any colors. 

The scale's "responsiveness" was heavily discussed in other issues so I don't think we need to rehash it, but we decided on a final responsiveness that showed some movement in all cases until the scale bottomed out, and didn't want the scale to bottom out any sooner than it currently does.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> ... we decided on a final responsiveness that showed some movement in all cases ...

This is true for the first 3 screens only.   The 4th screen (Solving) has no limitations on the coefficient for x, and (using the universal operator and division) we can end up with very small fractions.  E.g. if the scale contains '1/100 x', then even large changes in x will result in little or no perceptible change to the position of the plates.

**Comment by amanda-phet** [comment]
Thanks for clarifying @pixelzoom. I was thinking only of the first screen where we fine tuned it, and the 3rd screen where we played with scenarios with x being large. By the 4th screen we are less concerned, but if it is problematic in interviews we could take an approach similar to other interactive where they simply show an unbalanced state and a balanced state, and nothing in between.
