### ISSUE TITLE
term still in toolbox when cells filled with term

### ISSUE THREAD

**Issue by ghost** [phetsims/equality-explorer#130]
For phetsims/QA/issues/131. When the cells are completely filled with a term (e.g. lemons), I can still pick a lemon from the toolbox despite not being able to place more lemons:
![lemons](https://user-images.githubusercontent.com/31285590/41872331-bf48f008-787e-11e8-86be-5b12b37665fe.png)
Would it be a good idea to grey out the lemon and make it not pickable at this point?

**Comment by amanda-phet** [comment]
That was an idea we tossed around and I can't remember the exact path that led us to this design, but I think it's working well and didn't pose issues in interviews.
