### ISSUE TITLE
snapshots appear uninteractable

### ISSUE THREAD

**Issue by ghost** [phetsims/equality-explorer#131]
<b>Test Device</b>

MacBook Air, Hanson

<b>Operating System</b>

macOS 10.13.5, Windows 10

<b>Browser</b>

macOS:
Chrome, FF, Safari

Windows:
Chrome, Edge, FF

<b>Problem Description</b>

For phetsims/QA/issues/131. If you take a snapshot, it looks like you can't select it. (The cursor doesn't turn into a hand.)

Is there a reason for this?

<b>Visuals</b>

![ee](https://user-images.githubusercontent.com/31285590/41876474-28db6dc8-788b-11e8-94c9-340f486e1c9c.gif)

**Comment by amanda-phet** [comment]
I like this suggestion of having the cursor change when hovering over a screenshot.

**Comment by amanda-phet** [comment]
@pixelzoom can you change the cursor into a hand when hovering over a snapshot?

**Comment by pixelzoom** [comment]
Good catch, this was an oversight. Fixed in master.  @lmulhall-phet please verify.

**Comment by ghost** [comment]
Confirmed fixed in master.

**Comment by ghost** [comment]
This seems to be an issue:

![eqex](https://user-images.githubusercontent.com/31285590/42338292-8ba57ea4-8046-11e8-8641-1063b71bb530.gif)

Seen on macOS + Chrome.

**Comment by pixelzoom** [comment]
Good catch. Fixed in master, please review.

**Comment by ghost** [comment]
Fixed in master.

**Comment by pixelzoom** [comment]
👍 Closing again.
