### ISSUE TITLE
Verify that we don't run out of memory on iPad

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#136]
Related to https://github.com/phetsims/QA/issues/131 (dev test).

While working on https://github.com/phetsims/equality-explorer/issues/134, I experienced a lot of errors of the type "A problem occurred with this webpage so it was reloaded” from Safari Mobile on iPad2 (iOS 9.3.5).   This is indicative of a memory issue, and occurred while running in requirejs mode, which requires a lot more memory than a built version.   But over the past year or two, PhET has dramatically increased memory usage for sims, and this is a 5-screen sim, so we're more likely to hit the iPad memory ceiling.   And this was also a problem for Area Model, which had a similar memory footprint.

This can be verified using [Equality Explorer 1.0.0-dev.125](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.125/phet/equality-explorer_en_phet.html).

@lmulhall-phet could you please handle this, or delegate?

**Comment by ghost** [comment]
Top priority is getting Katie up to speed and other QA issues, but I will try to squeeze it in this afternoon or tomorrow afternoon.

**Comment by pixelzoom** [comment]
In a Slack discussion, @phet-steele pointed out that the numbers in https://github.com/phetsims/equality-explorer/issues/64 "show that the sim gets close to the memory limit on iPad 2, but does not surpass it", so this issue is unnecessary.   That seems reasonable, so closing.
