### ISSUE TITLE
make state of Equation accordion box specific to screen, not scene

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#137]
Similar to what was done for Snapshots accordion box in https://github.com/phetsims/equality-explorer/issues/124.  Default state is expanded.

**Comment by pixelzoom** [comment]
@amanda-phet please verify in [1.0.0-dev.126](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.126/phet/equality-explorer_en_phet.html).

**Comment by amanda-phet** [comment]
Looks great.

Just to clarify, will this change also apply to Equality Explorer: Basics?

**Comment by pixelzoom** [comment]
Yes, applies to all EqEx sims with screens that have multiple scenes.
