### ISSUE TITLE
lock Scenario 8 fails

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/equality-explorer#138]
Windows 10 Ver. 1803.17134.165

Chrome Ver. 67.0.3396.99

The sim fails scenario 8 under specific circumstances with the setup. Scenario 8, for reference;
![image](https://user-images.githubusercontent.com/22551096/42716595-7cb3ea10-86b9-11e8-90b4-49328579c5b3.png)

On the variables screen, set up the balance so that there is one "1" circle on each side at the bottom of the stack, and the rest of the right side is "x" blocks, like so;
![image](https://user-images.githubusercontent.com/22551096/42716659-d344b7b0-86b9-11e8-9ed0-dad7b9dbb0cb.png)
After following Scenario 8, the balance will look like this;
![image](https://user-images.githubusercontent.com/22551096/42716706-1469bff6-86ba-11e8-9f0a-a39e41d56131.png)
Note that the total is 36x + 1, which is impossible given there are only 36 slots available. If the upper left X is removed;
![image](https://user-images.githubusercontent.com/22551096/42716727-3d5d666a-86ba-11e8-8570-18c5441c4b34.png)
The "1" circle is revealed to have been behind it. And if the "1" is removed from the left side (not the right);
![image](https://user-images.githubusercontent.com/22551096/42716757-704f4610-86ba-11e8-928f-be4fe4d9b94f.png)
The sim starts to not work proper.

Equality Explorer Two Variables ALSO fails Scenario 8; Posting this across both might be a bit redundant, but I can copy it over if necessary.

If other scenarios fail as they're tested I'll make separate issues for them for posterity. 

Related to both https://github.com/phetsims/QA/issues/144 and https://github.com/phetsims/QA/issues/146, as both fail the scenario. 

Debug Information;
Name: ‪Equality Explorer‬
URL: https://bayes.colorado.edu/dev/html/equality-explorer/1.0.0-rc.1/phet/equality-explorer_en_phet.html?speed=0.1
Version: 1.0.0-rc.1 2018-07-13 20:18:02 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36
Language: en-US
Window: 1366x645
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"HEAD"},"axon":{"sha":"bbf84cf1","branch":"HEAD"},"brand":{"sha":"89d28f63","branch":"HEAD"},"chipper":{"sha":"9222b8ef","branch":"HEAD"},"dot":{"sha":"383e4b02","branch":"HEAD"},"equality-explorer":{"sha":"99d0d09d","branch":"HEAD"},"joist":{"sha":"f8538192","branch":"HEAD"},"kite":{"sha":"d08fb3c7","branch":"HEAD"},"phet-core":{"sha":"e9adfb5b","branch":"HEAD"},"phet-io":{"sha":"2a3c3457","branch":"HEAD"},"phet-io-wrapper-classroom-activity":{"sha":"c1caa58b","branch":"HEAD"},"phet-io-wrapper-hookes-law-energy":{"sha":"b316cfcf","branch":"HEAD"},"phet-io-wrapper-lab-book":{"sha":"fe5cd3b9","branch":"HEAD"},"phet-io-wrappers":{"sha":"d90097d8","branch":"HEAD"},"phetcommon":{"sha":"6ec8cd89","branch":"HEAD"},"query-string-machine":{"sha":"e5007cda","branch":"HEAD"},"scenery":{"sha":"3f99fe32","branch":"HEAD"},"scenery-phet":{"sha":"80fa4ab9","branch":"HEAD"},"sherpa":{"sha":"341552b7","branch":"HEAD"},"sun":{"sha":"9b94b548","branch":"HEAD"},"tandem":{"sha":"7fd76b92","branch":"HEAD"},"twixt":{"sha":"ca04b21f","branch":"HEAD"},"vegas":{"sha":"213b6a79","branch":"HEAD"},"vibe":{"sha":"1c92302b","branch":"HEAD"}}

**Comment by pixelzoom** [comment]
Reproduced on macOS + Chrome, so the problem is not specific to Windows. 

With `?ea`:

> Error: Assertion failed: opposite plate is full
window.assertions.assertFunction (assert.js:22)
animationCompletedCallback (SeparateTermsDragListener.js?bust=1531522144297:184)
step (EqualityExplorerMovable.js?bust=1531522144297:178)
step (TermCreator.js?bust=1531522144297:264)
(anonymous) (EqualityExplorerScene.js?bust=1531522144297:211)
step (EqualityExplorerScene.js?bust=1531522144297:210)
step (EqualityExplorerModel.js?bust=1531522144297:61)
stepSimulation (Sim.js?bust=1531522144297:836)
stepOneFrame (Sim.js?bust=1531522144297:769)
runAnimationLoop (Sim.js?bust=1531522144297:752)

**Comment by pixelzoom** [comment]
This is faster to reproduce by making the grid smaller with `?rows=1&columns=2&showGrid&speed=0.1`.  After step 3, we have:

![screenshot_697](https://user-images.githubusercontent.com/3046552/42717580-439c5efa-86bf-11e8-9303-5ae031504fd5.png)

For step 4, drag off the left '1'.

For step 7, the empty cell on the right plate must be filled by dragging a term from the _right_ toolbox.  If you drag a term from the _left_ toolbox with the lock on, such that the _equivalent_ term fills the cell on the right plate, then the problem doesn't occur, and the terms from step 4 go back to their respective toolboxes.

**Comment by pixelzoom** [comment]
Fixed in the above commit, to be verified in 1.0.0-rc.2.  Feel free to verify in master in the meantime.

**Comment by pixelzoom** [comment]
Note to self: This needs to be patched in 1.0 branch.

**Comment by pixelzoom** [comment]
Fixed in the above commits, to be verified in 1.0.0-rc.2. Feel free to verify in master in the meantime.

**Comment by pixelzoom** [comment]
If you encounter further Scenario 8 failures during RC testing, please test [1.1.0-dev.1](https://phet-dev.colorado.edu/html/equality-explorer/1.1.0-dev.1/phet/equality-explorer_en_phet.html) to confirm that the failures are addressed by this fix.   And please note the OS+browser here.

**Comment by EthanWJohnson** [comment]
I'm not seeing this happening in my testing anymore, so i'll mark it closed.
