### ISSUE TITLE
animating term does not re-examine the state of a full scale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#139]
Related to RC test https://github.com/phetsims/QA/issues/144.

I'm creating this issue since it's likely to come up during testing.  

To demonstrate:

1. Run equality-explorer sim with `?speed=0.05&showGrid`.
2. Go to the _Basics_ screen
2. Fill the scale, leaving one cell open, like this:

![screenshot_699](https://user-images.githubusercontent.com/3046552/42717942-ded34fda-86c1-11e8-9410-4b7e1a78a2a1.png)

3. Drag a blue square from the right toolbox, and drop it above the right plate.
4. Before the blue square reaches the empty cell, put a red sphere in the empty cell, then immediately remove something from the scale so that there is an empty cell.

Even though there is still an empty cell in the grid, the blue square will return to the toolbox.  While a term is animating, if the grid becomes full at any time, the animating term returns to the toolbox.  It does not re-examine the grid to see if it a cell opens up.   This greatly simplified the animation code, and in practice (when `speed=1`) it's not an issue. 

Assigning to @amanda-phet so that she's aware of this - please close after reading.

@lmulhall-phet FYI.

**Comment by amanda-phet** [comment]
This seems like a very reasonable simplification.
