### ISSUE TITLE
fixes to lock-scenarios.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#140]
lock-scenarios.md describes the testing scenarios for the lock feature.  This document has never been used by anyone expect me.  So while testing the lock feature, QA will also be testing this document.

**Comment by pixelzoom** [comment]
@KatieWoe Thanks for pointing out the buggy scenario descriptions that I've fixed above.  Have you been through all of the scenarios?  If so, and you've found no other problems, then I'll close this issue.

**Comment by KatieWoe** [comment]
We are going through the scenarios on each device and on each browser.  I have finished the iPad 2 and am still working on the Windows 10 Firefox.  I have been stopping to report problems as they're found.

**Comment by pixelzoom** [comment]
The QA team has been through all of the scenario descriptions, so I'll close this.
