### ISSUE TITLE
make scoreboard float to the top of the browser window

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#144]
... to compensate for incorrect layout bounds on iOS (see https://github.com/phetsims/joist/issues/500) where things currently look like this:

![42830755-916ef420-89a9-11e8-894b-3efcd81cda4e](https://user-images.githubusercontent.com/3046552/42833819-7fc51c64-89b2-11e8-94e6-acc23f0c9d9b.jpeg)

Related to RC testing https://github.com/phetsims/QA/issues/144.

**Comment by pixelzoom** [comment]
Changed in 1.0 and master, to be verified in 1.0.0-rc.2.

**Comment by KatieWoe** [comment]
Possible to hide scoreboard behind tabs
Test device:
iPad2
Operating System:
iOS 9.3.5
Browser:
Safari
Problem description:
For phetsims/QA/issues/148
The Pink Scoreboard can be hidden behind newly created tabs briefly on an iPad.  When creating a new tab in safari to create a tab bar, the scoreboard will not lower to a new position and will therefore be hidden behind the new tab bar.  This is corrected if you change the orientation of the iPad.
Steps to Reproduce:
1. Make sure the tab bar on Safari is empty
2. Go to Solve It! screen and choose a level
3. Open a new tab in safari and choose a site, such as google
4. Without closing the new tab, return to the simulation.  Make sure you do not change the orientation of the iPad.
5. When you return, part of the scoreboard will be hidden.
6. Rotate the iPad to change orientation, and rotate it back, and the scoreboard will no longer be hidden.

**Comment by phet-steele** [comment]
@KatieWoe let me introduce you to this awesome issue: https://github.com/phetsims/joist/issues/234 (I think this is what you are describing, you didn't post a screenshot)

@pixelzoom the floaty-ness is looking good. Closing.

**Comment by pixelzoom** [comment]
Ah yes, the lovely complications of rotating an iPad.   Not something I can address here, as @phet-steele pointed out.  So we'll call this good.

**Comment by ghost** [comment]
@pixelzoom, @phet-steele confirmed same issue.
