### ISSUE TITLE
add to Gooru and Edmodo

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#146]
From the master checklist in #1:

> - [ ] Add to Edmodo
> - [ ] Add to Gooru (signed in as phethelp)

In https://github.com/phetsims/equality-explorer/issues/1#issuecomment-407917529, @amanda-phet said:
> @ariel-phet can you please add to Gooru and Edmodo?

**Comment by ariel-phet** [comment]
Added, closing
