### ISSUE TITLE
Eliminate usage of frameStartedEmitter 

### ISSUE THREAD

**Issue by samreid** [phetsims/equality-explorer#148]
From https://github.com/phetsims/joist/issues/534, we would like to eliminate `frameStartedEmitter`.  Equality Explorer uses it like so:

```js
// Things to do after the sim has loaded, when this Node has a valid location.
var frameStartedCallback = function() {

  // This Node's location
  var location = termsLayer.globalToLocalPoint( self.parentToGlobalPoint( self.center ) );

  // assign to termCreator's location
  if ( options.sign === 1 ) {
    termCreator.positiveLocation = location;
  }
  else {
    termCreator.negativeLocation = location;
  }

  // Remove this function, so that it's called only once.
  phet.joist.sim.frameStartedEmitter.removeListener( frameStartedCallback );
};
phet.joist.sim.frameStartedEmitter.addListener( frameStartedCallback ); // removeListener after first call
```

It seems like this code needs to be called after the nodes have been attached to the view.  Could this be done through `stepSimulationEmitter`?

**Comment by pixelzoom** [comment]
@samreid asked:
>  ... Could this be done through `stepSimulationEmitter`?

No idea. See https://github.com/phetsims/joist/issues/534#issuecomment-459176061.

**Comment by pixelzoom** [comment]
`stepSimulationEmitter` as currently implemented is not a replacement for `frameStartedEmitter`.  It does not notify listeners at the start of the frame, it notifies them at the end of the frame.  See (2) in https://github.com/phetsims/joist/issues/534#issuecomment-459181469.  The callback in this sim needs to be executed _before_ the first step is performed by Sim.js.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/joist/issues/534#issuecomment-459205595, @samreid proposed that using `sim.endedSimConstructionEmitter` might be more appropriate.   I experimented with it, and it seems to work.  But a couple of questions before I commit and push:

(1) Does `endedSimConstructionEmitter` emit after the scenegraph is built? The documentation says "indicates sim construction completed", which is not helpful.

(2) I see zero uses of `endedSimConstructionEmitter` in other sims. Why was it added? Is this its intended purpose? Has it been tested?

**Comment by pixelzoom** [comment]
Here's a patch for using `endedSimConstructionEmitter` in `TermCreatorNode`.

```
Index: js/common/view/TermCreatorNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/TermCreatorNode.js	(revision e29bf19e52364ecc7bfa0bcc367043d2f9ab8469)
+++ js/common/view/TermCreatorNode.js	(date 1548908438000)
@@ -59,8 +59,8 @@
       }
     ) );
 
-    // Things to do after the sim has loaded, when this Node has a valid location.
-    var frameStartedCallback = function() {
+    // Things to do after the sim has been constructed, when TermCreatorNode has a valid location.
+    phet.joist.sim.endedSimConstructionEmitter.addListener( function() {
 
       // This Node's location
       var location = termsLayer.globalToLocalPoint( self.parentToGlobalPoint( self.center ) );
@@ -72,11 +72,7 @@
       else {
         termCreator.negativeLocation = location;
       }
-
-      // Remove this function, so that it's called only once.
-      phet.joist.sim.frameStartedEmitter.removeListener( frameStartedCallback );
-    };
-    phet.joist.sim.frameStartedEmitter.addListener( frameStartedCallback ); // removeListener after first call
+    } );
   }
 
   equalityExplorer.register( 'TermCreatorNode', TermCreatorNode );
```

**Comment by samreid** [comment]
> (1) Does endedSimConstructionEmitter emit after the scenegraph is built?

Yes, it is called after all screen models and views are fully constructed.

> (2) I see zero uses of endedSimConstructionEmitter in other sims. Why was it added? Is this its intended purpose? Has it been tested?

From the documentation:

```js
// This was added for PhET-iO but can be used by any client.
```

It is exercised frequently by PhET-iO and also leveraged by Legends of Learning.

**Comment by samreid** [comment]
I added a note to the documentation, let me know if that helps!

**Comment by pixelzoom** [comment]
Replaced frameStartedEmitter with endedSimConstructionEmitter in the above commits.  Tested all screens manually after startup.  Tested with `?ea&fuzz`.  

@samreid please take a quick peek, close if this looks OK.

**Comment by samreid** [comment]
The commits look good.  I also added console.log statements to verify that they were happening at the appropriate time.  However, this revealed that one step() is called before `endedSimConstructionEmitter` emits.  This will not cause a problem in practice, since the splash screen is still showing when the step() runs, but I'll create a joist issue where we can discuss further.  

Up to you if you want to close this issue.

**Comment by pixelzoom** [comment]
#149 immediately started in CT after making this switch, so I'm reverting.  And I don't have time to investigate this.  So if you think it's vital to eliminate frameStartedEmitter, someone else will need to handle.

**Comment by samreid** [comment]
In https://github.com/phetsims/joist/issues/534 it was determined we will keep both `frameStartedEmitter` and `frameEndedEmitter`.  However, we also changed https://github.com/phetsims/joist/issues/550 to make `endedSimConstructionEmitter` emit before the  first step.  I'll leave it up to you if you want to reinvestigate using `endedSimConstructionEmitter`, or leave it as it is and close.

**Comment by pixelzoom** [comment]
I'm going to leave it as is.  Closing.
