### ISSUE TITLE
CT failure invalid value for range

### ISSUE THREAD

**Issue by zepumph** [phetsims/equality-explorer#156]
From https://github.com/phetsims/axon/issues/274#issuecomment-577737728

CT is failing after work was done in that issue to validate the range more. The problem seems to be in `Variable.js`. By the looks of this, there is a misspelled var. I think `xRange` may want to be `range`.

**Comment by zepumph** [comment]
After further investigation, the passed in range doesn't seem to be correct for the passed in value. Here is a patch that allows the sim to run:

<details>

```diff
Index: js/basics/model/AnimalsScene.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/basics/model/AnimalsScene.js	(revision 7107b4ee6413ebeb20d556d2f32dcd25ada022cd)
+++ js/basics/model/AnimalsScene.js	(date 1579800710959)
@@ -15,6 +15,7 @@
   const Image = require( 'SCENERY/nodes/Image' );
   const inherit = require( 'PHET_CORE/inherit' );
   const ObjectVariable = require( 'EQUALITY_EXPLORER/basics/model/ObjectVariable' );
+  const Range = require( 'DOT/Range' );
 
   // images
   const catImage = require( 'image!EQUALITY_EXPLORER/cat.png' );
@@ -32,7 +33,7 @@
     const variables = [
 
       // name, image, shadow
-      new ObjectVariable( 'dog', dogImage, dogShadowImage, { value: 11 } ),
+      new ObjectVariable( 'dog', dogImage, dogShadowImage, { value: 11, range: new Range( 0, 11 ) } ),
       new ObjectVariable( 'cat', catImage, catShadowImage, { value: 4 } ),
       new ObjectVariable( 'turtle', turtleImage, turtleShadowImage, { value: 6 } )
     ];
Index: js/common/model/Variable.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/Variable.js	(revision 7107b4ee6413ebeb20d556d2f32dcd25ada022cd)
+++ js/common/model/Variable.js	(date 1579800705384)
@@ -39,7 +39,7 @@
     // @public the value of the variable
     this.valueProperty = new NumberProperty( options.value, {
       numberType: 'Integer',
-      range: this.xRange
+      range: this.range
     } );
   }
 

```
</details>

Assigning to responsible dev to see if this seems like the correct approach for the fix.

**Comment by pixelzoom** [comment]
@zepumph can you speculate on why it's necessary to provide `range` for 'dog':

`new ObjectVariable( 'dog', dogImage, dogShadowImage, { value: 11, range: new Range( 0, 11 ) } )`

... but not for 'cat' and 'turtle'?

**Comment by zepumph** [comment]
I know nothing about the sim, and don't think my patch is necessarily the best. It was just something that got the sim running. The reason only dog was needing a special range was because of the default provided by `ObjectVariable`, which is [1,10].

**Comment by pixelzoom** [comment]
Thanks for investigating @zepumph.  Patch in https://github.com/phetsims/equality-explorer/issues/156#issuecomment-577787384 is not appropriate.   

Fixed in the above commit. Tested with and without https://github.com/phetsims/axon/commit/d4b681297503cd91bb83ef1cdc78f162e48fa881 (which is still up for discussion in https://github.com/phetsims/axon/issues/274.

I'll leave this open until CT verifies.

**Comment by pixelzoom** [comment]
Added an assertion in the above commit so that this type of problem will be caught before it ever gets to NumberProperty validation.

**Comment by pixelzoom** [comment]
Passing CT, closing.
