### ISSUE TITLE
User suggestion: undo feature

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/equality-explorer#162]
> Is there anyway you could add an undo button for the students who make a mistake while they are learning so they can go back instead of starting a new problem? They are having a hard enough time trying to learn how to 'undo' the operations in the right order.  Getting them to 'undo' their mistakes is proving difficult.

**Comment by amanda-phet** [comment]
@oliver-phet can you forward this user email to me so I can reply? We won't be making an undo button.

**Comment by amanda-phet** [comment]
Responded 2/9/21.

Thank you for your suggestion! I'm so glad to hear you're using the sim with your students. 

When we interviewed students using the Equality Explorer sim, we found that *not* having an undo button was a *feature* of the game. I observed students wanting to undo their operation, and had to use the inverse operation to do so. That process led them to a more solid understanding of inverse operations, and after that experience, they solved successive problems with more ease. 

I'm wondering if you could encourage students to use the Operations screen first for a while, as part of your lesson, before playing the game. Ask them to perform an operation there (so it feels low-stakes), and then figure out which operation will "undo" it, and look for patterns. They might notice certain operations are inverses, or that the scale is always balanced (!), or something else! Then do a quick discussion to have students share the patterns they noticed. 

Then when they play the game, if they do an operation they didn't want, ask them how to undo it to go back to where they were. They will start to see the relationship between inverse operations, and might extend that knowledge to "undoing" operations in the equation they are trying to solve! 

I'd recommend an activity sheet with something like this. Maybe you can use this as a warm-up in an upcoming lesson. 

1. Suppose you have x = 1 on the balance. What value of x makes the scale balance? (ans: x = 1) 
2. Keep x = 1 on the balance, and fill in the table with the following: 
a. Using the operation tool, do an operation on both sides of the balance. 
b. What does it look like now? 
c. Find the one that will "undo" it.

Original operation | What does it look like now? | Operation that will “undo” the original operation
-- | -- | --
Example:       + 6 | x + 6 = 7 | – 6
  |   |  
  |   |  
  |   |  
  |   |  


3. What patterns do you notice? 


If you decide to try this mini-lesson, let me know how it goes! And thank you again for reaching out.
