### ISSUE TITLE
Add a query parameter to constrain Level 1 challenges to have positive coefficients.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#163]
On Slack, @kathy-phet requested a query parameter that constrains the _Solve It!_ challenges for Level 1 to have positive coefficients for _x_.

The full specification for the Level 1 challenges can be found in this design doc: https://docs.google.com/document/d/1vG5U9HhcqVGMvmGGXry28PLqlNWj25lStDP2vSWgUOo/edit#heading=h.tuc0yye6ee0b.  Here's a summary of the 3 types of challenges in Level 1:

* `ax = c`, where the range of `a` is `[-10,10]`, and a is not 0 or 1
* `x + b = c`
* `x/d = c`, where the range of `d` is `[-10,10]`, and d is not 0 or 1

This query parameter will constrain `a` and `d` to positive values, that is [2,10]. 

In addition to adding this in master, @kathy-phet asked that it be added to a RC created on the current release branch.  That RC version will not be QA tested or published, but will be used for a study with a 6th-grade class.

Query parameter name will be `easyLevel1`, a flag.

Deadline is 4/6/21 @ 1:15pm, for discussion at a team meeting. Students will use it on Friday, 4/9/21.

**Comment by pixelzoom** [comment]
@kathy-phet here's a dev version, to confirm that this is behaving as desired:

https://phet-dev.colorado.edu/html/equality-explorer/1.1.0-dev.2/phet/equality-explorer_en_phet.html?easyLevel1

If this looks OK, let me know and I'll patch it into the 1.0 release branch.

**Comment by pixelzoom** [comment]
In Slack, @kathy-phet verified that 1.1.0-dev.2 is behaving as desired.  I'll proceed with patching into the 1.0 branch, and creating the RC.

**Comment by pixelzoom** [comment]
Patching the 1.0 branch was a tad more work than usual.  I could not cherry-pick, because the branch predates the conversion to ES6.  So I had to manually patch the affected files.  Anyway...

The RC version has been deployed. The link, with `easyLevel1` query parameter, is:

https://phet-dev.colorado.edu/html/equality-explorer/1.0.13-rc.1/phet/equality-explorer_en_phet.html?easyLevel1

@kathy-phet let me know if there's anything else to be done here.

**Comment by kathy-phet** [comment]
Thanks! Closing.

**Comment by pixelzoom** [comment]
Reopening.

Now that this change is in both master and the 1.0 release branch, there are consequences.  

First, is this going to be a new "official" feature?  If so, it needs to be added to the query-parameters spreadsheet, QA tested, etc.

Second, there's the issue of having an unpublished/untested change in a production branch. For the 1.0 branch, this change will automatically be published, without having been QA tested, the next time a 1.0 maintenance release occurs. That came up today, when @samreid needed to do a maintenance release.  Luckily that maintenace release involved a PhET-iO feature, so equality-explorer was skipped. But the next time there is a general maintenance release, this query parameter will get published in a production version.

@kathy-phet How do you want to proceed with this feature?

**Comment by kathy-phet** [comment]
@amanda-phet and I can discuss about the future of this query parameter after we hear back from the teacher about how the sim use went. So in a week or so.

**Comment by pixelzoom** [comment]
@amanda-phet @kathy-phet checking in to see how use of this query parameter went.  How would you like me to proceed?

**Comment by amanda-phet** [comment]
@kathy-phet and I discussed this. 

@pixelzoom I'm thinking I'd like to add a new level between 1 and 2 (so a new level 2). 

**Level 1**: "easy" level 1 [what is currently `?easyLevel1`] 
**Level 2**: challenges with negative coefficients [modified Level 1, only challenge types 1 and 3, with a = [-10,-1] and d = [-10,-1] with the first challenge being type 1 and a=-1] 
**Level 3**: [current level 2, no change] 
**Level 4**: [current level 3, no change] 
**Level 5**: [current level 4, no change] 

This is obviously a major change, so we should discuss the cost and timeline. We can do it here or schedule a quick design meeting to review questions. I tried to summarize level 2 above, but it would probably benefit from a more robust spec.

**Comment by pixelzoom** [comment]
This would be relatively straightforward, but time consuming.   Here are the tasks and time estimates.

@amanda-phet design:
*  Update [the design doc](https://docs.google.com/document/d/1vG5U9HhcqVGMvmGGXry28PLqlNWj25lStDP2vSWgUOo/edit.). Because it is referenced in the code for each level's challenge generator, it's important that the doc is kept up-to-date.
* Decide what the layout should be for 5 level selection buttons (versus the current 4 buttons).

@pixelzoom implementation (2-4 hours):
* Add a button to the level selection screen, adjust layout.
* Rename the challenge generators for levels 2, 3, 4 (to 3, 4, 5).
* Split the level 1 challenge generator into two generators, for levels 1 & 2.
* Tweak the implementation to meet the new requirements for level 2.
* Delete the `easyLevel1` query parameter.

@pixelzoom maintenance release (1-3 hours):
* Patch into 1.0 branch
* QA testing, RC spot-check of the _Solve It_ screen.
* Publish 1.0 maintenance release

**Comment by kathy-phet** [comment]
@pixelzoom - We have funding for this, and it would be good to have for our grant work. There is no current deadline for this work, but in general I think it would be nice to have it published with this by start of 2021-22 school year.

**Comment by pixelzoom** [comment]
Sounds good.  As @amanda-phet suggested, let's schedule a quick design meeting about this, to make sure we're all on the same page.

**Comment by pixelzoom** [comment]
Since revising the game is a different (and larger) task than adding a query parameter, I've moved the game revision to https://github.com/phetsims/equality-explorer/issues/164.  Let's continue the discussion there.   

Closing.

**Comment by pixelzoom** [comment]
Reopening to remove `easyLevel1` query parameter, for #164.

**Comment by pixelzoom** [comment]
`easyLevel1` query parameter was removed from master and 1.0 in the above commits. 

[1.0.13-rc.1](https://phet-dev.colorado.edu/html/equality-explorer/1.0.13-rc.1/phet/equality-explorer_en_phet.html) was the only version to support `easyLevel1`. 

Closing.

**Comment by pixelzoom** [comment]
I've finished this work, but noted a problem in Level 2 specification.  In the [design doc](https://docs.google.com/document/d/1vG5U9HhcqVGMvmGGXry28PLqlNWj25lStDP2vSWgUOo/edit#):

> First challenge should be type #1 with a=-1. 
> Second challenge should be type #3 with a=-1

Type #3 does not include `a`.  And if this was supposed to be `d=-1`, then the first two challenges will both be of the form `-x = c`, and `c` is highly likely to be the same for both challenges (and changing that would be a big task.)   So...  For now, I've ignore the "Second challenge..."  specification, and Level 2 starts with one challenge of the form `-x = c`.

@amanda-phet please review in [1.1.0-dev.3](https://phet-dev.colorado.edu/html/equality-explorer/1.1.0-dev.3/phet/equality-explorer_en_phet.html), and let me know if you'd like to make changes.
