### ISSUE TITLE
Changes to Solve It! game

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#164]
In https://github.com/phetsims/equality-explorer/issues/163, we added the `easyLevel1` query parmeter that was used in a study.  It simplified the challenges for level 1. 

As a result of that study, changes to the game were proposed in https://github.com/phetsims/equality-explorer/issues/163#issuecomment-827778502. 

@amanda-phet said:
> 
> @kathy-phet and I discussed this. 
> 
> @pixelzoom I'm thinking I'd like to add a new level between 1 and 2 (so a new level 2). 
> 
> **Level 1**: "easy" level 1 [what is currently `?easyLevel1`] 
> **Level 2**: challenges with negative coefficients [modified Level 1, only challenge types 1 and 3, with a = [-10,-1] and d = [-10,-1] with the first challenge being type 1 and a=-1] 
>  **Level 3**: [current level 2, no change] 
>  **Level 4**: [current level 3, no change] 
> **Level 5**: [current level 4, no change] 
> 
> This is obviously a major change, so we should discuss the cost and timeline. We can do it here or schedule a quick design meeting to review questions. I tried to summarize level 2 above, but it would probably benefit from a more robust spec.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/equality-explorer/issues/163#issuecomment-827950501, I provided a list of tasks and time estimates:

This would be relatively straightforward, but time consuming.   Here are the tasks and time estimates.

@amanda-phet design:
*  Update [the design doc](https://docs.google.com/document/d/1vG5U9HhcqVGMvmGGXry28PLqlNWj25lStDP2vSWgUOo/edit). Because it is referenced in the code for each level's challenge generator, it's important that the doc is kept up-to-date.
* Decide what the layout should be for 5 level selection buttons (versus the current 4 buttons).

@pixelzoom implementation (2-4 hours):
* Add a button to the level selection screen, adjust layout.
* Rename the challenge generators for levels 2, 3, 4 (to 3, 4, 5).
* Split the level 1 challenge generator into two generators, for levels 1 & 2.
* Tweak the implementation to meet the new requirements for level 2.
* Delete the `easyLevel1` query parameter.

@pixelzoom maintenance release (1-3 hours):
* Patch into 1.0 branch
* QA testing, RC spot-check of the _Solve It_ screen.
* Publish 1.0 maintenance release

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/equality-explorer/issues/163#issuecomment-828000540, @kathy-phet said:
> @pixelzoom - We have funding for this, and it would be good to have for our grant work. There is no current deadline for this work, but in general I think it would be nice to have it published with this by start of 2021-22 school year.

I replied:
> Sounds good. As @amanda-phet suggested, let's schedule a quick design meeting about this, to make sure we're all on the same page.

**Comment by pixelzoom** [comment]
For discussion at 4/29 design meeting...

 - [x] Do you want this in a 1.0 maintenance release? It's not going to be straightforward to patch into the 1.0 branch, because that branch pre-dates the switch to ES6.
 
**DECISION: master only, no maintenance release.**

-  [x] Clarify level 1 requirements
> Level 1: "easy" level 1 [what is currently ?easyLevel1]

To clarify... You still want all 3 challenge types in level 1, but types 1 & 3 should be adjusted as for the easyLevel1 query parameter. Is that correct?

**DECISION: Yes, that is correct.**

- [x] Review level 2 requirements

> Level 2: challenges with negative coefficients [modified Level 1, only challenge types 1 and 3, with a = [-10,-1] and d = [-10,-1] with the first challenge being type 1 and a=-1]

**DECISION: See specification of Level 2 in [design doc](https://docs.google.com/document/d/1vG5U9HhcqVGMvmGGXry28PLqlNWj25lStDP2vSWgUOo/edit#heading=h.ox64kcpeabe8).  I will remove yellow highlighting when I'm done.**

- [x] Level translations

Level descriptions are translated strings. They appear in the "Info" dialog, and in the scoreboard.  All of the translated strings will now be incorrect.   Should we attempt to fix the translated strings? Or should be abandon the current string keys and create new keys for all level descriptions?  I recommend the latter.  In either case, inform translators that these need to be translated.

**DECISION: Abandon current string keys, create new string keys, inform translators of the update.**

- [x] We need a new description for Level 2 challenges. The current values are:

```js
  "level1": {
    "value": "<b>Level 1</b>  One-step equations"
  },
  "level2": {
    "value": "<b>Level 2</b>  Two-step equations"
  },
```

**DECISION: "level2" -> "<b>Level 2</b>  One-step equations with negative coefficients"**

- [x] Button layout

Here are the options for button layout.  Spacing is adjustable in either case.

Single row:
<img width="1031" alt="screenshot_967" src="https://user-images.githubusercontent.com/3046552/116559292-8646bc00-a8bd-11eb-8a24-0d04cf938df5.png">

Grid:
<img width="1034" alt="screenshot_968" src="https://user-images.githubusercontent.com/3046552/116559304-8a72d980-a8bd-11eb-931b-42ead55426a1.png">

**DECISION: Single row, with `spacing: 20`.**

- [x] Remove `easyLevel1` query parameter from 1.0 branch. 

**DECISION: Yes, to prevent it from being added to a production release by the maintenance release process.**

**Comment by pixelzoom** [comment]
Here are the options for button layout.  Spacing is adjustable in either case.

Single row:
<img width="1031" alt="screenshot_967" src="https://user-images.githubusercontent.com/3046552/116559292-8646bc00-a8bd-11eb-8a24-0d04cf938df5.png">

Grid:
<img width="1034" alt="screenshot_968" src="https://user-images.githubusercontent.com/3046552/116559304-8a72d980-a8bd-11eb-931b-42ead55426a1.png">

**Comment by pixelzoom** [comment]
> Level 1: "easy" level 1 [what is currently `?easyLevel1`]

To clarify... You still want all challenge types in level 1, but type 1 & 3 should be adjusted as for the `easyLevel1` query parameter.  Is that correct?

**Comment by pixelzoom** [comment]
4/29/21 design meeting @amanda-phet @kathy-phet @pixelzoom 

We discussed the items in https://github.com/phetsims/equality-explorer/issues/164#issuecomment-829226364.  Decisions are interspersed in that comment with "DECISION".

**Comment by pixelzoom** [comment]
A bug chunk of this has been completed in the above commit.

Still to be done:
- [x] Revise level 1 challenge generator
- [x] Revise level 2 challenge generator
- [x] Remove `easyLevel1` query parameter in master and 1.0, in https://github.com/phetsims/equality-explorer/issues/163

**Comment by pixelzoom** [comment]
I've finished this work, but noted a problem in Level 2 specification.  In the [design doc](https://docs.google.com/document/d/1vG5U9HhcqVGMvmGGXry28PLqlNWj25lStDP2vSWgUOo/edit#):

> First challenge should be type 1 with a=-1. 
> Second challenge should be type 3 with a=-1

Type 3 does not include `a`.  And if this was supposed to be `d=-1`, then the first two challenges will both be of the form `-x = c`, and `c` is highly likely to be the same for both challenges (changing that would be a big task.)   So...  For now, I've ignored the "Second challenge..."  specification, and Level 2 starts with one challenge of the form `-x = c`.

@amanda-phet please review in [1.1.0-dev.3](https://phet-dev.colorado.edu/html/equality-explorer/1.1.0-dev.3/phet/equality-explorer_en_phet.html), and let me know if you'd like to make changes.

**Comment by pixelzoom** [comment]
By the way... Running with `?showAnwers` might make this easier to review.  To use that query parameter, you need to follow the instructions to identify yourself as a PhET team member in your browser, see the "How to identify yourself as a PhET team member" section of https://github.com/phetsims/special-ops/blob/master/doc/phetTeamMember.md#how-to-identify-yourself-as-a-phet-team-member

**Comment by amanda-phet** [comment]
>Type 3 does not include a. And if this was supposed to be d=-1, then the first two challenges will both be of the form -x = c, and c is highly likely to be the same for both challenges (changing that would be a big task.) So... For now, I've ignored the "Second challenge..." specification, and Level 2 starts with one challenge of the form -x = c. 

Thanks for pointing that out. We should only specify the first challenge and the rest can be random. I've updated the design doc.

**Comment by amanda-phet** [comment]
The levels all look perfect!

**Comment by pixelzoom** [comment]
Excellent.   Let me know if there's anything else to be done here.  If not, feel free to unassign yourself.

In the meantime, I'll label this as "fix-awaiting-deploy" for verification in the next QA cycle.

**Comment by liammulh** [comment]
The changes described above seem to have been implemented correctly. Reassigning @pixelzoom.

**Comment by pixelzoom** [comment]
Thanks @liam-mulhall.

Closing.

**Comment by pixelzoom** [comment]
Assigning to @amanda-phet to decide when and how this gets deployed. Note that this work was only done in master, so a maintenance release would require more work.

**Comment by amanda-phet** [comment]
@pixelzoom I think we are ready to publish this sim, and QA has capacity to test. Can you go ahead and start the maintenance release process?

**Comment by pixelzoom** [comment]
Unassigning until there's a QA plan in https://github.com/phetsims/equality-explorer/issues/167.

**Comment by pixelzoom** [comment]
@amanda-phet asked:
> ... Can you go ahead and start the maintenance release process?

From https://github.com/phetsims/equality-explorer/issues/164#issuecomment-829226364:
> **DECISION: master only, no maintenance release.***

This cannot be done via a maintenance release. The 1.0 branch is pre-ES6, and cannot be easily patched. Re-publishing requires a full QA process.

Unassigning until there's a QA plan in https://github.com/phetsims/equality-explorer/issues/167.

**Comment by KatieWoe** [comment]
@pixelzoom to clarify:
QA should test that
1. The changes to level described in https://github.com/phetsims/equality-explorer/issues/164#issue-870485681 took place
2. The levels can all be completed as expected
3. No new bugs in the game were introduced

Is this correct? Or is there an aspect that I'm missing?

**Comment by pixelzoom** [comment]
Yes @KatieWoe, that's correct.   And the challenges for each level are fully described in [Equality Explorer - game challenge generation](https://docs.google.com/document/d/1vG5U9HhcqVGMvmGGXry28PLqlNWj25lStDP2vSWgUOo/edit#heading=h.73cauoe0e0wx) (aka, "the design doc").

**Comment by KatieWoe** [comment]
Challenges look ok, but leaving open for now due to https://github.com/phetsims/equality-explorer/issues/169

**Comment by pixelzoom** [comment]
#169 is resolved and in review, so this issue can be closed.
