### ISSUE TITLE
requirements for "sum to zero" feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#17]
In Equality Explorer, we want to remove similar items that sum to zero.  The design document doesn't adequately describe this feature, and there has been related discussion in Slack that needs to be captured.  So I'm creating this issue, which can be referred to in the [design document](https://docs.google.com/document/d/1xu9nawWcndFqgg5zyCGm25h-OFUsuFYnXF3QHW42spQ/edit#).

Currently, the entire specification in the design document is:

> When a 1 and -1 overlap, they become a 0 and fade away. We’d like to mimic the behavior seen in Expression Exchange. 

Additional details (gathered from 11/1/2017 Slack chat with @amanda-phet):

- [x] this feature involves 2 items; one on the scale, one being dragged
- [x] when 1 and -1 overlap during a drag, they both get a halo
- [x] when x and -x overlap during a drag, they both get a halo
- [x] when 1 and -1 overlap at the end of a drag, they are immediately replaced by '0'
- [x] when x and -x overlap at the end of a drag, they are immediately replaced by '0x'
- [x] 1, -1 and '0' have a circular yellow halo
- [ ] ❌ x, -x and '0x' have a rectangular yellow halo (see https://github.com/phetsims/equality-explorer/issues/17#issuecomment-350806089)
- [x] halos have a similar look to those in the "Negatives" screen of Expression Exchange
- [x] when an item on the scale is replaced in this manner, items on the scale above it drop down immediately
- [x] 0 and 0x fade out, and they are not interactive
- [x] when inverse items overlap, hide the drop shadow on the dragging item

@amanda-phet does this describe the feature?

**Comment by pixelzoom** [comment]
Added to the design document:
> (This “sum to zero” feature is more completed described in `https://github.com/phetsims/equality-explorer/issues/17`.)

**Comment by pixelzoom** [comment]
About this requirement:
> We’d like to mimic the behavior seen in Expression Exchange.

Expression Exchange is doing the animation in the model, which was surprising to me. Talking with @jbphet, it sounds like there's a reason to represent zero in the model, so he chose to do the animation there.  

In Equality Explorer, there is no reason to represent zero in the model. The '0' and '0x' serves only as visual indicators that 2 terms have been deleted because they sum to zero. So I'll be doing these as view animations, which means I'll be using TWEEN (3rd party library).  

Since we're using different methods of animation, there may be subtle differences in the "look".  I'm confident that Equality Explorer can "mimic" the animation in Expression Exchange, but I'm not going to try to match it exactly. 

@amanda-phet please let me know asap if you anticipate this being a problem.

**Comment by amanda-phet** [comment]
The description above sounds accurate. Can you clarify: does "end of a drag" refer to the moment when the mouse click ends? 

A few comments: 
* I haven't seen the yellow halo yet, so there's a chance I'll want to change it if something about it doesn't look good.
Are you thinking something like this?
![screen shot 2017-11-03 at 10 42 30 am](https://user-images.githubusercontent.com/7852916/32385441-beeb2bb6-c083-11e7-992c-18e5c22c5a3e.png)
I also wonder if a white box behind the number would look good as it fades:
![screen shot 2017-11-03 at 10 49 54 am](https://user-images.githubusercontent.com/7852916/32385776-cf7842f6-c084-11e7-9d06-465c7b5ce1b9.png)

* We should add that the 0 and 0x appears on the _top layer_ so that it is visible over an object (when applicable). 
* The timing of the fade out of 0 and 0x should be similar to Expression Exchange.

I do not see a problem with not representing zero in the model, and am fine if there are subtle differences.

**Comment by pixelzoom** [comment]
@amanda-phet asked:
> does "end of a drag" refer to the moment when the mouse click ends?

Yes, but it's generally "pointer" not "mouse click".

FYI, a drag cycle has 3 phases:
• start - when the pointer goes down (e.g. mouse button pressed, finger contacts tablet)
• drag - moving the pointer while its down (e.g. mouse moved, finger moved)
• end - when the pointer is released (e.g. mouse button released, finger removed from tablet)

> I haven't seen the yellow halo yet, so there's a chance I'll want to change it if something about it doesn't look good.

I'll make the look of what's behind the '0' and '0x' independent of the halos around items (1,-1,x,-x).  So if you don't like the look, we can change it. (I'm confident that you'll like it :)

> The timing of the fade out of 0 and 0x should be similar to Expression Exchange.

Will do.

**Comment by pixelzoom** [comment]
Here's a list of subtle issues and non-so-obvious scenarios that we need triage, numbered to make it easier to refer to them in subsequent discussions. Handling all of these would result in a very expensive/complicated implementation. We may be able to ignore some (all?) of the multi-touch issues, since they are unlikely to occur and/or occur only if you keep the dragged item stationary.  

- [x] (1) The '0' or '0x' is created at the location of the item that will be removed from the scale.  When that item disappears, the scale will move - a little or a lot, depending on the weight of the item removed.  And when the scale moves, the '0' or '0x' may end up nowhere near where the item that was removed was relative to the scale. That may be OK.  Try summing x and -x with x=40 to see the worst-case scenario.

- [x] (2) Multi-touch: If 'Reset' scale button is pressed while dragging item has halo, the halo should be removed, since it will no longer overlap with any items on the scale.

- [x] (3) Multi-touch: If 'Organize' button is pressed while a dragging item has a halo, then items on scale may move, and whether the dragging item still gets a halo needs to be refreshed. 

- [x] (4) Multi-touch: While 2 items have a halo, user may start dragging the item that's on the scale. Halo on both items should be removed. (Very difficult to do physically, so unlikely.)

- [x] (5) Multi-touch: If an item "drops down" as a result of removing an item lower on the scale, check to see if that item would sum to zero with a dragging item.

- [x] (6) Multi-touch: If an item is added to the scale such that it overlaps with the dragged item, determine whether the 2 items would sum to zero.

- [x] (7) Multi-touch: Putting an item on the scale may cause the scale to move enough that inverse items no longer overlap. 

- [x] (8) Multi-touch: Drag 2 instances of 'x' on top of '-x' on the scale.  All 3 items should get a halo.  Drop one 'x' on top of the '-x', the other 'x' should lose its halo.  (Very difficult to do physically, so unlikely.)

- [x] (9) Is this feature relevant to the "Solving" screen? If so, what are the requirements there? 

- [x] (10) Questions related to "coupled" feature, see https://github.com/phetsims/equality-explorer/issues/19.

**Comment by pixelzoom** [comment]
Additional requirement in Slack, added to checklist in https://github.com/phetsims/equality-explorer/issues/17#issue-271032750:

> @pixelzoom 
While you’re dragging an item, it displays a drop shadow.  Having both the yellow halo and the drop shadow looks quite odd.  Should the drop shadow disappear when the halo is visible? ExEx has no drop shadow, so there is no similar conflict.
> 
> @amanda-phet 
That makes sense to remove the shadow when the halo is visible. Because the halo should still makes the object look “active”

**Comment by pixelzoom** [comment]
@amanda-phet FYI, the background color of the "Variables" screen (greenish yellow) doesn't work at all with the yellow halos.

**Comment by pixelzoom** [comment]
@amanda-phet FYI, I've changed the Variables screen background color to 'rgb( 175, 246, 204 )', the color used for the first 3 screens in Expression Exchange.  This seems to work well with the yellow halo.  If you want to change it to something else, let me know.

**Comment by pixelzoom** [comment]
@amanda-phet please review [1.0.0-dev.37](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.37/equality-explorer_en.html).  I'd like feedback on the look of the halos, fade animation, etc.  

Caveats:  

This dev version implements all of the requirements in https://github.com/phetsims/equality-explorer/issues/17#issue-271032750, _except_ it uses circular halos for x, -x and '0x'.  Rectangular halos proved problematic to implement, and (imo) using circular halos everywhere looks OK. If you really want rectangular halos, then we need to move forward with https://github.com/phetsims/scenery/issues/707. 

This dev version also does not address the scenarios enumerated in https://github.com/phetsims/equality-explorer/issues/17#issuecomment-341774489.  That list is unlikely to be complete; there are certainly other scenarios that I haven't considered yet.  Supporting all of these scenarios will be an expensive endeavor, and some are not feasible to support with the current architecture.  So we should review these scenarios together, to identify which ones need to be supported.

**Comment by pixelzoom** [comment]
@amanda-phet I should mention that you can use the `?slowMotion` query parameter to slow down all animations, including motion and fades.  Use this if you want to closely examine the look of the halos around '0' and '0x'.

**Comment by amanda-phet** [comment]
I don't love the new shade of green, so let me play around to find another shade. Alternatively, the halo could not be yellow, but I don't have a great idea for that and like the consistency with ExEx. 

Overall I really like the halo, and I think the timing is great. 

I would prefer a square halo for sure, and might want to see what others think before you work for too long on that. 

The halo seems a big large to me (it's definitely larger than the one in ExEx). Did you play around and find that this size looked the best? If so I trust your judgement.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> I don't love the new shade of green, so let me play around to find another shade. 

Hmmm... Since you were the designer on Expression Exchange, I'm curious about why you like that color in Expression Exchange but not in Equality Explorer.   Both sims have a similar "look" and layout, and we're trying to mimic the halos in Expression Exchange.  That said, it's easy to change the color, just let me know what you'd prefer. 

> I would prefer a square halo for sure, and might want to see what others think before you work for too long on that.

I'll hold off on square halos - how do you want to solicit feedback from others?  If we do want square halos, I recommend that PhET invest in phetsims/scenery#707, rather doing yet-another sim-specific one off.

> The halo seems a big large to me (it's definitely larger than the one in ExEx). Did you play around and find that this size looked the best? If so I trust your judgement.

It's actually proportionally _smaller_ then the halo in ExEx. But yes, I played around until I thought it looked decent for all cases (1,-1,x,-x,0,0x).  It currently has a radius that's 0.85 times the width of cells in the scale's grid.  Again, easy to change if you want to try something else.  But I recommend waiting until we decide on square halos.

**Comment by pixelzoom** [comment]
(Reopened, accidentally closed 2 days ago.)

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery/issues/707, we decided not to work on common-code support for shadows/halos until January 2018 at the earliest (after chipper:2.0 work). 

For EqEx, that means that:
(1) we continue to use separate PNG files for shadows
(2) we don't have common-code support for rectangular halos 

@ariel-phet's opinion is that circular halos on all items looks fine.

**Comment by pixelzoom** [comment]
Note to self: Investigate addressing multi-touch issues in https://github.com/phetsims/equality-explorer/issues/17#issuecomment-341774489 by adding `this.changedEmitter = new Emitter()` to Plate.  When the Plate changes in any way (location, number of items on the plate, position of items on the plate,...), then `this.changedEmitter.emit()`.   Make ItemNode register as a listener to `changedEmitter`.  If `changedEmitter` fires while ItemNode is dragging, then run the algorithm to determine whether ItemNode overlaps with an inverse item on the scale.

**Comment by pixelzoom** [comment]
All of the multi-touch scenarios in https://github.com/phetsims/equality-explorer/issues/17#issuecomment-341774489 were addressed by adding `changedEmitter` to Plate, as noted in https://github.com/phetsims/equality-explorer/issues/17#issuecomment-344056965.

I'll need to discuss the remaining items in https://github.com/phetsims/equality-explorer/issues/17#issuecomment-341774489, since I don't know what the desired behavior or requirements are.

**Comment by amanda-phet** [comment]
(1) I'm not sure how to handle this, because in this case the 0x is in a very odd location. The entire action happens so quickly that I'm not sure how serious it is, and I don't have a great idea for how to handle it. Ideally the 0x occurs right on the plate and the plate doesn't move, but that is not possible and doesn't make sense. 
![screen shot 2017-11-22 at 11 22 24 am 2](https://user-images.githubusercontent.com/7852916/33143647-c7a8821e-cf77-11e7-9fe8-68a63ad2d79f.png)

(9) Yes, a user can sum to 0 in the solving screen. This would happen in only a few cases: an x, -x, 1, or -1, is sitting on the plate, and the user drags up an opposite term. A halo appears and the term is replaced with a 0x or 0 in the same manner as the variables screen.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> (9) Yes, a user can sum to 0 in the solving screen. This would happen in only a few cases: an x, -x, 1, or -1, is sitting on the plate, and the user drags up an opposite term. A halo appears and the term is replaced with a 0x or 0 in the same manner as the variables screen.

It is impossible to do this in "the same manner as the Variables screen."  According to the design doc, there are at most 2 terms on the scale (variable and constant).  And the size of those terms (size of the rectangle and circle) does not change, they are always large.   So consider the scenario where I have a big "-x" (or perhaps it's "-1x") on the scale.  Are you saying that when I drag a small "x" from the panel and overlap the big "x" on the scale, the small "x" and big "x" should perform some variation of the "sum to zero" representation?

**Comment by pixelzoom** [comment]
@amanda-phet said:
> (1) I'm not sure how to handle this, because in this case the 0x is in a very odd location. The entire action happens so quickly that I'm not sure how serious it is, and I don't have a great idea for how to handle it. Ideally the 0x occurs right on the plate and the plate doesn't move, but that is not possible and doesn't make sense.

There are 2 options for location of the "sum to zero" animation, both relative to the item that was deleted from the scale:

(a) at the location where the deleted item was _before_ the scale moved
(b)  at the location where the deleted item _would have been after_ the scale moved

Option (a) is what is currently implemented, and option (b) makes no sense to me.

**Comment by amanda-phet** [comment]
Ah, regarding (9), I hadn't thought about the size discrepancy. Let's discuss options for this. I have some ideas. 

For (1) I don't think option (b) is that bad. It seems like the 0 would appear at the same time the plate jumps so there shouldn't be any weirdness. Or maybe both options are just going to be weird in the worst case scenario.

**Comment by pixelzoom** [comment]
Imo, option (b) is nonsensical because the scale will not move until the the item is removed from the scale. And the item is not removed from the scale until it has summed to zero.  So showing the sum-to-zero animation at a location other than where the summing took place is confusing.

**Comment by pixelzoom** [comment]
@amanda-phet and I are going to meet about this issue today, specifically (1) and (9).

**Comment by pixelzoom** [comment]
@amanda-phet and I are going to meet about this issue today, specifically:

- [x] decision for (1)
DECISION: Try option (b), which is to perform the animation in the cell that the deleted item occupied, but in the location of that cell after the scale has moved.

- [x] decision for (9)
DECISION: Small and big items both get a halo, "sum to zero" animation has a "0" or "0x" that is the size of the big item.  Animation should occur in location subject to decision in (1).  If a -1 falls from above onto a big 1 on the scale, also need to do the "sum to zero" animation, possibly without the halo. (Ditto for x and -x.)

- [x] confirm behavior for (2-8)

- [x] whether 'x' and '-x' can live with a circular halo
DECISION: We can live with circular halo.

**Comment by pixelzoom** [comment]
Related to (1), in https://github.com/phetsims/equality-explorer/issues/17#issuecomment-347287201 I described the 2 options for where to show the "sum to zero" animation:

> (a) at the location where the deleted item was _before_ the scale moved
(b) at the location where the deleted item _would have been after_ the scale moved

Option (a) was implemented in [1.0.0-dev.41](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.42/equality-explorer_en.html) and previous versions.

Options (b) is now implemented in [1.0.0-dev.42](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.42/equality-explorer_en.html).

@amanda-phet please review and let me know which you'd prefer. (Be sure to try Variables screen with large value for x.)

**Comment by amanda-phet** [comment]
I like option (b) very much!!! Thanks for making that change.

**Comment by pixelzoom** [comment]
Re:

> - [ ] x, -x and '0x' have a rectangular yellow halo

We decided to stick with circular halos throughout, since they look fine, and since we won't have common-code support for awhile (see phetsims/scenery#707).

**Comment by pixelzoom** [comment]
I think we've enumerated all of the requirements for this feature, and it's implemented in all screens except Solving.  I'm going to go ahead and close this issue, since I understand the requirements for the Solving screen.
