### ISSUE TITLE
Changes to QA credits for version 1.1

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#172]
@KatieWoe any changes QA credits for the upcoming 1.1 release?  So far, that would be anyone who worked on https://github.com/phetsims/qa/issues/732.

Current credits are:

<img width="591" alt="screenshot_1410" src="https://user-images.githubusercontent.com/3046552/140810620-4141d0a5-086e-481c-bda1-8390987166fe.png">

**Comment by pixelzoom** [comment]
Current credits are:

<img width="591" alt="screenshot_1410" src="https://user-images.githubusercontent.com/3046552/140810620-4141d0a5-086e-481c-bda1-8390987166fe.png">

**Comment by KatieWoe** [comment]
Nancy Salpepi should be added.

**Comment by pixelzoom** [comment]
Based on issues like #180, it looks like I need to add Emily Miller to QA credits. 

_EDIT: done._

**Comment by KatieWoe** [comment]
No new additions for rc.2

**Comment by pixelzoom** [comment]
Ready to publish 1.1, so closing this issue.
