### ISSUE TITLE
Pressing open/close button on accordion panel adjusts panel in all game levels

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/equality-explorer#175]
**Test device**
MacBook Air (m1 chip)

**Operating System**
12.0.1

**Browser**
Chrome

**Problem description**
https://github.com/phetsims/qa/issues/735

On the Solve It! Screen, if I open (or close) the Snapshots accordion panel on one level, if will be opened (closed) for all levels. Is that correct behavior or should they be independent of one another? 

**Steps to reproduce**
1. Pick any level on the Solve It! screen
2. Open the Snapshots accordion panel
3. Pick another level- the panel will be open

**Visuals**
![snapshots](https://user-images.githubusercontent.com/87318828/141472284-7026ca3b-a672-4bca-b0c8-bbdb8cc87a02.gif)

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Equality Explorer‬
URL: https://phet-dev.colorado.edu/html/equality-explorer/1.1.0-rc.1/phet/equality-explorer_all_phet.html?showAnswers&gameLevels=1,2
Version: 1.1.0-rc.1 2021-11-09 18:21:34 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
Language: en-US
Window: 1314x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Each game level used to have its own state for the accordion box. But a single global state for all levels was requested by @kathy-phet in https://github.com/phetsims/equality-explorer/issues/124.    It's also documented in the code:

```js
    // @private state of the Snapshots accordion box is global to the Screen,
    // see https://github.com/phetsims/equality-explorer/issues/124
    this.snapshotsAccordionBoxExpandedProperty =
      new BooleanProperty( EqualityExplorerConstants.SNAPSHOTS_ACCORDION_BOX_EXPANDED );
```

I recommend no change, and closing this issue as "won't fix".  @amanda-phet please review this issue, discuss with @kathy-phet if necessary.  If you are still OK with the current behavior, close as "won't fix".  Otherwise specify what you'd like to change.

**Comment by amanda-phet** [comment]
Thanks for finding that historical issue @pixelzoom ! I remembered it being an intentional decision to keep the state of the accordion boxes. We should leave this as-is.
