### ISSUE TITLE
UI sounds were enabled unintentionally.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#177]
For https://github.com/phetsims/qa/issues/735.

While testing this sim for the 1.1 release, I suddenly realized that UI sounds have been enabled.  We didn't do this intentionally, and this sim has never had a sound design, or even a discussion about sound.

@jbphet enabled all UI sounds when he switched to tambo-based for `GameAudioPlayer`, common code (in vegas) which plays sounds related to the game.  For Equality Explorer, this was first done in the main.js (https://github.com/phetsims/equality-explorer/commit/22f9aad82cb10e25d267848596403e4ae824b520), then moved to package.json (https://github.com/phetsims/equality-explorer/commit/8bf530bd63cc68500ec0f37d7ff44e001a5359cd).   And according to https://github.com/phetsims/vegas/issues/77 and https://github.com/phetsims/chipper/issues/806, this was done for ALL sims that use `GameAudioPlayer`. 

@amanda-phet  @kathy-phet 
* Did we really want to enable all UI sounds for this sim, before having the opportnity to discuss or (possibly) add UI sounds to fill in the gaps?  It doesn't feel like a very good "sound experience" to me.
* Is this a problem for all sims that have a Game? I've asked this more generally in https://github.com/phetsims/vegas/issues/77#issuecomment-968085715.

**Comment by pixelzoom** [comment]
My recommendation for addressing this in Equality Explorer 1.1 is described in https://github.com/phetsims/vegas/issues/77#issuecomment-969214191.

**Comment by pixelzoom** [comment]
11/18/21 design meeting:

The workaround in https://github.com/phetsims/vegas/issues/77#issuecomment-969214191 was approved.  I'll need to:
- [x] turn off 'ui-sounds' category
- [x] cherry-picking fixes from https://github.com/phetsims/vegas/issues/98

**Comment by pixelzoom** [comment]
Fixes for phetsims/vegas#98 were cherry-picked in https://github.com/phetsims/vegas/commit/e2629f81b185932a4404c74952724241f60611ab and https://github.com/phetsims/scenery-phet/commit/8a4f7f6b1d3592327f9ed1d22c32ac15ccdaeb5e.

**Comment by pixelzoom** [comment]
Work is done in master and 1.1 branches.

@KatieWoe would you please assign someone from QA to test this? 

If this looks OK, change the label to "fixed-awaiting-deploy". 

To test:

1. Run the sim from master with `?showAnswers&reward=2`
2. Verify that there is no sound for the UI controls. (You don't need to test every one of them, just a random sample.) 
3. In the Game screen, verify that there is no sound for the level-selection buttons, and the back button on the scoreboard.
4. Go to any one of the levels in the Game. (Testing one level is fine, no need to test them all.)
5. Press the red "show answer" button. You should hear the "ding" sound when the smiley face becomes visible.
6. Press the red "show answer" button again. You should hear the "cheering" sound when the reward becomes visible.
7. Turn off sound in the navigation bar.
8. Repeat steps 4,5,6 for a different level. You should hear no sound after pushing the "show answer" button.

**Comment by KatieWoe** [comment]
Looks good on master

**Comment by pixelzoom** [comment]
To verify in 1.1.0-rc.2, follow the steps in https://github.com/phetsims/equality-explorer/issues/177#issuecomment-973289661.

**Comment by KatieWoe** [comment]
Looks good in RC.2
