### ISSUE TITLE
Game level 3 is a 1-step equation when a=1.

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/equality-explorer#178]
For phetsims/qa#735.

Level 3 of the Solve It! game is Two-Step Equations. When 'a' has a value of 1, it is a one-step equation.
![Screen Shot 2021-11-16 at 10 42 21 AM](https://user-images.githubusercontent.com/87318828/142018648-6aeaeec7-5f5d-4452-a0b5-a4abd8f750ab.png)

**Comment by pixelzoom** [comment]
Level 3 is indeed supposed to be two-step equations.  From the info dialog:

<img width="809" alt="screenshot_1440" src="https://user-images.githubusercontent.com/3046552/142025894-2ac13b52-0f7c-4d69-afe0-e97a7d2ad90b.png">


From the [design doc](https://docs.google.com/document/d/1vG5U9HhcqVGMvmGGXry28PLqlNWj25lStDP2vSWgUOo/edit#heading=h.vjeb381yleoi):

> **Level 3**
> Challenges in the form ax+b=c
> 
> Let x be a random integer between [-40,40], x ≠ 0 
> Let a be a random integer between [-10,10], a ≠ 0
> Let b be a random integer between [-10,10], b ≠ 0
> Let c = ax+b **note: it is possible that c = 0 and that is acceptable**

It would be trivial to also exclude a = 1.

And is there a similar problem in Levels 4 & 5? Those levels are supposed to be "multi-step equations".

**Comment by pixelzoom** [comment]
Do we have a similar problem in Levels 4 & 5?  Those levels are supposed to be "multi-step equations".

**Comment by amanda-phet** [comment]
We should definitely exclude a=1, good catch! I excluded b=0 for the same reason. 

Thanks for quickly looking at that @pixelzoom . I'd like to make that change.

**Comment by amanda-phet** [comment]
I just added the suggestion to the design doc, and confirmed that level 4 and 5 shouldn't need any changes.

**Comment by pixelzoom** [comment]
I also confirmed with @amanda-phet that a = -1 is OK.

Changed in the above commits, in master and 1.0 branches.  a=1 is now excluded from Level 3.

@Nancy-Salpepi please verify in master, and change label to "fixed-awaiting-deploy" if it looks OK.

You could verify this by running with `?showAnswers`, going to Level 3, and repeatedly pushing the "show answer" and "Next" buttons. But it will take a long time to generate enough challenges to be convinced that you'll never see a=1. 

There's an easier way to generate a large number of challenges quickly. Run with `?showAnswers`, go to the level-selection UI, and press the red "test challenge generators" button.   This will generate 1000 challenges (numbered 0-999) for each level, printing each challenge to the browser console, for example:

```
>>> Testing level 1
0: 7 x + 0 = 0 x + -56 (x=-8)
1: 1 x + 1 = 0 x + -12 (x=-13)
...
>>> Testing level 2
0: -1 x + 0 = 0 x + 39 (x=-39)
1: 1/-7 x + 0 = 0 x + -1 (x=7)
...
>>> Testing level 3
0: 2 x + 10 = 0 x + -42 (x=-26)
1: 8 x + -5 = 0 x + 163 (x=21)
...
>>> Testing level 4
0: 3/2 x + -5/2 = 0 x + -83/2 (x=-26)
1: -4/5 x + -3/5 = 0 x + 1 (x=-2)
...
>>> Testing level 5
0: -2 x + 6 = -9 x + 237 (x=33)
1: -6 x + -3 = -2 x + 5 (x=-2)
...
>>> Tests passed for all levels
```

The format of each line is:

`{{challengeNumber}}: '{{a}} x + {{b}} = {{m}} x + {{n}} (x={{x}})'`

... where `m` is always `0` for Level 3.

You'll need to inspect the challenges that were generated for Level 3. Go to the browser console, search for "Testing level 3".  Inspect the value of 'a' (the coefficient of x on the left side of the equation) for each challenge.  Press the "test challenge generators" button multiple times if you wish.  You should never see `1 x` on the left side of the equation.

**Comment by Nancy-Salpepi** [comment]
Thanks for the shortcut method @pixelzoom. All looks good in master.

**Comment by KatieWoe** [comment]
I saw this as well on Firefox Win 11. I tried 50+ levels with `?showAnswers` on Chrome and wasn't able to reproduce it, so it may be a bit rare.

**Comment by pixelzoom** [comment]
The range of `a` was [-10,10], integers, with zero excluded.  Values are selected random, so (over a large number of samples) there was a 1 in 20 chance that you'd see a=1.

**Comment by pixelzoom** [comment]
To verify in 1.1.0-rc.2, follow the instructions in https://github.com/phetsims/equality-explorer/issues/178#issuecomment-970638240.

**Comment by KatieWoe** [comment]
The `test challenge generators` doesn't seem to show up in RC.2. So I hit the yellow refresh equation button several times and did not see a=1 come up. @pixelzoom is this enough? If so, I think it is safe to close

**Comment by pixelzoom** [comment]
> The `test challenge generators` doesn't seem to show up in RC.2.

Ah, right. I forgot that `?showAnswers` cannot be enabled in built versions. 

> So I hit the yellow refresh equation button several times and did not see a=1 come up. @pixelzoom is this enough? If so, I think it is safe to close

Yes, that's sufficient.  Closing.
