### ISSUE TITLE
usability of dragging with touch

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#18]
Similar to https://github.com/phetsims/expression-exchange/issues/133 ... When dragging an item on touch devices, your finger covers the item.  It's difficult to see the item, difficult to see the "halos" when inverse items overlap,...   (And I have relatively slim finger tips :)

There is nothing about this in the design document. I recommend that at least the top 2/3 of the item should remain visible above the pointer (finger).

@amanda-phet @ariel-phet your thoughts?

**Comment by pixelzoom** [comment]
This came up while investigating the multi-touch issues enumerated in https://github.com/phetsims/equality-explorer/issues/17#issuecomment-341774489.  I'm finding it difficult to use this sim on iPad.

**Comment by ariel-phet** [comment]
@pixelzoom we have certainly used this strategy in other sims like charges and fields, and I am fine with using it again. I say go ahead and implement your proposed strategy.

**Comment by pixelzoom** [comment]
With mouse, the item continues to move slightly up and left at the start of a drag (no change from previous versions).  

```js
// ItemDragHandler
38 mouseOffset: new Dimension2( -4, -4 ),
```

With touch, the item now moves straight up by 70% of its height at the start of a drag:

```js
// ItemDragHandler
41 touchOffset: new Dimension2( 0, -0.7 * itemNode.height )
```

This feels good with my specific finger, your mileage may vary.  Easy to change by tweaking values in the above code.  

This change is present starting with [1.0.0-dev.38](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.38/equality-explorer_en.html). @amanda-phet let me know if you'd like this changed.

**Comment by pixelzoom** [comment]
As I continued to work on #17, I really wasn't happy with what I did in [1.0.0-dev.38](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.38/equality-explorer_en.html).  So I rewrote the bit of code that handles positioning the item relative to the pointer (for both mouse and touch).  See [1.0.0-dev.39](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.39/equality-explorer_en.html).  Feels pretty good to me now, and the "sum to zero" effect is much clearer.

**Comment by pixelzoom** [comment]
@amanda-phet this is still awaiting your review.

**Comment by pixelzoom** [comment]
Reviewed with @amanda-phet, looks good, closing.
