### ISSUE TITLE
Support for UI sounds

### ISSUE THREAD

**Issue by markgammon** [phetsims/equality-explorer#181]
As part of the work done for https://github.com/phetsims/vegas/issues/77, UI sounds got turned on for this simulation.  Before the sim is published again from master, we should decide whether to turn the UI sounds off, leave them on and design and implement sounds for the rest of the interactions, or publish with a partial sound design.

If the decision is to turn them off, this can be accomplished by adding the following line to the end of the sim's `-main.js` file:

```js
  soundManager.setOutputLevelForCategory( 'user-interface', 0 );
```

**Comment by pixelzoom** [comment]
UI sounds were turned off for the 1.1 release in https://github.com/phetsims/equality-explorer/issues/177.  So I'm going to retitle this issue accordingly, and adjust its status.

**Comment by pixelzoom** [comment]
@kathy-phet asked me to evaluate the technical lift of adding UI sound to this sim.  @amanda-phet FYI.

There are very few common-code UI components in this sim, only a handful of buttons on each screen.  Most of the interaction involves moving items between the toolboxes and the scale.  So simply turning on UI sounds is not going to provide a good/useful sound experience.  

So there will be a lot of sim-specific sound implementation required. And the first thing that needs to happen is a significant design task.  Identify where to use sound, how much sound design to bite off, etc.  Then descide whether to move forward, based on whether adding sim-specific sound will result in a meaningful sound experience for the user.  

There are some big questions here, including:

* Is there sound when you take something out of a toolbox?
* Is there sound when you put something back into a toolbox?
* Is there sound when you take an item off the scale?
* Is there sound when you put an iten on the scale?
* Is there sound while you're dragging an item?
* Is there sound when you release something and it animates to the scale or toolbox?
* Is there a sound when the lock is on and dragging is accompanied by an item from the opposite side of the scale?
* Is there a sound when items combine to form a new item? (e.g. dragging 'x' onto 'x' produces '2x') 
* Is there a sound when items combine and cancel each other out? (e.g. dragging "1" onto "-1")
* Do different kinds of items have different associated sounds?
* How does sound work with the highly-multitouch nature of this sim? Are there sounds playing at the same time, one at a time, interrupted,...?
* In the Operations screen, is there a sound associated with the operation dropping downward toward the plates? a sound when it reaches the plate and causes what's on the plates to change?

**Comment by amanda-phet** [comment]
After a discussion with Ashton many months ago, my understanding is that sound design is a big chunk of work for everyone involved as there is a lot of thought that goes into it (similar to your questions you've listed) as well as lots of iterating on the design. So it's a lengthy process that takes time. Is this a Q2 goal? I have other sims where sound design has come into question and I think I need some clarification from Kathy about the priority of sound design for this sim, as well as others.

**Comment by pixelzoom** [comment]
My understanding is that @kathy-phet wants to have a discussion about this, sometime towards the beginning of Q2 2022.  So assigning to @kathy-phet and @amanda-phet.

**Comment by pixelzoom** [comment]
According to @kathy-phet in Slack, "we are going to postpone that work on EE for now".  So unassigning myself, and labeling as deferred.

**Comment by pixelzoom** [comment]
Support for default UI sounds in common code has come a long way since we last worked on this issue.  In the couple of places where this sim was missing UI sounds, I was able to quickly add them in the above commits, and I used the same defaults as common code.

Sounds is now enabled for the entire suite, and I recommend that we publish 1.2 (see https://github.com/phetsims/equality-explorer/issues/208) with default UI sounds.  @amanda-phet @kathy-phet Do you have any objections?

If no objections... @amanda-phet feel free to test-drive if you have time.  If you don't have time, I think it's fine to vet this during dev testing, since QA is well-versed in default UI sounds.

**Comment by kathy-phet** [comment]
No objections to publishing with UI sound. Thanks!

**Comment by pixelzoom** [comment]
Ready for dev testing in https://github.com/phetsims/qa/issues/1172, https://github.com/phetsims/qa/issues/1173, and https://github.com/phetsims/qa/issues/1174.

**Comment by amanda-phet** [comment]
I tried every action and heard a sound, so that's good!

**Comment by KatieWoe** [comment]
Sound seemed ok in dev test

**Comment by pixelzoom** [comment]
Great. This issue can be closed.
