### ISSUE TITLE
Levels that are not included in ?gameLevels should not be shown in game Info dialog.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#184]
Related to  https://github.com/phetsims/vegas/issues/104

**Comment by pixelzoom** [comment]
On hold until general design decisions have been made, see https://github.com/phetsims/vegas/issues/104#issuecomment-1102871139.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/vegas/issues/104#issuecomment-1119190311, @amanda-phet said:
> That sounds great to do this for EqEx.

**Comment by pixelzoom** [comment]
@amanda-phet please review in master. For example, test with `?gameLevels=1,3,5` and verify that the correct level-selection buttons and level descriptions (in the Info dialog) are shown.

**Comment by pixelzoom** [comment]
In Slack, @amanda-phet asked:
> Are you moving forward with the option that only shows the relevant levels and hides the others? Or the option that shows all levels, but “grays out” (text is gray, not black) the levels that aren’t options on the level selection screen?

Only show info for relevant levels, similar to how level-selection buttons are treated.

**Comment by amanda-phet** [comment]
Looks great to me!
