### ISSUE TITLE
Add support for dynamic locale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#187]
Requested by @kathy-phet. Includes equality-explorer-basics and equality-explorer-two-variables.

**Comment by pixelzoom** [comment]
The bulk of this work is done. But...  

There are 2 remaining TODOs, labeled with:

```
//TODO https://github.com/phetsims/equality-explorer/issues/187 must be disposed because it links to a translated string Property
```

These TODOs involve cases where a variable symbol ('x', 'y') appears in an equation. Those variable symbols are translated strings -- `xStringProperty` and `yStringProperty, to be specific. Equations are created dynamically, and therefore must be disposed in order to unlink from those StringProperties.  The problem is that we have no reference to the Nodes, they are buried deep in a scenegraph fragment, so cannot call dispose.

So this sim now has a significant memory leak.

**Comment by pixelzoom** [comment]
I addressed the easier of the two memory leaks in the commit above.

**Comment by pixelzoom** [comment]
The more difficult memory leak was addressed in the above commit, by factoring out class ExpressionNode, with its own `dispose` method.

**Comment by pixelzoom** [comment]
Support for dynamic locale is complete.  This sim was relatively easy (4.25 hours) because it does not have many strings.

@amanda-phet ready for review.

**Comment by pixelzoom** [comment]
@amanda-phet This issue is now active again, since we're republishing version 1.2 of the suite - see https://github.com/phetsims/equality-explorer/issues/208.   If you don't have time to review dynamic locale, I'm comfortable with having QA do so in dev testing. Let me know...

**Comment by pixelzoom** [comment]
Ready for dev testing in https://github.com/phetsims/qa/issues/1172, https://github.com/phetsims/qa/issues/1173, and https://github.com/phetsims/qa/issues/1174.

Note that https://github.com/phetsims/equality-explorer/issues/211 is a known issue, and does not need to be reported. I intend to fix it before RC testing, and will ask QA to verify separately.

**Comment by amanda-phet** [comment]
I'm happy to defer to QA to make sure dynamic locale is working well.

**Comment by KatieWoe** [comment]
Things were looking pretty good in the dev test.

**Comment by pixelzoom** [comment]
Great. This issue can be closed.
