### ISSUE TITLE
credits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#2]
Finalize credits in [equality-explorer-main.js](https://github.com/phetsims/equality-explorer/blob/master/js/equality-explorer-main.js).

I've started with the credits that are shown at the top of the Google design doc.

When RC testing is completed, any credit updates should be done in both the 1.0 and master branches.

**Comment by amanda-phet** [comment]
Please add Cheryl McCutchan to graphic arts.

**Comment by pixelzoom** [comment]
I inadvertently discovered that Mariah Hermsmeyer created the coins, which came from expression-exchange.  I'll add her to main.js credits and fix images/license.json.

@jbphet FYI, you don't have any credits in expression-exchange/images/license.json, which resulted in incorrect credits in equality-explorer.

**Comment by amanda-phet** [comment]
Let's be sure to add Diana to the design team credits.

**Comment by pixelzoom** [comment]
Slack conversation: 

Diana would like to be credited as "Diana Berenice López Tavares".

**Comment by pixelzoom** [comment]
Credits have been moved to `EqualityExplorerConstants.CREDITS` and (per @amanda-phet) will be shared by 3 sims:  _Equality Explorer_, _Equality Explorer: Basics_ and _Equality Explorer: Two Variables_.

**Comment by pixelzoom** [comment]
@lmulhall-phet We're getting close to starting RC testing.  Who should I add to the QA credits?

Currently:
`qualityAssurance: 'Steele Dalton, Liam Mulhall, Jacob Romero',`

**Comment by pixelzoom** [comment]
Current QA credits are:

`qualityAssurance: 'Steele Dalton, Liam Mulhall, Jacob Romero',`

**Comment by ghost** [comment]
@pixelzoom, we need to add @andrealin, as she found #134. (Unless she doesn't want to be in there twice.)

**Comment by pixelzoom** [comment]
I'll add @andrealin to QA. She is not currently in the credits, so adding her to QA will not cause her to "be in there twice".  If she was already part of the "team" group (the core design team), then we would not add her a second time.

**Comment by pixelzoom** [comment]
@amanda-phet RC testing will start in the next couple of days. Below are the current credits.  Please specific changes, or sign off.  

![screenshot_694](https://user-images.githubusercontent.com/3046552/42600291-07f80ac6-851f-11e8-8c63-837dae8b5888.png)

**Comment by amanda-phet** [comment]
I don't think there are any more changes to make! Thanks!

**Comment by pixelzoom** [comment]
I've added @KatieWoe to credits, since @lmulhall-phet says that she'll be involved in RC testing.  Final credits are shown below.    Closing.

![screenshot_695](https://user-images.githubusercontent.com/3046552/42647479-5d0de024-85c1-11e8-9600-d69447c7b188.png)

**Comment by pixelzoom** [comment]
@lmulhall-phet In the [EqEx test matrix](https://docs.google.com/spreadsheets/d/1-wXbbXEuK1M8-8zOoBZJjgGkWohWb57q3fwOtFFNeMI/edit#gid=2), I see EJ and ML.  Those initials don't match anyone in the QA credits.  Do we need to add someone?

**Comment by amanda-phet** [comment]
Ethan Johnson and Megan Lai.

**Comment by pixelzoom** [comment]
Revised credits:

![screenshot_701](https://user-images.githubusercontent.com/3046552/42833650-e9646e28-89b1-11e8-9a53-9d0248b2aa7e.png)
