### ISSUE TITLE
update the design document?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#20]
The design document is lagging behind. New information hasn't been added, questions/comments have gone unresolved for months, it doesn't reflect some of the decisions made, mockups are out of date, there's a general lack of scenarios, no info on multi-touch, ...   Consequently I'm finding it to be less and less useful.   

Options are to bring the document up to date, or (as we've done with some other sims) clearly mark it as "stale" and continue to specify things in GitHub issues (as we've done for #4, #17, #19,...)

**Comment by pixelzoom** [comment]
@amanda-phet have you and @ariel-phet discussed this?

**Comment by amanda-phet** [comment]
Yes, on 11/28/17 I brought this up in slack and we determined that design docs are intended to be a sketch of the sim intent, but once development starts the github discussions include the most up-to-date decisions. We will link to github issues when they are discussed, especially in meeting notes, and try to include a table of github issues for future reference. 

I think it is fair to say that the design doc is an accurate reflection the learning goals, original design decisions, and pedagogical considerations, but will not necessarily reflect the current state of a sim once it begins development and changes are made to the design.

**Comment by pixelzoom** [comment]
If there's nothing else to do here, feel free to close.

**Comment by amanda-phet** [comment]
We meant to bring it up at status so at some future status (or developer) meeting it would be good to make sure everyone on the team is on the same page.
