### ISSUE TITLE
Credits for 1.2 release.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#209]
All 3 sims in this suite share the same credits, see EqualityExplorerConstants.CREDITS.

Credits are currently:

<img width="670" alt="screenshot_3599" src="https://github.com/user-attachments/assets/b8b5994e-c74a-41ed-aa12-b588b9701df0">

**Comment by pixelzoom** [comment]
Please specify QA credits for https://github.com/phetsims/qa/issues/1172, https://github.com/phetsims/qa/issues/1173, and https://github.com/phetsims/qa/issues/1174.

**Comment by KatieWoe** [comment]
Matthew Moore can be added

**Comment by pixelzoom** [comment]
Please specify QA credits for https://github.com/phetsims/qa/issues/1175, https://github.com/phetsims/qa/issues/1176, and https://github.com/phetsims/qa/issues/1177.

**Comment by Nancy-Salpepi** [comment]
Please add Ashton Morris.

**Comment by pixelzoom** [comment]
In the commits above, Ashton Morris was added to QA credits in main and 1.2 branches of all sims in the suite.

**Comment by pixelzoom** [comment]
Please specify QA credits for https://github.com/phetsims/qa/issues/1180, https://github.com/phetsims/qa/issues/1181, and https://github.com/phetsims/qa/issues/1182.

**Comment by Nancy-Salpepi** [comment]
No one else to add! Closing
