### ISSUE TITLE
screen background colors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#21]
Finalize screen background colors. 

Variables screen is the only one that's truly problematic -- the yellow halos for "sum to zero" animation don't look very good on the greenish-yellow background.  I tried the background color from Expression Exchange ( `rgb( 175, 246, 204 )`, see [1.0.0-dev.40](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.40/equality-explorer_en.html)), but @amanda-phet thought it was too dark and conflicted with the scale's green arrow (`rgb( 0, 200, 0 )`).

Screen colors as of [1.0.0-dev.42](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.42/equality-explorer_en.html) are:

screen | color
:--- | :---
Basics | `rgb( 255, 250, 227 )`
Numbers | `rgb( 214, 233, 254 )`
Variables | `rgb( 239, 253, 218 )`
Solving | `rgb( 237, 225, 253 )`

**Comment by pixelzoom** [comment]
Starting with [1.0.0-dev.51](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.51/equality-explorer_en.html), I've swapped the background colors for the Numbers and Variables screens because:

(1) Mockups in the design document use 2 different colors for the Numbers screen, but a single consistent color (`'rgb( 214, 233, 254 )'`) for Variables.

(2) I'm working mostly in the Variables screen, and I really can't stand looking at the greenish-yellow background color any more.  So moving it to the Numbers screen allows me to (mostly) ignore it.

So the background colors are now:

screen | color
:--- | :---
Basics | `rgb( 255, 250, 227 )`
Numbers | `rgb( 239, 253, 218 )`
Variables | `rgb( 214, 233, 254 )`
Solving | `rgb( 237, 225, 253 )`

**Comment by pixelzoom** [comment]
We'll also need a color for the "Mystery" screen, added in #34.  I'm using white for now.

**Comment by pixelzoom** [comment]
As of [1.0.0-dev.62](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.62/phet/equality-explorer_en_phet.html), I'm using `rgb( 248, 227, 226 )` for the "Solve It!" screen background color, as shown in mockups is #34.

Summary:

screen | color
:--- | :---
Basics | `rgb( 255, 250, 227 )`
Numbers | `rgb( 239, 253, 218 )`
Variables | `rgb( 214, 233, 254 )`
Solving | `rgb( 237, 225, 253 )`
Solve It! | `rgb( 248, 227, 226 )`

**Comment by pixelzoom** [comment]
With the exception of the "lock" feature, the first 4 screens are feature complete.  So it's not impossible that we'll meet the "March 26 interviews" milestone.  And if we're going to do interviews, perhaps it's time to solidify the background colors.

**Comment by amanda-phet** [comment]
I'd like to see how Solve It! looks once we have more of the features implemented, so that color might change. We don't have many more colors left to choose from so it will likely still be a shade of "pink." 

I would still like to switch the Numbers and Variables colors back because the different backgrounds will offer better contrast to the new elements (the 1s on Numbers contrast better with blue, and the x's on Variables contrast better with green). Happy to tweak the actual hues or shades if people want, though.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> I would still like to switch the Numbers and Variables colors back ...

Do you mean _swap_ colors for these 2 screens?  Your reason for swapping discusses the merits based on the term colors.  But are you considering the halo color? As I've mentioned previously, the greenish-yellow background color is (imo) not harmonious with the yellow halos.

In https://github.com/phetsims/equality-explorer/issues/21#issue-279461614:
> Variables screen is the only one that's truly problematic -- the yellow halos for "sum to zero" animation don't look very good on the greenish-yellow background.

In https://github.com/phetsims/equality-explorer/issues/21#issuecomment-352882787:
> I'm working mostly in the Variables screen, and I really can't stand looking at the greenish-yellow background color any more. So moving it to the Numbers screen allows me to (mostly) ignore it.

But if this doesn't bother anyone else, I'll live with it.

**Comment by amanda-phet** [comment]
>Do you mean swap colors for these 2 screens? 

Yes, swap. 

>Your reason for swapping discusses the merits based on the term colors. But are you considering the halo color? As I've mentioned previously, the greenish-yellow background color is (imo) not harmonious with the yellow halos.

The halo is on both screens, so the yellow halo will be over a green background anyway unless we re-work all screen colors. 

I din't mind the greenish-yellow background as much as you, I guess! Unfortunately with so many screens we really need 4 contrasting colors because otherwise they can look too similar. But the game screen doesn't necessarily need to be a 5th color, so I can go back to the drawing board.

**Comment by pixelzoom** [comment]
I've swapped colors for Numbers and Variables screens. The change will appear in dev versions >= 1.0.0-dev.70 (not published yet).

**Comment by pixelzoom** [comment]
With the exception of the lock feature, all 5 screens are now feature complete.  So there is no impediment to making final decisions about screen background colors. 

@amanda-phet Do you have an change requests? And if not, please close this issue.

**Comment by pixelzoom** [comment]
4/26/18 design meeting:

Current colors are working well.  No changes to make. Closing.
