### ISSUE TITLE
Revise screenshots for 1.2 release.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#210]
For #208.

The "look" of some common-code features (like the navigation bar) has changed since these sims were last published 6+ years ago.  So the screenshots should be updated for this release.

**Comment by Nancy-Salpepi** [comment]
I can do these if you would like @amanda-phet?

**Comment by amanda-phet** [comment]
Thanks Nancy, that would be great!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Nancy-Salpepi** [comment]
@KatieWoe would you mind making the commits for me?
https://o365coloradoedu-my.sharepoint.com/:f:/g/personal/nasa9473_colorado_edu/Eokbcz37JfxDuA-4fnciQNoB28Af01XX4yvFLuMIHzOU5g?e=0zaWVX

**Comment by KatieWoe** [comment]
Committed new screenshots

**Comment by pixelzoom** [comment]
@amanda-phet Do you want to review, or can we close this issue?

**Comment by amanda-phet** [comment]
These look good to me. Thank you!
