### ISSUE TITLE
Dynamic layout problem with left-hand side of equations.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#211]
Related to https://github.com/phetsims/equality-explorer/issues/187 ...

There's a dynamic layout problem with the equations (EquationNode) in the Solve It! screen, reproducible with `?stringTest=dynamic`. For example:

<img width="1047" alt="screenshot_3603" src="https://github.com/user-attachments/assets/b2aa1d76-93e6-464c-aeed-5f72cfb64673">

I expected that this patch below would resolve the problem...

```diff
Subject: [PATCH] fix comment, https://github.com/phetsims/scenery-phet/issues/888
---
Index: js/common/view/EquationNode.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/EquationNode.ts b/js/common/view/EquationNode.ts
--- a/js/common/view/EquationNode.ts	(revision 41d0cb271ff21da403c438466eb14feeb1403f21)
+++ b/js/common/view/EquationNode.ts	(date 1732060518047)
@@ -163,7 +163,8 @@
     this.leftExpressionNode = new ExpressionNode( this.leftTermCreators, this.expressionNodeOptions );
     this.rightExpressionNode = new ExpressionNode( this.rightTermCreators, this.expressionNodeOptions );
     this.children = [ this.leftExpressionNode, this.relationalOperatorText, this.rightExpressionNode ];
-    this.updateLayout();
+    Multilink.multilink( [ this.leftExpressionNode.localBoundsProperty, this.rightExpressionNode.localBoundsProperty ],
+      () => this.updateLayout() );
   }
 
   /**
```

... but it results in a new layout problem:

<img width="1023" alt="screenshot_3601" src="https://github.com/user-attachments/assets/dd9e6934-f123-4b43-af90-16309783a96c">

**Comment by pixelzoom** [comment]
This is a problem anywhere that a dynamic string appears on the left-hand side of the equation. For example, in the Variables screen:

<img width="1139" alt="screenshot_3604" src="https://github.com/user-attachments/assets/b8d51bea-8d79-4f86-b285-a9459078bb98">

**Comment by pixelzoom** [comment]
@Nancy-Salpepi would you mind verifying this in main?  It needs to be tested in equality-explorer and equality-explorer-two-variables with `?stringTest=dynamic`.   If it looks OK, please close this issue.

**Comment by Nancy-Salpepi** [comment]
Both sims look great to me!
Closing.
