### ISSUE TITLE
The "x" variable on the Solve It! screen is no longer italicized 

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/equality-explorer#216]
**Test device**
MacBook Air M1 chip

**Operating System**
15.0.1

**Browser**
Safari 18.0.1

**Problem description**
For https://github.com/phetsims/qa/issues/1172, on the Solve It! screen the "x" no longer looks like a variable in the 'Solve for X' text. 

**Visuals**
Published:
<img width="510" alt="Screenshot 2024-11-18 at 3 32 11 PM" src="https://github.com/user-attachments/assets/2c2f1da6-f596-45ff-89bf-aaee3bb5835a">

dev version:
<img width="510" alt="Screenshot 2024-11-18 at 3 32 18 PM" src="https://github.com/user-attachments/assets/e1b6e5cf-ee78-448a-94dd-bb90cfa479d7">

**Comment by Nancy-Salpepi** [comment]
This is also seen in an level.
Published:
<img width="510" alt="Screenshot 2024-11-18 at 3 32 11 PM" src="https://github.com/user-attachments/assets/986fdcd2-ed88-47e1-9f47-a7cd1f563dcf">

Dev version:
<img width="510" alt="Screenshot 2024-11-18 at 3 32 18 PM" src="https://github.com/user-attachments/assets/9b82a589-8036-4448-b496-036395a6e193">

**Comment by pixelzoom** [comment]
This regression was introduced during conversion to TypeScript, and is fixed in the above commit.   @Nancy-Salpepi please verify in main, close if OK.

**Comment by Nancy-Salpepi** [comment]
Looks good. Closing!
