### ISSUE TITLE
Changes to lock-scenarios.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#219]
For https://github.com/phetsims/qa/issues/1172 ...

@Nancy-Salpepi identified some fixes and improvements for [lock-scenarios.md](https://github.com/phetsims/equality-explorer/blob/main/doc/lock-scenarios.md).

- [x] Scenario 4: delete “and above any other terms on the plate”
- [x] Scenario 6:  change “Term the lock on” to “Turn the lock on”
- [x] Scenario 14, step 4: Change “is created on the plate” to “is created on the right plate”
- [x] Scenario 14, step 6 is confusing
- [x] Scenario 23: needs 2 more steps to describe releasing dragged term and final state.
- [x] All scenarios: clearer, more straighforward description of final state, what’s on plates

**Comment by pixelzoom** [comment]
@Nancy-Salpepi please review in main,  or have a look at https://github.com/phetsims/equality-explorer/commit/d21172da485804bdbd4d1e997f83e95b371c3553 to see what was changed.  Close if OK.

**Comment by Nancy-Salpepi** [comment]
Some more improvements and typos I noticed:

- [x] Scenario 12 Step 4: change 'is created on the plate' to 'is created on the right plate'
- [x] Scenario 14 Step 6: Can we use the same wording as in Scenario 22 step 6? Change  'and the inverse term (-1) is replaced by the equivalent term. The result is 1 on the left plate, and empty right plate.'     to 
'and that the equivalent term is added to the inverse term on the right plate. The result is 1 on the left plate, 0 on the right plate.'
- [x] Scenario 15 Step 7: Change 'the result a 1 on the left plate,' to 'the result is 1 on the left plate,'
- [x] Scenario 19 (the numbering looks off in https://github.com/phetsims/equality-explorer/commit/d21172da485804bdbd4d1e997f83e95b371c3553 for this scenario and a few others)
                 Step 3: Change 'from a toolbox.' to 'from the left toolbox.'
                 Step 5: Change 'on the scale.' to 'on the left plate.'
- [x] Scenario 20
                Step 3: Change 'from a toolbox.' to 'from the left toolbox.'
- [x] Scenario 21 Step 4: Change 'right late' to 'right plate'
- [x] Scenario 22 Step 4: change 'is created on the plate' to 'is created on the right plate'

**Comment by pixelzoom** [comment]
Thanks @Nancy-Salpepi, I made the above changes. Back to you for review, close if OK.

**Comment by pixelzoom** [comment]
PS - I did fix the numbering that was "off" in a few scenarios.

**Comment by Nancy-Salpepi** [comment]
Sorry I missed this the last time.... 
For Scenario 23 Step 8, change 'The result is 2 on the left plate, 0 on the right plate. ' to 'The result is 1 on the left plate, 0 on the right plate. 

Everything else looks great and hopefully this is clearer to users in the future!

**Comment by pixelzoom** [comment]
Done, back to you @Nancy-Salpepi. Close if OK.

**Comment by Nancy-Salpepi** [comment]
🎉🎉🎉🎉🎉🎉
Closing.

**Comment by Nancy-Salpepi** [comment]
Reopening. Sorry. 
Scenario 13 should start with: 
Run with ?speed=0.1 to slow animation.

**Comment by pixelzoom** [comment]
Thanks @Nancy-Salpepi. Scenario 13 has been revised.  There's no need to patch this into the release branches, because this document will always be referred to in main.  So please review in main, and if it looks good you can close this issue - no need to verify in an RC.

**Comment by Nancy-Salpepi** [comment]
Looks good. Closing (again).
