### ISSUE TITLE
Selecting a snapshot makes no sound.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#220]
For https://github.com/phetsims/qa/issues/1172 and #181.

@Nancy-Salpepi reported that selecting a snapshot in the Snapshots accordion box does not current have a sound.

**Comment by pixelzoom** [comment]
There is now a sound associated with each snapshot. Each snapshot has a different tone, and the pitch decreases from top to bottom -- similar to items in a combo box.  This seemed more appropriate than something like a push button sound, which would be indistinguishable from the snapshot (camera) buttons.

@Nancy-Salpepi please review in main, close if OK.

**Comment by Nancy-Salpepi** [comment]
Sounds great! I think the combo box sounds were a nice choice!
Closing.
