### ISSUE TITLE
Delay when switching between screenshots with full plates [Chromebook]

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/equality-explorer#222]
**Test device**
Chromebook Lenovo 2e

**Browser**
Chrome

**Problem description**
For https://github.com/phetsims/qa/issues/1172, https://github.com/phetsims/qa/issues/1173 and https://github.com/phetsims/qa/issues/1174

While testing EE: Two Variables, I noticed that when switching between screenshots that have full plates, there is a delay of ~2 seconds. The published version is about ~1. 
This also happens with EE and EE:Basics.

@Matthew-Moore240 had similar results on a Lenovo 2e second generation. He said it takes about twice as long (~2seconds) in the dev version as in published (~1 second) to load a screenshot. 

**Steps to reproduce**
Here is an example (listen with sound on to hear when I press the button):
1. In EE: 2 Variables fill both plates with terms
2. Take a screenshot
3. Make some changes but keep the plates full or almost full 
4. Take a screenshot
5. Repeat steps 3 and 4
6. Load the first screenshot
7. Load the second screenshot etc

**Visuals**

https://github.com/user-attachments/assets/b02ad864-85b3-4139-8c90-ff2b8c7f8a91

**Comment by Nancy-Salpepi** [comment]
I don't think this has a huge impact on the user experience, but I wanted you to know ☺️. Feel free to ignore.

**Comment by pixelzoom** [comment]
@Nancy-Salpepi Is this delay present in [the published version](https://phet.colorado.edu/sims/html/equality-explorer/latest/equality-explorer_all.html), or is it new?

**Comment by pixelzoom** [comment]
Actually, no need to test the published version @Nancy-Salpepi.  

This delay was previously reported in https://github.com/phetsims/equality-explorer/issues/83.

The diagnosis was described in https://github.com/phetsims/equality-explorer/issues/83#issuecomment-387801713:
> That performance hit is (unfortunately) unavoidable; the time to restore a snapshot's view increases linearly with the number of terms. It's previously been run past the design team, and the consensus was that the user can tolerate (perhaps might even expect) a bit of time to restore a snapshot.

And the consensus in https://github.com/phetsims/equality-explorer/issues/83#issuecomment-393677633 was:
> 5/31/18 design meeting: Discussed and demonstrated the delay to restore a snapshot, and it was deemed acceptable.

So closing as "won't fix".
