### ISSUE TITLE
when a snapshot is created, automatically select it

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#24]
In a request for feedback on [1.0.0-dev.48](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.48/equality-explorer_en.html), @ariel-phet suggested via email:

> 1. On the flow of taking a snapshot and reloading. It took me a moment to know I had to click the snapshot to get the blue rectangle and activate the reload and trash button. What about if that blue rectangle just appeared over the last snapshot you took and those trash and reload buttons were active as long as there was a snapshot "in play". I just feel that might be a more seamless user experience, since there is not an obvious clue to click the snapshot choices. (I don't think I saw a discussion of that question in the github issue)

**Comment by pixelzoom** [comment]
I think this is a good suggestion - when the user creates a snapshot, they will be immediately introduced to the look of a selected snapshot.  5 minutes to implement.

**Comment by pixelzoom** [comment]
@amanda-phet This suggestion is implemented in [1.0.0-dev.50](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.50/equality-explorer_en.html).  Do you approve?

**Comment by amanda-phet** [comment]
I like this change a lot!

**Comment by pixelzoom** [comment]
Great.  Then change accepted and closing.  Thanks for the suggestion @ariel-phet.
