### ISSUE TITLE
Assertion failed: cannot dispose while event is in progress

### ISSUE THREAD

**Issue by samreid** [phetsims/equality-explorer#25]
I noticed this problem while fuzzing Equality Explorer as part of https://github.com/phetsims/tandem/issues/46

```
Uncaught Error: Assertion failed: cannot dispose while event is in progress
    at window.assertions.assertFunction (assert.js:22)
    at ItemDragListener.dispose (PhetioObject.js?bust=1513717229488:116)
    at ItemDragListener.dispose (SimpleDragHandler.js?bust=1513717229488:268)
    at ItemDragListener.dispose (ItemDragListener.js?bust=1513717229488:183)
    at ItemNode.disposeItemNode (ItemNode.js?bust=1513717229488:112)
    at ItemNode.dispose (ItemNode.js?bust=1513717229488:125)
    at ItemNode.Node.dispose (Node.js?bust=1513717229488:492)
    at Array.<anonymous> (ItemCreatorNode.js?bust=1513717229488:54)
    at Emitter.emit1 (Emitter.js?bust=1513717229488:155)
    at VariableItem.dispose (AbstractItem.js?bust=1513717229488:56)
```

This assertion was newly introduced in https://github.com/phetsims/phet-io/issues/1281 and may indicate a problem in the library or in the sim code, I'm not sure which.  Co-assigning to @pixelzoom and @samreid.

**Comment by pixelzoom** [comment]
Looks like `startEvent` was called, and I'm calling `dispose` before `endEvent` has been called.  This sim isn't instrumented, so I'm not clear on why `startEvent` was called.   This also has big general implications -- e.g. if some Node is being dragged, and an action is taken that causes the Node to be disposed (like pressing Reset All button), then this assertion failure will presumably occur.

**Comment by pixelzoom** [comment]
Raising priority to high.  I need this to be resolved, since it's impacting my ability to do effective fuzz testing.

**Comment by pixelzoom** [comment]
I said:
>  This sim isn't instrumented, so I'm not clear on why startEvent was called. 

`ItemDragListener` is a subtype of `SimpleDragHandler`, which calls `startEvent` and `endEvent`.   So looks like I get this whether I asked for it or not.

**Comment by pixelzoom** [comment]
The implementation of `dispose` in `SimpleDragHandler` looks wrong to me, it duplicates a lot of stuff that's in `endDrag`:

```js
    dispose: function() {
      if ( this.dragging ) {
        this.pointer.dragging = false;
        this.pointer.cursor = null;
        this.pointer.removeInputListener( this.dragListener );
      }
      PhetioObject.prototype.dispose.call( this );
    }
```

Perhaps it should be:

```js
    dispose: function() {
      this.endDrag( null );
      PhetioObject.prototype.dispose.call( this );
    }
```

... but will `endDrag( null )` cause problems?    I sure hope not, because that's the current recommended way of ending a drag cycle programmatically (for SimpleDragHandler), and is used in function-builder and unit-rates.

**Comment by samreid** [comment]
The SimpleDragHandler.dispose was added by @jonathanolson in https://github.com/phetsims/scenery/issues/647

I wonder if we need to apply the same strategy to PhetioObject--ending an in-progress action (if any).

**Comment by pixelzoom** [comment]
Calling `endDrag( null )` looks generally dangerous to me, because of this:

```js
    endDrag: function( event ) {
      ...
      if ( this.options.end ) {

        // drag end may be triggered programmatically and hence event and trail may be undefined
        this.options.end.call( null, event, this.trail );
      }
```

If the client provide an `options.end` callback that requires an event, then boom.

**Comment by pixelzoom** [comment]
I tried changing SimpleDragHandler `dispose` to:

```js
   dispose: function() {
      this.endDrag( null );
      PhetioObject.prototype.dispose.call( this );
    }
```

... and I'm still experiencing the assertion failure with fuzzMouse.

**Comment by pixelzoom** [comment]
@samreid said:
> The SimpleDragHandler.dispose was added by @jonathanolson in phetsims/scenery#647

@jonathanolson can you comment on why `dispose` does only _some_ of the "cleanup" things that normally occur in `endDrag`?   If `dispose` is called during a drag cycle, `this.dragging` remains `true`, the client's `options.end` callback is never called, and `this.pointer` still holds a reference to the pointer.

**Comment by pixelzoom** [comment]
This has nothing to do with sim-specific code and is blocking my ability to fuzz test.  So I commented out the failing assertion in the above commit.  

@samreid @jonathanolson There appear to be 2 problems here:

(1) `startEvent`/`endEvent` pairing is not considering the possibility of an interrupted drag cycle.

(2) The cleanup done by SimpleDragHandler `dispose` appears to be incomplete, when compared with `endDrag`.

**Comment by pixelzoom** [comment]
Continuous testing report shows that many sims are experiencing this assertion failure.

**Comment by jonathanolson** [comment]
> @jonathanolson can you comment on why dispose does only some of the "cleanup" things that normally occur in endDrag? If dispose is called during a drag cycle, this.dragging remains true, the client's options.end callback is never called, and this.pointer still holds a reference to the pointer.

> (2) The cleanup done by SimpleDragHandler dispose appears to be incomplete, when compared with endDrag.

Presumably if there's a chance of dispose() being called during a drag, we COULD add interrupt() to the dispose()? It feels slightly unclean to DO things other than dispose during a dispose call, and I'd consider requiring clients to make sure they don't dispose something while dragging.

As for the unchanged variables on the SimpleDragHandler, it shouldn't matter. If you dispose it, you shouldn't be accessing it afterwards or assuming things about its state.

So I can:

1. Add an assertion that prevents disposing a "dragging" SimpleDragHandler, or
2. Add an `interrupt()` call at the start of `dispose()`.

> ... but will endDrag( null ) cause problems? I sure hope not, because that's the current recommended way of ending a drag cycle programmatically (for SimpleDragHandler), and is used in function-builder and unit-rates.

It should be permitted to call `interrupt()` yourself. Some things assume the presence of event.pointer and event.currentTarget (which it handles). In general, I think it's best to never assume there is an actual DOM input event for end drags.

**Comment by samreid** [comment]
> (1) startEvent/endEvent pairing is not considering the possibility of an interrupted drag cycle.

Currently, `endEvent` requires the message ID for cross-checking.  This makes it difficult to end the event from a different context than where `startEvent` was called (because the `id` would not be available).  However, we added enough assertion checking in PhetioObject (checking `eventInProgress` at startEvent and endEvent) that I think it will be possible to convert the `var id = ...` to an instance variable.  This will clean up usage sites.  This will also prevent re-entrant events from the same instance, but they were already prevented by the `eventInProgress` assertions, so that is a break-even.  Equality explorer has been successfully fuzzing for more than 15 minutes, so I think this is safe to commit, but would be good to have @pixelzoom review. I'll also create a side issue for removing usage of `var id = ...`, but I'm inclined to postpone that step until review here is complete.

**Comment by samreid** [comment]
Commits are https://github.com/phetsims/tandem/commit/b4f52211961982d614dd3c14572cbfab85479a89 and https://github.com/phetsims/scenery/commit/8ad4f42933eb050ddd092c1bb7b2f0bd17029894

@pixelzoom can you please review the preceding comment and the change sets?

**Comment by samreid** [comment]
I discovered an attempted re-entrant startEvent during area-model-multiplication fuzzing.  If I understand correctly, DragListener extends PressListener and both of their `release` methods are trying to start/end event.  Removing the event from the subtype appears to help (at least fuzzing is passing a lot longer), I'll commit that change here:

**Comment by samreid** [comment]
I'm still seeing far too many `Uncaught Error: Assertion failed: cannot start event while event is in progress` on Bayes, I'm going to comment out the assertion again and look into this more tomorrow (today).

**Comment by pixelzoom** [comment]
From a quick look at the commits... Making PhetioObject `eventInProgress` public is not a good direction. This flag is an implementation detail that should be private to `PhetioObject`, and now it's leaked into SimpleDragHandler.   It also does nothing to address the general issue of interrupted event cycles -- which will presumably also be a problem in DragListener.

**Comment by pixelzoom** [comment]
Removing high-priority label since this is no longer preventing me from fuzz testing.

**Comment by samreid** [comment]
I moved the comments about SimpleDragHandler dispose to a new scenery issue https://github.com/phetsims/scenery/issues/725

**Comment by samreid** [comment]
I made `eventInProgress` private again and addressed interrupted events.  The `endEvent` and `dispose` got more complicated, but I couldn't see a better solution given our constraints.  @pixelzoom can you please review?

**Comment by samreid** [comment]
Oops there is still a bad `eventInProgress` reference, self-assigning to investigate.

**Comment by samreid** [comment]
OK that's fixed, reassigning to @pixelzoom to review the changes to PhetioObject.js

> I made `eventInProgress` private again and addressed interrupted events.  The `endEvent` and `dispose` got more complicated, but I couldn't see a better solution given our constraints.

**Comment by pixelzoom** [comment]
So let me summarize to see if I inferred the solution correctly from the commits...  

The solution is to allow `endEvent` to be called on a PhetioObject that has been disposed, and the `endEvent` in that case is a no-op.  The data stream will contain a "start" event with no matching "end" event, and that won't be a problem.   

Is that correct?

**Comment by samreid** [comment]
> The solution is to allow `endEvent` to be called on a PhetioObject that has been disposed, and the `endEvent` in that case is a no-op. 

That is correct.

> The data stream will contain a "start" event with no matching "end" event, and that won't be a problem.   

That is incorrect.  If disposed during event processing, `endEvent()` is called from `dispose` (line 135), so there will be a matching end event.

**Comment by pixelzoom** [comment]
>  ... If disposed during event processing, `endEvent()` is called from `dispose` ....

Thanks for clarifying, I missed that while reading through the commits. 

I think we're done here, so closing. (Reopen if there's more to do.)
