### ISSUE TITLE
fonts for snapshots

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#26]
In a request for feedback on [1.0.0-dev.48](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.48/equality-explorer_en.html), @ariel-phet said via email:

> 2. I know you want things easy to read in the snapshot section, but I find the change in size of snapshots from short equations/inequalities to long ones a bit jarring. I would lean towards just always keeping them a consistent (smaller) size.

My response was:

> Font size is currently a compromise. In screens 2-4, the font size is uniform, regardless of the length of the equations — equations are shorter, so we have room for a font size that is sufficiently usable. In screen 1, the equations can be considerably longer, so using a uniform font would result in all equations having a very small font.  Rather than have all equations in screen 1 suffer, we decided to prefer usability over consistency.  Easy to change, if desired. 

@amanda-phet's response was:

> I agree that the variation in font sizes isn’t ideal, but the smallest size was only allowed because it wouldn’t likely happen 100% of the time. So I think this was a good compromise. 

More on the decisions related to this issue can be found in https://github.com/phetsims/equality-explorer/issues/23#issuecomment-350330029 (refine UX for snapshots).

**Comment by pixelzoom** [comment]
@ariel-phet are you satisfied with the compromise described above?  If so, we can close this issue.  If not, please discuss with @amanda-phet.

**Comment by ariel-phet** [comment]
I leave it to designer discretion here. I understand the concerns, and why they were compromised they way they were.

**Comment by pixelzoom** [comment]
In a request for feedback on 1.0.0-dev.48, Argenta Price said via email:

> I don't mind the snap shots getting smaller when there's too much stuff to easily fit, and I agree with Amanda that the less crowded scenarios will be the ones with snap shots taken anyway.
