### ISSUE TITLE
simplify animal icons?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#27]
This issue concerns the icons (dog, cat, turtle) in the "Animals" scene, found in the "Basics" screen.

In a request for feedback on [1.0.0-dev.48](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.48/equality-explorer_en.html), @ariel-phet said via email:

> 3. In playing with the sim, I think the animal pieces have a bit too much detail. I wonder could these be simplified, especially for the snapshot feature, the simpler items (such as the fruit or shapes) seem to work much better visually.

My response was:

> My recommendation prior to creation of the animals was “avoid unnecessary detail", see https://github.com/phetsims/equality-explorer/issues/6#issuecomment-332958578.  Amanda said "I'm not concerned about detail in the snapshots, only that they can be interpreted correctly”, https://github.com/phetsims/equality-explorer/issues/6#issuecomment-337657365.  I don’t think that the current icons will be misinterpreted.  But I agree that they don’t work as well as the other icons in the Basics screen.

**Comment by amanda-phet** [comment]
Students seemed to enjoy the items on the Basics screen and  didn't have trouble distinguishing between items or reading the snapshots. For the most part they named them appropriately, except that one student referred to the red coin as the one with the "curly hair". If that coin wasn't already in a published sim I would recommend changing the image. 

The interviews were done on an iPad (so a smaller screen than a laptop) so I think that these images were all successful. 

In response to @ariel-phet 's question about simplifying the artwork, I think it would be difficult to do that any further than we have, and since they didn't pose a problem in interviews I would like to keep them the way they are right now. 

Assigning to @ariel-phet to respond or close. If you feel strongly about this, of course it can be open for discussion.

**Comment by ariel-phet** [comment]
@amanda-phet I am not concerned about things being misinterpreted. The iPad you were using was likely a retina screen. My concern was more that things looking aliased. The sim looks pretty clean on chrome, but for instance, when I look at it on FF the anmials (even in the equation) are a bit aliased. (below is a screenshot at full screen size on FF)

![animals](https://user-images.githubusercontent.com/4051174/34900306-fa71a812-f7bb-11e7-86fd-c4fc7f2c6400.PNG)

I would prefer these images looking cleaner. But I will leave that to your call.

**Comment by pixelzoom** [comment]
@ariel-phet said:
> ... when I look at it on FF the anmials (even in the equation) are a bit aliased. ...

Hmmm... Surprisingly, these images do look a little mangled on FF, even with FF 57+ and its new Quantum rendering engine.

**Comment by pixelzoom** [comment]
@ariel-phet said:
>  I am not concerned about things being misinterpreted. The iPad you were using was likely a retina screen. My concern was more that things looking aliased. The sim looks pretty clean on chrome, but for instance, when I look at it on FF the anmials (even in the equation) are a bit aliased. 

The "aliased" problem isn't specific to the animal icons.  It's an issue with _all_ of the image-based icons (everything except 1, -1, x, -x). Rendered images look ragged on FF 57.0.4 (latest).  Disappointing, since I was hopeful that Quantum was going to address the render-quality issue that we've historically had with FF.  @jonathanolson FYI.

So if @ariel-phet is not concerned about misinterpretation, then there's probably no need to change the animal icons, and we can close this issue.  And if we want to address the more general rendering-quality issue on FF, we should open a new issue to do so. Or we could just live with the inferior quality on FF, as we've done in the past for some other sims.

**Comment by pixelzoom** [comment]
Investigating improvements to FF rendering quality in https://github.com/phetsims/equality-explorer/issues/33.

**Comment by pixelzoom** [comment]
@amanda-phet There is one bit of detail in the dog icon that I do recommend getting rid of. That's the detail in the tail, shown in the screenshot below.  In the screenshots in #33, it shows up as a black dot on the tail.  I keep thinking it's dirt on my screen :) 

![dog-dot](https://user-images.githubusercontent.com/3046552/34900900-3a8347c6-f7c1-11e7-95b0-867c110e360e.jpg)

**Comment by pixelzoom** [comment]
@amanda-phet There is one bit of detail in the dog icon that I do recommend getting rid of. That's the detail in the tail, shown in the screenshots below.  I keep thinking it's dirt on my screen :) 

![dog-dot](https://user-images.githubusercontent.com/3046552/34900900-3a8347c6-f7c1-11e7-95b0-867c110e360e.jpg)

![small-dog-dot](https://user-images.githubusercontent.com/3046552/34900944-a7320f56-f7c1-11e7-8942-f9a628704658.jpg)

**Comment by jonathanolson** [comment]
> Rendered images look ragged on FF 57.0.4 (latest). Disappointing, since I was hopeful that Quantum was going to address the render-quality issue that we've historically had with FF. @jonathanolson FYI.

It looks like the `image!` plugin is being used, instead of the `mipmap!` plugin (which would hopefully improve the appearance on Firefox). Is that worth a try?

**Comment by pixelzoom** [comment]
@jonathanolson I don't think the mipmap plugin is necessary, this seem to be an issue caused by extreme down-scaling, see #33.

**Comment by amanda-phet** [comment]
I agree we can remove that bit of detail on the dog. I will give it a shot and if it's too difficult for me I will ask Cheryl to do it.

**Comment by amanda-phet** [comment]
How about this?
![screen shot 2018-01-15 at 11 42 46 am](https://user-images.githubusercontent.com/7852916/34957076-40f41cdc-f9e9-11e7-9ab7-d73a849f0743.png)

**Comment by pixelzoom** [comment]
@amanda-phet That looks great. Reminder that the same change must be applied to the shadow.

Please revise these .ai files:

https://github.com/phetsims/equality-explorer/blob/master/assets/basics-artwork-without-shadows.ai
https://github.com/phetsims/equality-explorer/blob/master/assets/basics-artwork-shadows.ai

You can either send me the new files, or push the changes to GitHub yourself, if you prefer.

**Comment by amanda-phet** [comment]
The new .ai files are uploaded. Do I need to export the artwork as well or will you do that? I recall there were a lot of issues with exporting...

**Comment by pixelzoom** [comment]
I'm handle creating the PNG files. FYI, the process for creating PNG files from .ai is documented in https://github.com/phetsims/equality-explorer/blob/master/assets/README.md.

**Comment by pixelzoom** [comment]
@amanda-phet Looks like you checked in `assets/Screen Shot 2018-01-15 at 11.41.48 AM.png`, the screenshot in https://github.com/phetsims/equality-explorer/issues/27#issuecomment-357760633.  I'm going to delete it. If there's some reason that you want it checked in, let me know and I'll restore it.

**Comment by pixelzoom** [comment]
@amanda-phet Looks like you changed basics-artwork-shadows.ai.  But basics-artwork-without-shadows.ai still contains the old dog icon.

**Comment by pixelzoom** [comment]
Dog icon has been revised in [1.0.0-dev.56](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.56/equality-explorer_en.html).  Compare to [1.0.0-dev.55](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.55/equality-explorer_en.html).

@amanda-phet please review, feel free to close.

**Comment by amanda-phet** [comment]
I like it quite a bit. Good suggestion.
