### ISSUE TITLE
adjust the cutoff for whether an item is on or off the scale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#29]
In a request for feedback on 1.0.0-dev.48, @ariel-phet said via email:

> I think I would change the default of where an object will pop onto the tray to be a little bit more generous. I'm not exactly sure of the rule right now, but it seems like you have to have more than 1/2 above the top lip. Perhaps, if 1/2 of its body is above the bottom edge of the tray it should pop up instead of returning to the carousel. I found that I often was lazy and releasing a bit early, and having to start over with my drag. 

The current "cutoff" is that the center of the item must be above the center of the plate.  This is easy to tweak, just let me know what you'd prefer.  Note that the same cutoff is used for items that are dragged from the scale, or from the panels below the scale.  If you want different cutoffs (which I think would be potentially confusing) it will be more work.

For reference, in Unit Rates, the cutoff point is 70 units below the center of the scale's plate.

As I recall, @phet-steele has had some good input on this type of issue in the past.

**Comment by pixelzoom** [comment]
I've added a query parameter in [1.0.0-dev.53](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.53/equality-explorer_en.html) that will let you play around with where the cutoff is located.   The new query parameter is `plateYOffset`, default value `0`.   When you run with `?dev`, the cutoff is represented by a horizontal red dashed line below each plate.  

Examples:

[1.0.0-dev.53/equality-explorer_en.html?dev](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.53/equality-explorer_en.html?dev) gives you the default (`0`) offset, so the cutoff is at the center of the plates:

![screenshot_452](https://user-images.githubusercontent.com/3046552/34499416-385009ae-efc3-11e7-9e44-b5689bd93d98.png)

[1.0.0-dev.53/equality-explorer_en.html?dev&plateYOffset=25](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.53/equality-explorer_en.html?dev&plateYOffset=25) moves the cutoff line down 25 units from the center of the plates:

![screenshot_453](https://user-images.githubusercontent.com/3046552/34499413-364b6da6-efc3-11e7-9eab-af4ab1f48a18.png)

Please let me know what default value you'd like for `plateYOffset`. Reminder that the items have their locations at their centers.  Be sure to also test taking items _off_ the plates, since the same cutoff line is used. Also highly recommended to test on both desktop and iPad -- being able to flick items on/off the plates is especially useful on iPad.

**Comment by pixelzoom** [comment]
Also highly recommended to test this on both desktop on iPad.  Being able to flick items on/off the plates is especially useful on iPad.

**Comment by pixelzoom** [comment]
As I mentioned in https://github.com/phetsims/equality-explorer/issues/29#issue-285513145:
> @phet-steele has had some good input on this type of issue in the past.

@phet-steele I'd like your recommendation on the default value for `?plateYOffset` (see above), so that we don't need to revisit this issue after the sim enters QA.

**Comment by amanda-phet** [comment]
I really like the offset of 25 on the desktop! I've been meaning to ask if we could tweak this and the parameter makes this really easy to test. 

The tricky thing on the iPad is that the items jump up above your finger, so that combined with the lower offset makes it really difficult to remove items. plateYOffset=18 seems to work a bit better for me on the iPad, and logically feels like the right place because the center of the item needs to be below the lowest part of the plate to be removed.

**Comment by pixelzoom** [comment]
@amanda-phet If we need different offsets for mouse vs touch, that's possible.  

[1.0.0-dev.54](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.54/equality-explorer_en.html?dev) has default `plateYOffset=18`. Here's a screenshot, showing the cutoff as a dashed line when running with `?dev`:

![screenshot_457](https://user-images.githubusercontent.com/3046552/34624452-9b9715ec-f212-11e7-8fde-d881a5d6de08.png)

FYI, Unit Rates ultimately used a much larger offset of `70` (again, from the center of the plate). Here's a screenshot showing the cutoff as a solid horizontal line when running with `?dev`:

![screenshot_458](https://user-images.githubusercontent.com/3046552/34624504-cb8655d8-f212-11e7-98ed-8a7b24db8060.png)

I suspect that we'll end up choosing a bit larger `plateYOffset` for Equality Explorer.  But I doubt that 70 is appropriate for Equality Explorer, because the plates are smaller, and the plates move.  With 70, the cutoff seems too close to the panels when a plate is bottomed out. E.g:

![screenshot_459](https://user-images.githubusercontent.com/3046552/34624676-5bc932a0-f213-11e7-961c-6f77844ba23e.png)

**Comment by pixelzoom** [comment]
Example of how the default aliases are inappropriate. With default alias for `ls`, I get the classic blue-on-black coloring for directories:

![screenshot_460](https://user-images.githubusercontent.com/3046552/34625261-43fa1f70-f215-11e7-9e48-88f6b6afbb17.png)

**Comment by amanda-phet** [comment]
I don't recall all of the conversations about Unit Rates, but I don't think we want to go too low. For the moment, and the interviews I have scheduled, let's stick with 18. Maybe I should do one interview on iPad and one on laptop.

**Comment by pixelzoom** [comment]
@phet-steele If you could find some time to give input on this, I'd appreciate it.  I'd like to have our "best guess" on this before I send it back to @kathy-phet for verification.

**Comment by phet-steele** [comment]
I'm liking `plateYOffset=18` for these reasons:

1. It tested well in interviews
2. In a sim such as this where we have a moving target (the scale in UR was static), it's more important to have the cutoff in a location that is visually consistent with the scale. In other words, It should look like I'm about to place/take off an item based on its relative position to the plate. It's difficult to find a cutoff that _feels_ great at every location of the scale, so we should settle on something that _looks_ great. That's my best guess...

If my arm was twisted, I might try `plateYOffset=33`. This is right where an object would just start touching the bottom of the plate.

@pixelzoom apologies for the late response, I was waiting for interviews to conclude and hear from AM.

**Comment by pixelzoom** [comment]
Thanks @phet-steele.

@amanda-phet let me know if you want to change anything here.  If nothing to change, please please solicit feedback from @kathy-phet.

**Comment by amanda-phet** [comment]
Two students were interviewed using iPads and they did not have any trouble with putting objects on or off the plates. There may have been a handful of times that they tried to put it on the plate and it didn't make it, but immediately after they were able to successfully place the item. 

I think the current offset is logical and functioning well. 

@kathy-phet can you let us know what you think of the offset?

**Comment by pixelzoom** [comment]
@kathy-phet the dev version for your review is:
https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.54/equality-explorer_en.html

Add the `?dev` query parameter to show a horizontal line indicating where the cutoff is.
Use `plateYOffset=25` (for example) to shift the cutoff line. The default is 18.

**Comment by kathy-phet** [comment]
This seems good to me. Thanks!

**Comment by pixelzoom** [comment]
Excellent, thanks @kathy-phet. Closing.

**Comment by pixelzoom** [comment]
Noet: After closing this issue, I changed the query parameter used to show the cutoff line.  It was previously shown with `?dev`, but that's a common-code query parameter.  It's now shown with `?showOrigin`, along with the origins of various other things (items, scale, plates,...)

**Comment by pixelzoom** [comment]
Changed my mind again... Back to using `?dev` to should the cutoff line, and all other "debug nodes".
