### ISSUE TITLE
better titles for accordion boxes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#3]
As I'm testing the sim while implementing, the title "Equation or Inequality" feels a bit clunky. Can we brainstorm some other possibilities?

![screenshot_289](https://user-images.githubusercontent.com/3046552/27665437-60511920-5c2a-11e7-9b22-1c5ca3d180cd.png)

**Comment by pixelzoom** [comment]
The "My" on "My Snapshots" also makes me gag a little. It's so Microsoft Windows.

**Comment by pixelzoom** [comment]
The "My" on "My Snapshots" also makes me gag a little. It's so Microsoft Windows.  I don't mind it so much when it's something that's "custom" (e.g. "My Solution").  But there aren't any snapshots here other than the ones that the user has created.

**Comment by amanda-phet** [comment]
Tried brainstorming the "equality or inequality" title and that seemed to be the most accurate label. 

We can just call the snapshots panel "Snapshots".

**Comment by amanda-phet** [comment]
Tried brainstorming the "equality or inequality" title and that seemed to be the most accurate label. I'm happy to consider other options!  

We can just call the snapshots panel "Snapshots".
