### ISSUE TITLE
make it easier to "coordinate information" while changing value of x

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#30]
In a request for feedback on 1.0.0-dev.48, @kathy-phet said via email:

> On the variables screen, I had some desire to be able to "sub in" the x-value, as you can in Expression exchange. So to change the "x's" to display the current value of x, so that as I was changing x, I could see all of those values changing. This is more of a pedagogy question -- and I cannot remember if we discussed it. I was just thinking about it, because I was finding that I had to do a lot of looking back and forth between x value and the equation, as I was changing x to really coordinate all of the information and carry out the multiplication. And that was a fairly long distance for my eyes to go back and forth -- I could not keep both in my active view at the same time. If I could temporarily display x as a changeable value, I could be changing x but keep my eyes on the equation. 
>
> A different possibility to support having both in my active view would be to optionally display "(x=2)" in the equation box .... similar to how it is optionally displayed in the snapshot saves. I do think it would need to be optional though to allow for teacher facilitation. I think I like the second of these options more. Keeping the x in the equation, but optionally displaying the dynamic value up where the equation is. Anyway, thoughts on this? I played around a bit - see attached - just to see some options.

Snapshots of @kathy-phet's EE_Mockup.ppx attachment:

Slide 1 (current UX?):
![screenshot_440](https://user-images.githubusercontent.com/3046552/34496831-5f89a3e6-efb8-11e7-9eaa-f524eed73b6a.png)

Slide 2:
![screenshot_441](https://user-images.githubusercontent.com/3046552/34496834-64588766-efb8-11e7-9f91-ffe458d6f5db.png)

Slide 3:
![screenshot_442](https://user-images.githubusercontent.com/3046552/34496841-68930432-efb8-11e7-8af7-297249102548.png)

Slide 4 (with @kathy-phet's annotation in yellow):
![screenshot_443](https://user-images.githubusercontent.com/3046552/34496844-6d02fa86-efb8-11e7-9ab2-4c0971d78951.png)

So @kathy-phet has proposed 3 options:

• Option 1: replace 'x' with its value, similar to Expression Exchange

• Option 2: show 'x = value' in (or near) the "Equation or Inequality" accordion box (Slides 2 & 3)

• Option 3: move the x picker closer to the "Equation or Inequality" accordion box (Slide 4)

My comments/feedback on these 3 options appears in the comments below.

**Comment by pixelzoom** [comment]
**Option 1**:  replace 'x' with its value, similar to Expression Exchange

In Expression Exchange, see the "Variable Values" check box in the Negatives screen.  When not checked, a term looks like this:
![screenshot_438](https://user-images.githubusercontent.com/3046552/34497017-f4f07324-efb8-11e7-92a5-a3abbd08f478.png)

When checked, the same term looks like this (where x = 2):
![screenshot_439](https://user-images.githubusercontent.com/3046552/34497041-04eb560e-efb9-11e7-8a97-4d06fba0c58f.png)

The pedagogy question is outside my wheelhouse, but a few comments about option 1:

• Expression Exchange has multiple variables (x, y), while Equality Explorer has only one (x). So I'm wondering how valuable this feature would be, and why you'd need to see every 'x' replaced by its value.
• At this point in development, this will be a huge change.  It will affect almost everything -- items, equations, snapshots,...
• It will be challenging to find a place to put a "Show x value" check box.

**Comment by pixelzoom** [comment]
**Option 2**: show 'x = value' in (or near) the "Equation or Inequality" accordion box (Slides 2 & 3)

This option would be relatively easy to add. But I don't like the control as shown in Slides 2 & 3. The control should be located close to (or better yet, inside) the "Equation or Inequality" accordion box, since that's what it affects. And it should not be labeled "Show x"; it does the same thing as the "x = ?" control in the Snapshots accordion box. The display of "x = value" also can't be below the Equation accordion box, as shown in Slider 2 -- that space is used by the "universal operator" in the Solving screen.

Here's another mockup for option 2.  The check box is inside the "Equation or Inequality" accordion box.  When it's unchecked, the check box is labeled "x = ?", like this:

![screenshot_447](https://user-images.githubusercontent.com/3046552/34497623-8d5d853c-efbb-11e7-9cad-bff95bbcf943.png)

When it's checked, the check box label shows the value of x, like this:

![screenshot_448](https://user-images.githubusercontent.com/3046552/34497642-9ae19086-efbb-11e7-98bb-9ae213110da9.png)

I'm generally not a fan of overloading a control like this (making it both a control and a display), but in this case if may be a "lesser of evils" choice.

But another problem with option 2... If you want to hide the variable value, that now involves 2 controls -- close the Variable accordion box, and turn off the "Show x value" check box for the Equation accordion box. Trying to do something like link these controls will be (imo) confusing.

**Comment by pixelzoom** [comment]
**Option 3**: move the x picker closer to the "Equation or Inequality" accordion box (Slide 4)

One could argue that the proper location for the x picker is somewhere in close proximity to the equation. This is supported by @kathy-phet's complaint of having to move her eye "a fairly long distance".  

Slide 4 shows the picker below the Equation accordion box.  But that space is reserved for the "universal operator" in the Solving screen. So the layout would need to be something like this:

![screenshot_450](https://user-images.githubusercontent.com/3046552/34498126-712d1b1e-efbd-11e7-98eb-61a2d8c1ac9b.png)

This involves shrinking the vertical height of the x picker a bit, to accommodate the case where the left plate is bottomed out.  This would appear on the "Variables" and "Solving" screens.  

As @kathy-phet noted for Slide 4, putting the "Variable" accordion box at the top has a significant usability disadvantage: Since it's at the top of the screen, your hand may be more apt to cover parts of the screen while you're changing the value.

In terms of implementation, this is a "medium impact" change. Currently, the layout of all 3 screens is essentially the same, and we just put the "Variable" accordion box in a space (below Snapshots) that is otherwise empty. This would involve specifying the width of the "Equation or Inequality" accordion box on a per-screen basis.

**Comment by pixelzoom** [comment]
Note that putting the "Variable" accordion box at the top has one significant usability disadvantage. Since it's at the top of the screen, your hand may be more apt to cover parts of the screen while you're changing the value.

**Comment by pixelzoom** [comment]
Another problem with option 2...  If you want to hide the variable value, that now involves 2 controls -- close the Variable accordion box, and turn off the "Show x value" check box for the Equation accordion box.

**Comment by pixelzoom** [comment]
@amanda-phet @kathy-phet I edited my comments/feedback for the 3 options above.  So please read the comments here in GitHub, and ignore the email notifications from GitHub.

**Comment by amanda-phet** [comment]
We do want students thinking about substituting a value for a variable when assessing the state of the balance, so having it front and center does make sense to me. 

Chris's mockup of option 3 is my favorite. Kathy's slides 2 and 4 don't work because of the Variables screen (as Chris mentioned). 

I also like Kathy's slide 3, since the format is similar to the snapshots. In that vein, it would make sense to me to have one control for both that value and the values in the snapshots since they are similar displays, but they have very different reasons for being visible/invisible. 

So, if we want to move forward with this change, my vote would be for Chris's option 3. 

In recent interviews with two 7th graders, they didn't do much with the variable picker. They used it, and saw that it did something (move the balance), but that's about it. Having it closer to the top of the screen might make it more visible and inviting for students to engage with, or at least attend to. We can look specifically at occlusion in future interviews, but since there are two places that respond to the variable value changing (the equality statement and the balance) I think it's likely that students will notice at least one of those areas changing. 

@kathy-phet can you remind me what you thought of Chris's suggestion?

**Comment by pixelzoom** [comment]
A few of things with my "option 3", from an impromptu discussion that we had between 1/11/18 design meetings...   

(1) By moving the picker to the top, it's going to be difficult (impossible?) to keep the relational operator in the equation centered on the scale.  And it sounded like that might be important.

(2) By moving the picker to the top, changing the value of 'x' will cause your hand to obscure more of the screen.  Not sure how much of an issue that is.

(3) If we make the Equation accordion box narrower in the Solving screen, coefficients and constants will become illegible much more quickly than they do in the terms on the scale.

**Comment by pixelzoom** [comment]
(3) If we make the Equation accordion box narrower in the Solving screen, coefficients and constants will become illegible much more quickly than they do in the terms on the scale.

**Comment by pixelzoom** [comment]
1/18/18 design meeting:  We discussed option 3, but creates problems. So we decided to defer this until interview.

**Comment by pixelzoom** [comment]
1/18/18 design meeting: We discussed option 3, but creates problems. So we decided to leave this "a sis", and defer until interview, to see if students experience the same problems that @kathy-phet did.

**Comment by amanda-phet** [comment]
I took a shot at mocking this up and there is not enough room for the variable accordion if we keep the equality statement centered and large enough unless we want to start decreasing the font size sooner (which is an option, if we discover after interviews that this is important) 

![screen shot 2018-01-19 at 12 15 36 pm](https://user-images.githubusercontent.com/7852916/35167855-2c69237e-fd14-11e7-8a4e-ded8476b702c.png)

**Comment by pixelzoom** [comment]
In the above mockup, the "Variable" accordion box (with 'x' picker) is slightly unrealistic. For an accordion box that hides its title when expanded, the box's button must be fully to the left of the box's content.  You're showing some overlap.  So there's slightly less horizontal space available than what's shown in the mockup.

And I agree that this is not a feasible layout.  To use this layout, we would need to drop the requirement that the equation's relational operator is centered on the scale.   And I don't think that's a good idea, especially in the Solving screen where we have the center-aligned universal operator.

**Comment by pixelzoom** [comment]
Assigning this to @amanda-phet so that it's on her radar for interviews, see #62.

**Comment by amanda-phet** [comment]
I observed a student in an interview specifically playing with the x picker and saying "that tips the scale" and "like when you do an input [...] like plugging in the number" and plays around with the value of x. So, I observed him coordinating this information very easily. The other student also seemed to be paying attention to the play area when changing the value of x. 

I don't disagree that it would be nice to have this closer to the equation, but I also think it's useful to have near the balance. Since I didn't see an issue with a student coordinating this information in interviews I think we can leave the design as it is.

**Comment by pixelzoom** [comment]
Reopening.

@kathy-phet received input related to this issue.  I received the info from @amanda-phet, and I'll try to summarize here.   What's shown in the "Equation or inequality" accordion box is only true based on the variable value(s).  So it's important to show the values with the equation or inequality.

Putting the values inside the accordion box is not possible -- there is simply not room for the "Lab" and "Two Variables" screens.   And even if it were possible, we'd need a way to show/hide the values.  Overloading the expand/collapse button of the Variables accordion box to do that is a real hack with usability problems.  

So the best solution we could come up with is to move the Variable accordion box _above_ the Snapshots accordion box, so that it is immediately to the right of the equation/inequality.   I will create dev versions to evaluate that solution

**Comment by pixelzoom** [comment]
https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.118/phet/equality-explorer_en_phet.html?xy, note the `?xy` query parameter so you can test that screen.

If you want to run standalone xy screen, use `?xy&screens=6`.

Basics version, so you can also check the Lab screen: https://phet-dev.colorado.edu/html/equality-explorer-basics/1.0.0-dev.5/phet/equality-explorer-basics_en_phet.html

**Comment by pixelzoom** [comment]
One thing I'm not too satisfied with... The pickers in the "Lab" screen look small to me, see screenshot below.  I haven't evaluated their usability on iPad yet. 

The pickers became smaller because we need to hide the 'Values' accordion box title when expanded, so that the accordion box height matches the height of the 'Equation or inequality' accordion box.  And hiding the title means that the contents of the accordion box must be to the right of the expand/collapse button, so we loose some width.  

![screenshot_641](https://user-images.githubusercontent.com/3046552/40464007-bbc2a04a-5ed5-11e8-9171-573eb57cb43c.png)

**Comment by kathy-phet** [comment]
I thought I had seen a prior version when the Values word was still visible ant the pickers were lower and the heights did not match. I thought it worked well that way. I agree they look squished here. 

Does it have to be the same height as the Equation or Inequality?

**Comment by kathy-phet** [comment]
If left this way, the images could be smaller (only in the Values box) giving more horizontal room and the overall height of the equation box and the values box could be made 10% bigger, so the pickers can be bigger.

**Comment by pixelzoom** [comment]
@kathy-phet said:
> I thought I had seen a prior version when the Values word was still visible ant the pickers were lower and the heights did not match. I thought it worked well that way.

There was no such dev version. Perhaps you're thinking of [1.0.0-dev.4](https://bayes.colorado.edu/dev/html/equality-explorer-basics/1.0.0-dev.4/phet/equality-explorer-basics_en_phet.html), when Values was below Snapshots.

> Does it have to be the same height as the Equation or Inequality?

That was my understanding.  We want the equation and values to "read well" from left to right, as a compromise for the inability to put the values in the Equation box.  That flow is interrupted by different size boxes and the downward shift of the values caused by displaying the title. 

> If left this way, the images could be smaller (only in the Values box) giving more horizontal room and the overall height of the equation box and the values box could be made 10% bigger, so the pickers can be bigger.

The Values box is the same box used throughout all sims for displaying values, so doing something custom here is a fair amount of work.  And more importantly, I think smaller images will look and feel odd, so I'm reluctant to spend the time. 

If you mean make the Values box 10% _taller_, then that will steal space from the snapshots. The other reason why the title was hidden was to to provide room for displaying values with the snapshots.  They were previously too small.

@amanda-phet How would you like me to proceed?

**Comment by pixelzoom** [comment]
Another option we haven't discussed is making the Values box _wider_.  There is space to the left of it.   Making it wider than the Snapshots box may look a little odd, but it would make all pickers bigger without the drawbacks associated with making the box taller.

**Comment by pixelzoom** [comment]
5/24/18 design meeting:

We decided to make the Values box wider.

**Comment by pixelzoom** [comment]
The Values box was made wider.

**Comment by pixelzoom** [comment]
5/31/18 design meeting: In interviews, putting the pickers above collapsed Snapshots was more effective.  Closing.
