### ISSUE TITLE
items look ragged on Firefox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#33]
This issue was broken out of https://github.com/phetsims/equality-explorer/issues/27.

In https://github.com/phetsims/equality-explorer/issues/27#issuecomment-357389793, @ariel-phet reported that icons looked "aliased" on Firefox.  I confirmed with FF 57.0.4 Quantum.  

Investigate ways to improve.

**Comment by pixelzoom** [comment]
One thing I noticed immediately is that our PNG files have height of 100 px, while the icons in the sim are scaled to a uniform height of 32 px.   In the past, my experience has been that the more extreme the scaling, the lousier the rendering quality on FF.  So if we reduce the height of the PNG files to ~50 px, that will reduce the amount of scaling, and I would expect quality to improve.

**Comment by pixelzoom** [comment]
I did a quick test, reducing the height of the dog, cat and turtle PNG files to 50 px.  There's a dramatic improvement.  

Before:

![screenshot_468](https://user-images.githubusercontent.com/3046552/34900836-90434d2e-f7c0-11e7-9e87-54035730a82d.png)

After:

![screenshot_467](https://user-images.githubusercontent.com/3046552/34900840-93eaa0e4-f7c0-11e7-8bcb-63f89ee33502.png)

I see no reason not to reduce the height of all icon images (and their shadow images) to 50 px.

@ariel-phet If everything looks as good as the "After" screenshot above, do you think that's acceptable?

**Comment by amanda-phet** [comment]
That looks much improved to me!

**Comment by ariel-phet** [comment]
@pixelzoom yes, that is acceptable to me, feel free to close.

**Comment by pixelzoom** [comment]
OK, I'll proceed with this change (nothing has been committed yet), then close.

The lock icons have a similar problem, I'll take care ofthem too.

**Comment by pixelzoom** [comment]
Icons have been revised in [1.0.0-dev.56](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.56/equality-explorer_en.html).  Compare to [1.0.0-dev.54](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.56/equality-explorer_en.html).

@amanda-phet @ariel-phet please review. Last one to review please close.

**Comment by pixelzoom** [comment]
Icons have been revised in [1.0.0-dev.56](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.56/equality-explorer_en.html). Compare to [1.0.0-dev.54](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.54/equality-explorer_en.html).

@amanda-phet @ariel-phet please review. Last one to review please close.

(EDIT: Fixed link to 1.0.0-dev.54 above.)

**Comment by amanda-phet** [comment]
I'm happy with the fix. Thanks Chris.

**Comment by ariel-phet** [comment]
Much improved. Closing
