### ISSUE TITLE
specification of animation for universal operation

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#35]
The animation associated with the universal operation control (herein "the control") is under-specified in the design document.  It's mentioned in one sentence:

> If they decide to add 5 to both sides of the balance, a +5 will appear above both plates and drop vertically while also fading so it looks like it is getting dropped on to the plate and being absorbed. 

Questions:

- [x] If you want both motion and fading, that's not supported by PhET's current library of reusable animations (twixt).  I'll need to either create a new animation, or use Tween (3rd-party library) directly. 

DECISION: Want both motion and fading.  Try doing the motion animation first, followed by fade.  When the operation gets to its end locations, then do the fading.  (This will allow me to use a `twixt.MoveTo`, followed by `twixt.OpacityTo`.)

- [x] Where does the animation start? (x & y) Directly above the center of the plate? From somewhere near the control? ...

DECISION:
x = horizontally centered on the plate
y = vertically centered on the control

- [x] Where does the animation end? (x & y ) At some location above the scale? At some location above the plates?  Horizontally centered on the plates? Dependent in any way on the location of terms on the scale?

DECISION:
x = horizontally centered on the plate
y = bottom of operation at y location of bottomed-out plate

- [x] Depending on what's on the scale, the plates may be located at different distances from the control. Do the animated operations need to travel at different speeds, so that they arrive at the same time?

DECISION: Let's try animating the same distance regardless of where the plates are. Both operations (left and right) can then be animated together, and when that animation ends, the operation can be applied to both sides simultaneously.

- [x] If the animations need to travel as different speeds depending on plate location, what happens if the plate locations change during the animation?  Ignore the new location and continue with animation as if plates hadn't moved? Adapt to the new location?

DECISION: If we stick with the above decision (animate the same distance regardless of where the plates are) then this is a non-issue.   If we change our minds then we'll try ignoring the new location and continuing with animation as if plates hadn't moved (since this scenario is unlikely to happen.)

- [x] Describe the motion. Constant speed? Accelerate?

DECISION: try constant (linear)

- [x] When is the operation applied to the terms? When the control button is pressed? When the animation completes? ...

DECISION: When animation completes.

- [x] Is the "fading" linear? quintic? (Quintic is like the sum-to-zero animation, where most of the fade happens at the end of the animation.)

DECISION: try quintic

- [x] If applying an operation results in a zero sum (e.g. `+5` applied to `x = -5` → `x + 5 = 0`), is there any sum-to-zero animation that occurs for the term that becomes zero?

DECISION: Something like sum-to-zero animation, but not quite the same -- no halo, just a '0' or '0x' that appears and fades when a term is removed from the scale.

- [x] Do animations that are in progress need to be cancelled when Reset All is pressed?

DECISION: Yes.

**Comment by pixelzoom** [comment]
1/23/18 call with @amanda-phet, decisions interspersed above.

**Comment by pixelzoom** [comment]
@amanda-phet [1.0.0-dev.58](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.58/phet/equality-explorer_en_phet.html) implements everything we discussed, except for the sum-to-zero animation.  Before proceeding further, I'd like to know if this is in the ballpark of what you had in mind.

The animations are set up as follows:
Motion: duration=500ms, easing=Quadratic.In (Linear/constant didn't look good.)  
Fade: duration=250ms, easing=Linear.None (Quintic didn't look good.)

Easing is the function that determines how the parameter being animated changes over time. For a pictorial description of the easing options, see the graphs at [Tween.js/graphs](http://sole.github.io/tween.js/examples/03_graphs.html). The x axis is time, the y axis is the parameter being animated. 

Caveats for 1.0.0-dev.58: The terms are still not really on the scale, so they don't affect the scale or equation. You can't currently drag terms, and you can't drag items to terms.  If you want to put the scale in a "bottomed out" orientation, drag an 'x' item from the carousel to the scale, then set 'x' to a big value using the picker.

**Comment by amanda-phet** [comment]
Definitely in the ballpark. I'd like to play around a little with the easing for the motion. The fade looks fine, but for some reason I'm not a fan of the motion. Can we try Quadratic.Out? Maybe we can play with these in-person on Thursday between meetings, if you're available. 

Also, the path for the operation animation seems a little short. I bottomed out the scale but it's hard to tell since the terms don't move with it, but that seems like something that would be easy to change once the balance is more functional.

**Comment by pixelzoom** [comment]
[1.0.0-dev.59](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.59/phet/equality-explorer_en_phet.html) uses `easing=Quadratic.Out` for motion, which causes the operations to decelerate as they fall.  Happy to experiment with other easing options in-person on Thursday. Easing is trivial to change, but non-trivial to provide a query parameter.

Yes, the animation distance is trivial to change, and will certainly need to be tweaked when I get more of the Solving screen working.

**Comment by pixelzoom** [comment]
Removing high priority label, since we're in the ballpark.

**Comment by pixelzoom** [comment]
Slack discussion with @amanda-phet about the sum-to-zero animation:

Chris Malley [12:58 PM]
Do you want the animation to show ‘0x’ and ‘0’, for x term and constant term respectively?

Amanda McGarry [12:59 PM]
yes that is ideal

**Comment by phet-steele** [comment]
@amanda-phet you can preview different easing here: http://phettest.colorado.edu/twixt/twixt_en.html?brand=phet&ea

**Comment by pixelzoom** [comment]
@phet-steele I don't recommend using that demo. It's not using Tween animation, it's using easing code that is documented as:

> WARNING: PROTOTYPE, see https://github.com/phetsims/twixt/issues/3 before using!
> Not fully documented or stabilized. May be deleted.

... and therefore is not something that I will use in production code.  The easing names are similar to the Tween easing functions, but not guaranteed to be the same.

**Comment by phet-steele** [comment]
> @phet-steele I don't recommend using that demo.

Roger that!

**Comment by pixelzoom** [comment]
@amanda-phet and I tweaked the animation during an in-person meeting on 1/25.  See commit immediately above this comment.   Motion duration was increased to 700 ms, motion easing was changed to Quintic.In.

**Comment by pixelzoom** [comment]
@amanda-phet I implemented the sum-to-zero animation for universal operations applied to terms on the scale.  Please have a look at [1.0.0-dev.60](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.60/phet/equality-explorer_en_phet.html) and let me know if this is what you had in mind.  There are no halos. The '0' and '0x' use the same font size as the terms.  I tried using the font size of the operations, and it looked too small.

**Comment by amanda-phet** [comment]
I added 8 and then subtracted 8 to see the 0. I also multiplied by 0 to see both 0x and 0. Are there any other scenarios I should be trying? 

It looks great to me. The animation feels very similar to the previous screens (I can't discern if it's exactly the same or not) and looks good without the halo.

**Comment by pixelzoom** [comment]
@amanda-phet asked:
> I added 8 and then subtracted 8 to see the 0. I also multiplied by 0 to see both 0x and 0. Are there any other scenarios I should be trying?

As long as you've seen both a '0' and '0x', you've seen it all.

> It looks great to me. The animation feels very similar to the previous screens (I can't discern if it's exactly the same or not) and looks good without the halo.

The animation uses identical parameters (duration, easing,...) on all screens. 

All requirements in the checklist https://github.com/phetsims/equality-explorer/issues/35#issue-290956098 have been implemented, so closing.
