### ISSUE TITLE
"organize" the scale

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#4]
There are lots of ways that this could be done, and it's going to be non-trivial to implement. So @amanda-phet, I'd like to hear what you had in mind for how items on the scale should be rearranged when the "organize" button is pressed.  

Should items be arranged left-to-right on the scale, in the same order that they appear in the equation?  Its seems like "yes", since that would make it easier to see how what's on the scale relates to the equation.

Here are some scenarios to get us started, where A, B and C are items. The items appear (left-to-right) in the order A B C in the equation and panels below the scale.  How would you arrange each of these in a 6x6 grid?

1 A
3 A
7 A
12 A
14 A
1 A, 1 B, 1 C
6 A, 4 B, 6C
8 A, 8B, 8C
13 A, 13 B, 10 C
15 A, 14 B, 7 C
34 A, 1 B, 1 C

**Comment by pixelzoom** [comment]
The easiest implementation would be to populate the 6x6 grid from left-to-right, bottom-to-top, in the same order that items appear in the equation.  Move to a new column for each type of item (if possible, not always possible).  

Here's what that would look like for the scenarios above.

I'm using `_ _ _ _ _ _` to indicate the 6 columns in the grid.

1 A
```js
A
_ _ _ _ _ _
```

3 A
```js
A
A
A
_ _ _ _ _ _
```

7 A
```js
A
A
A
A
A
A A
_ _ _ _ _ _
```

12 A
```js
A A
A A
A A
A A
A A
A A
_ _ _ _ _ _
```

14 A
```js
A A
A A
A A
A A
A A A
A A A
_ _ _ _ _ _
```

1 A, 1 B, 1 C
```js
A B C 
_ _ _ _ _ _
```

6 A, 4 B, 6C
```js
A   C
A   C
A B C
A B C
A B C
A B C 
_ _ _ _ _ _
```

8 A, 8B, 8C
```js
A   B   C
A   B   C
A   B   C
A   B   C
A A B B C C
A A B B C C 
_ _ _ _ _ _
```

13 A, 13 B, 10 C
```js
A A B B C C
A A B B C C
A A B B C C
A A B B C C
A A B B C C
A A A B B C
_ _ _ _ _ _
```

15 A, 14 B, 7 C
```js
A A B B C C
A A B B B C
A A B B B C
A A A B B C
A A A B B C
A A A B B C
_ _ _ _ _ _
```

34 A, 1 B, 1 C
```js
A A A A A C
A A A A A B
A A A A A A
A A A A A A
A A A A A A
A A A A A A
_ _ _ _ _ _
```

**Comment by pixelzoom** [comment]
Keep in mind that we need to come up with a general algorithm for doing this.  If we get to hung up on aesthetics and special cases, this will be a real nightmare to implement and test.

For example, the general algorithm that I described above yields this arrangement:

8 A, 8B, 8C
```js
A   B   C
A   B   C
A   B   C
A   B   C
A A B B C C
A A B B C C 
_ _ _ _ _ _
```

Three piles of 4 items might be more aesthetically appealing:

8 A, 8B, 8C
```js
A A B B C C
A A B B C C
A A B B C C
A A B B C C 
_ _ _ _ _ _
```

... but is difficult to describe how to handle in a general way, and therefore difficult to implement.

**Comment by amanda-phet** [comment]
The implementation described in https://github.com/phetsims/equality-explorer/issues/4#issuecomment-316168850 is exactly what I had in mind. The only difference might be that it would look nice to distribute the different items if there is room, so in the case of 

6 A, 4 B, 6C
```js
A       C
A       C
A   B   C
A   B   C
A   B   C
A   B   C 
_ _ _ _ _ _
```

or 6A 4B
```js
A   
A   
A     B 
A     B 
A     B 
A     B 
_ _ _ _ _ _
```

The piles start more spaced out. However this is not necessary- it would just be nice to have the space.

**Comment by pixelzoom** [comment]
@amanda-phet Thanks, that's great. I'll start by implementing what I described, then see if I can add the horizontal "pile spacing" that you've described above.

**Comment by pixelzoom** [comment]
@kathy-phet @ariel-phet If you have any opinion on this, or had something in mind other than what @amanda-phet and I have agreed on --- now is the time to speak up.  This will be expensive to change.

**Comment by amanda-phet** [comment]
how soon are you implementing this? @kathy-phet is on vacation this week..

**Comment by kathy-phet** [comment]
I took a peak. It looks good, but just to confirm, this is on the "reorganize" button push, correct? Otherwise, the pieces just slot into the column where they were placed and can be disorganized, correct. So its not constantly shifting around.

**Comment by pixelzoom** [comment]
@amanda-phet: I hope to be implementing this within the next 2 weeks.

@kathy-phet: Correct.  My question was:
> I'd like to hear what you had in mind for how items on the scale should be rearranged when the "organize" button is pressed.

**Comment by ariel-phet** [comment]
The suggested approach seems logical and reasonable to me.

**Comment by kathy-phet** [comment]
OK -- yes, sounds good to me.

**Comment by pixelzoom** [comment]
The specification described in https://github.com/phetsims/equality-explorer/issues/4#issuecomment-316168850 is implemented in [1.0.0-dev.10](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.10/equality-explorer_en.html).  I verified all of the examples shown in https://github.com/phetsims/equality-explorer/issues/4#issuecomment-316168850.

@amanda-phet please review and let me know where you want to go from here.

**Comment by amanda-phet** [comment]
Looks like it's working well to me. What do you think about adding the horizontal pile spacing described in https://github.com/phetsims/equality-explorer/issues/4#issuecomment-316441119? It is not necessary, but I think a more distributed appearance would look nice on the plates.

**Comment by pixelzoom** [comment]
Rather than spacing the piles, how about centering the piles?  E.g.:

6A, 4B
```
    A   
    A   
    A B 
    A B 
    A B 
    A B 
_ _ _ _ _ _
```

6 A, 4B, 6C
```
  A   C
  A   C
  A B C
  A B C
  A B C
  A B C 
_ _ _ _ _ _
```

**Comment by amanda-phet** [comment]
I think that could work! And it sounds easier. Let's do that.

**Comment by pixelzoom** [comment]
@amanda-phet please review [1.0.0-dev.11](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.11/equality-explorer_en.html), which centers the items in the grid.  Run with `?showGrid` so you can see the grid.  

Important to note that, since this is a grid, it's not possible to ensure that the stacks are visually centered on the scale's weighing platform. When the number of empty columns in the grid is uneven, the algorithm currently puts the extra empty column to the right of the items.  For example, with 1 instance of each item, there will be 3 empty columns in the grid -- with 1 empty column to the left, 2 empty columns to the right, like this:

![screenshot_378](https://user-images.githubusercontent.com/3046552/30232411-309aaa00-94ad-11e7-9ed8-29218804d31f.png)

**Comment by pixelzoom** [comment]
[1.0.0-12](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.12/equality-explorer_en.html) contains fixes for a couple of non-obvious cases.

**Comment by pixelzoom** [comment]
After playing with this for a few days, there's one improvement that I might make to this algorithm. That is, to prefer "full columns" when possible.  

For example, for `?rightItems=16,7,8`, here's how the items are currently organized. Note how the 1's are arranged.

![screenshot_381](https://user-images.githubusercontent.com/3046552/30293275-2ee02d7a-96f6-11e7-9cb2-7abc8f3c2e6a.png)

Would it be easier to count if the 1's were arranged like this?

![screenshot_382](https://user-images.githubusercontent.com/3046552/30293326-578f3b1c-96f6-11e7-8685-aa240400dc59.png)

I'm not sure how difficult this would be to implement, and it will certainly complicate the implementation (which is already relatively complicated).  

@amanda-phet your thoughts?

**Comment by pixelzoom** [comment]
Here's another example, `?rightItems=26,8,0`.

Organized with current algorithm:

![screenshot_383](https://user-images.githubusercontent.com/3046552/30293574-47ef8030-96f7-11e7-8059-fc60dd93875a.png)

Would this be better? Easier to count?

![screenshot_384](https://user-images.githubusercontent.com/3046552/30293596-5839f7fe-96f7-11e7-806a-f57f4e84dfb3.png)

**Comment by amanda-phet** [comment]
We don't really need to be able to easily *count* objects, because they're counted in the equation, but we want them to be grouped so they mimic the equation. At quick glance, we want the information to correspond. If someone wants to rearrange into piles that suit them better they always can. 

I tried ?rightItems=16,7,12 and in this case, I definitely prefer the proposed solution. 
Current implementation:
![screen shot 2017-09-11 at 2 02 01 pm](https://user-images.githubusercontent.com/7852916/30294297-d91066d6-96f9-11e7-9976-6ef401787faf.png)

@pixelzoom proposal: 
![screen shot 2017-09-11 at 2 02 33 pm](https://user-images.githubusercontent.com/7852916/30294317-e87fc850-96f9-11e7-95ed-d5630b098877.png)

I guess it comes down to how difficult it will be. I don't mind the current implementation that much ,because as I said someone can always move the top few if they don't like it, and it's more for a scenario like this, where the information is difficult to parse, and we want to link the representations more easily:
![screen shot 2017-09-11 at 2 08 26 pm](https://user-images.githubusercontent.com/7852916/30294561-bd4b12b0-96fa-11e7-86e2-977bed40dbf5.png)

**Comment by amanda-phet** [comment]
In the case of ?rightItems=16,7,13, would the proposed organization have a different outcome than this? 
![screen shot 2017-09-11 at 2 11 02 pm](https://user-images.githubusercontent.com/7852916/30294648-11936d4a-96fb-11e7-834e-105eb715ba70.png)

**Comment by pixelzoom** [comment]
For `?rightItems=16,7,13`, the organization would be as you've shown in https://github.com/phetsims/equality-explorer/issues/4#issuecomment-328644586. That's the only way to keep items of the same type grouped together. 

I'll put in a little time to investigate "fill columns", as I proposed in https://github.com/phetsims/equality-explorer/issues/4#issuecomment-328636180.  If it turns out to be too difficult/complicated, then I'll punt.

**Comment by pixelzoom** [comment]
After about 1.5 hours, the "fill columns" approach proved to be very complicated, and I never could get it to work right.  In https://github.com/phetsims/equality-explorer/issues/4#issuecomment-328644088, @amanda-phet indicated that the current algorithm was sufficient. So I'm going to punt on "fill columns".

@amanda-phet let me know if there's anything else to do here.  Otherwise you can close this issue.
