### ISSUE TITLE
regression test after major changes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#40]
I recently made huge changes to just about everything in Equality Explorer. Before proceeding, I want to make sure that everything that is currently implemented is working properly.   That includes everything in the first 3 screens, with the exception of the "lock" feature.

On Slack, I asked @ariel-phet:
> EqEx update… I’ve lowered the house down onto the new foundation. Changes were huge, affecting just about everything, so high potential for problems to have been introduced.  I’d like to make sure thinks are stable before I proceed with implementing additional features. I’m doing extensive testing, but another pair of eyes would be helpful. Would Steele be available to do (max) 1 hour of sanity testing?

He replied:
> Yes, definitely

@phet-steele Please test the first 3 screens of [1.0.0-dev.64](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.64/phet/equality-explorer_en_phet.html).  For any problems found, create a GitHub issue, linked to this issue. Indicate whether the problem was present in [1.0.0-dev.63](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.63/phet/equality-explorer_en_phet.html). 1 hour max, testing doesn't need to be exhaustive. Thanks.

**Comment by pixelzoom** [comment]
@amanda-phet FYI. Feel free to have a look too.

**Comment by pixelzoom** [comment]
@phet-steele In case there are any query parameters that might make your testing easier (e.g. slow motion animation), see [EqualityExplorerQueryParameters](https://github.com/phetsims/equality-explorer/blob/master/js/common/EqualityExplorerQueryParameters.js).

**Comment by phet-steele** [comment]
@pixelzoom did what I could in ~one hour. Sim is sane.

**Comment by pixelzoom** [comment]
Thanks @phet-steele!  #41 is a good find that's apparently been there since the beginning.  Looks like I didn't create any new/obvious problems. So mission accomplished, and I'll proceed with new features.

Closing.
