### ISSUE TITLE
"Solving" and "Solve It!" screen names are too similar

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#43]
Consider renaming the "Solve It!" (game) screen. Having 2 screens with very similar names (Solving, Solve It!) is already proving to be confusing. 

Slack conversation with @amanda-phet:

```
Chris Malley [10:07 AM]
In almost every conversation I’ve had about the Solving or Solve It! screens, 
there has been confusion about which screen we’re talking about.  
So we might reconsider having names that are so similar.

Amanda McGarry [10:16 AM]
I agree, I have gotten confused myself.
```

**Comment by pixelzoom** [comment]
Another option is to rename the "Solving" screen.

**Comment by pixelzoom** [comment]
Another option is to rename the "Solving" screen.  @amanda-phet suggested renaming "Solving" to "Operations", since it introduces the universal operation.

**Comment by pixelzoom** [comment]
Raising priority. It's not zero cost to change these names. Every day that goes by is more code that I'll need to change -- I created another couple of dozen instances of these names in the code today.

**Comment by amanda-phet** [comment]
Let's rename "Solving" to "Operations." It seems to fit the flow better from previous screens.

**Comment by pixelzoom** [comment]
Before I do the work required to rename things in code, folders, etc....  Here's a dev version with the new "Operations" name, [1.0.0-dev.77](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.77/phet/equality-explorer_en_phet.html).  @amanda-phet are you happy with this in context?  Seems nice to me.

**Comment by pixelzoom** [comment]
Hmmm... Now that this screen is named "Operations", is the icon (which was designed to communicate "Solving") still appropriate?

**Comment by amanda-phet** [comment]
I am happy with it. Thanks for making the change!

**Comment by pixelzoom** [comment]
Reopening.  I haven't changed anything other than the string yet.

**Comment by pixelzoom** [comment]
Code changes completed. Closing.

**Comment by pixelzoom** [comment]
Reopening.  It looks like no changes have been made to the design document.  At the very least, the "Solving" screen section should be renamed to "Operations", and a reference to this issue should be added to the document.  Assigning to @amanda-phet.

**Comment by amanda-phet** [comment]
I updated the name of this section of the design doc (and as many instances as I could find), and linked to this issue.
