### ISSUE TITLE
universal operations: add support for operands that are variable terms

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#45]
Summary of discussion with @amanda-phet about this feature that was proposed by @kathy-phet.

The universal operation control currently supports 4 operators (`+,−,×,÷`) , and integer operands in the range `[-10,10]`.   Universal operations are applied to terms on both sides of the scale. If there is no variable term on the scale, there is currently no way to create one on the scale using a universal operation.

The change request is to support operations with the `+` and `-` operators and operands that are variable terms.  The variable terms would have integer coefficients in the range `[-10,10]`, excluding zero -- i.e. `-10x,-9x,...,-x, x,..., 9x, 10x`.  Example operations: `+ 10x`, `+ -5x`, `− 5x`, `− -2x`.

The primary value of this change is in the game screen. It would allow us to include challenges that have variable terms on both sides of the equations.  There is little (no?) additional value for the Solving screen, but the control should be consistent in all screens.

Two challenges:

(1) Redesign the UI control so that an already-complex control doesn't become incomprehensible. 

(2) Implement support for operands that are constant or variable terms. This will be a full rewrite of the universal operation implementation.  No time estimate until this feature request gets more specific.

**Comment by pixelzoom** [comment]
The UX proposal that @amanda-phet described for me involves having the operators `[ +,−]` appear twice in the operator picker, with visual cues to indicate that one pair is applicable to constant terms and one pair is applicable to variable terms. Imo, that proposal has numerous problems, mostly relate to the duplication of operators − difficult to design effective visual cues, potentially confusing to students, difficult to describe (in specifications, classroom, teaching materials,..), difficult to instrument for a11y, complicated implementation that reflects the confusing UX, ...

Here's another UX proposal:

Operator picker with one instance of each of these operators, in this order. Default is `+`.  This is unchanged from the current implementation.
`[ +,−,×,÷ ]`

Operand picker with these constant and variable terms, in this order.  Default is `1`.
`-10x, -10, -9x, -9, ..., -2x, -2, -x, -1, 0, 1, x, 2, 2x, ..., 9, 9x, 10, 10x`

For operators `[+,−]`, the full set of operands (all constants and variable terms) is available.
For operator `×`, only the operands that are constants are available.
For operator `÷ `, only the operands that are _non-zero_ constants are available.

When switching from `[+,−]` to `[×,÷]` with a variable term operand selected, the operand changes to the constant with the same coefficient as the variable term.  E.g. if operand `10x` is selected, and you change the operator from `+` to `×`, then the operand changes to `10`.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/issues/357#issuecomment-372474105, @amanda-phet said:

Thanks @pixelzoom this is a really good summary.

I'd like to discuss the implications and timeline with @kathy-phet a bit. It sounds like this could push out the deadline for publishing this sim by at least a week, and we should weigh that with the benefits of having the sim published in time for our presentation at ISTE (already a tight timeline).

I'd also like to wait until after interviews to decide on if we make this change because there's a chance that the component as-is (pickers with operator and operand) will be difficult for students to interpret, so if they need to be re-designed I'd want to do that before making such a costly change. However, @pixelzoom mentioned that this should not be a 1.1 feature as it will take many times longer to accomplish at a future date than it would to do now, so if we do it, it should be in the next month.

**Comment by kathy-phet** [comment]
> Operand picker with these constant and variable terms, in this order. Default is 1.
> -10x, -10, -9x, -9, ..., -2x, -2, -x, -1, 0, 1, x, 2, 2x, ..., 9, 9x, 10, 10x

I think this could be conceptually confusing for the students. When you are working through deciding next steps, you typically want to separate ideas of working with the x terms from working with the constant term. So I would think the original suggestion would do a better job of having students focus on which of those operations they were trying to do at that time.

**Comment by kathy-phet** [comment]
> The primary value of this change is in the game screen. It would allow us to include challenges that have variable terms on both sides of the equations. There is little (no?) additional value for the Solving screen, but the control should be consistent in all screens.

I was thinking that there was equal value to having this in the "Solving" screen, as it enables addressing this goal, and affirms for students that the types of actions they are doing apply equally to the variable terms as they do to the constants.

**Comment by pixelzoom** [comment]
@kathy-phet What's your proposal for addressing the challenges identified in https://github.com/phetsims/equality-explorer/issues/45#issuecomment-372477647? 
> ... difficult to design effective visual cues, potentially confusing to students, difficult to describe (in specifications, classroom, teaching materials,..), difficult to instrument for a11y, complicated implementation that reflects the confusing UX, ...

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/equality-explorer/issues/45#issuecomment-372481076
> ... affirms for students that the types of actions they are doing apply equally to the variable terms as they do to the constants.

If that's the goal, then why do you need 2 sets of the same operators? Having a single instance of each operator and showing that it can be applied to both constant and variable terms seems to be exactly what you're describing.

**Comment by kathy-phet** [comment]
> The UX proposal that @amanda-phet described for me involves having the operators [ +,−] appear twice in the operator picker, with visual cues to indicate that one pair is applicable to constant terms and one pair is applicable to variable terms. Imo, that proposal has numerous problems, mostly relate to the duplication of operators − difficult to design effective visual cues, potentially confusing to students, difficult to describe (in specifications, classroom, teaching materials,..), difficult to instrument for a11y, complicated implementation that reflects the confusing UX, ...

I think this would be addressable in the descriptive text. You will need to be describing the change in the operator as is, so I think it could be a simple "add an integer term" vs "add an x term". or subtract similarly. But we can have a side conversation with Taliesin to see if she sees something complex that would make it harder than I'm thinking.

**Comment by kathy-phet** [comment]
> If that's the goal, then why do you need 2 sets of the same operators? Having a single instance of each operator and showing that it can be applied to both constant and variable terms seems to be exactly what you're describing.

That's not really how I think about it, but I'm happy to discuss at an upcoming design meeting. I also think it could be annoying/confusing to have to push up twice to move from -10 to -9.

**Comment by pixelzoom** [comment]
Labeling with high priority, since this sim is supposed to be "feature complete" by March 26.

**Comment by pixelzoom** [comment]
3/15/18 design meeting:
Add halo whenever like terms will combine, not just for when they will sum to zero.

**Comment by pixelzoom** [comment]
3/15/18 design meeting consensus:
• reimplement universal operation to use terms for operand, so I don't run into issues when implementing lock feature
•  try this proposal for UX first: https://github.com/phetsims/equality-explorer/issues/45#issuecomment-372477647

**Comment by pixelzoom** [comment]
@amanda-phet Please see [1.0.0-dev.71](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.71/phet/equality-explorer_en_phet.html). This is a very quick-&-dirty implementation of variable term operands.  (The code is now littered with "TODO" items for things that I need to address.)

This version does not skip over operations that are invalid -- i.e., divide by 0, multiply and divide by variable terms.  We can't use NumberPicker for the operand, and the more general ObjectPicker currently has no support for skipping choices.  So just ignore the invalid operations of now, and use this dev version to give you a feel for adding and subtracting both constant and variable terms.  

Note that order of operands is flexible, but it's currently:

`-10, -10x, -9, -9x, ..., -2, -2x, -1, -x, 0, 1, x, 2, 2x, ..., 9, 9x, 10, 10x`

... and the picker wraps around.

**Comment by pixelzoom** [comment]
@amanda-phet Please use [1.0.0-dev.72](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.72/phet/equality-explorer_en_phet.html). The previous dev version wasn't ignoring all of the invalid operations, and could crash in some situations.

**Comment by amanda-phet** [comment]
The order of the operands works for me. However the starting value should still be 1 (currently -10). I'm not sure I like the picker wrapping around. It's not that hard to get from one end to the other by just clicking and holding, and it is a little confusing for me when dealing with numerals, because I expect negatives to be at the "bottom" and positives to be at the "top" of the picker.

**Comment by kathy-phet** [comment]
I agree, not wrapping around on the value pickers. And I agree with starting value of 1. 

I think it is great to be able to do this action of adding/subtracting x values too.

**Comment by pixelzoom** [comment]
Change requests implemented. In [1.0.0-dev.73](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.73/phet/equality-explorer_en_phet.html), the operand picker defaults to 1 and does not wrap around.

**Comment by pixelzoom** [comment]
Slack with @amanda-phet:

Chris Malley [6:17 PM]
Re https://github.com/phetsims/equality-explorer/issues/45 …. Should I continue making this UX robust? (avoiding divide-by-zero, hiding variable terms when operator is times or divide, etc.)

Support for variable terms is now complete in the model.  But there’s significant work to be done on pickers in order to support this.

Amanda McGarry [6:22 PM]
Yes, I'm really happy with how it's working! Please do continue.

Chris Malley [6:22 PM]
OK.

**Comment by pixelzoom** [comment]
[1.0.0-dev.78](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.78/phet/equality-explorer_en_phet.html) supports skipping operands that are not appropriate for the operator.  It still has problems at the min/max of the operand range, which will require some major work on pickers. (E.g. If you have '× 10' selected, you're still able to change the operand picker to get to '× 10x'.) 

My main concern is that we may not all be "on the same page" about this UX, and I'm proceeding down an expensive path.  What I've implemented here is one of multiple UX proposals for this feature. @amanda-phet likes this UX. I feel like this UX a bit awkward, but probably the "lesser of evils".  @kathy-phet's feedback in https://github.com/phetsims/equality-explorer/issues/45#issuecomment-374753977 doesn't make it clear whether this UX is the way to go, or whether she'd like to see her proposal.  I'd also like @ariel-phet to weigh in.

**Comment by amanda-phet** [comment]
I agree that the UX is a bit awkward, but I think a special +/- would probably be more awkward to find the correct one that you want at a given time. Interviews will be important for this feature.

**Comment by ariel-phet** [comment]
I generally agree this is the best suggestion we have thus far. I am guessing it will be a bit of cognitive work to get used to the interface the first time, but I do think it is a logical interaction.

 When starting with a certain value and switching to a disallowed operation (such as having "0" and then changing to "divide" and seeing the value switch to "1"), the interaction is a bit surprising, but again seems like the best solution. 

I might tweak the color/prominence of the "apply" button to make it pop a bit more, but generally this UX seems like a reasonable compromise to get to the goals. I could think of a potentially more transparent UX, but I think it would involve designing new UI components, and that just does not seem worth the effort if interviews reveal this is an acceptable way to go.

**Comment by pixelzoom** [comment]
@ariel-phet said:
> I might tweak the color/prominence of the "apply" button to make it pop a bit more, 

The 'go' button was originally the standard PhET yellow. See for example [1.0.0-dev.60](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.60/phet/equality-explorer_en_phet.html?initialScreen=4). On 2/1/18, @amanda-phet requested that it be changed to white.

**Comment by pixelzoom** [comment]
@ariel-phet said:
> I might tweak the color/prominence of the "apply" button to make it pop a bit more, ...

The 'go' button was originally the standard PhET yellow. See for example [1.0.0-dev.60](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.60/phet/equality-explorer_en_phet.html?initialScreen=4), screenshot below. On 2/1/18, @amanda-phet requested that it be changed to white.

![screenshot_517](https://user-images.githubusercontent.com/3046552/37868402-4f77a604-2f6b-11e8-8a3a-ab91ca10dfef.png)

**Comment by pixelzoom** [comment]
[1.0.0-dev.80](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.80/phet/equality-explorer_en_phet.html) fixes the remaining issues with the pickers.  

There are 2 outstanding issues, @amanda-phet please advise:

(1) Prominences of the "go" button, see https://github.com/phetsims/equality-explorer/issues/45#issuecomment-375920597.

(2) Order of the operands.   

The current order is:
`-10, -10x, -9, -9x, ..., -2, -2x, -1, -x, 0, 1, x, 2, 2x, ..., 9, 9x, 10, 10x`
About this order, @amanda-phet said "order of the operands works for me" in https://github.com/phetsims/equality-explorer/issues/45#issuecomment-374750772.  But there's a subtle lack of symmetry with this order. Starting at 1, as you go 'up', you encounter constant terms before variable terms (e.g. 2 before 2x).  As you go down, you encounter variable terms before contacts terms (e.g. -2x before 2).  This feels especially awkward to me around `0`, i.e. `-1, -x, 0, 1, x`.

The order that I proposed in https://github.com/phetsims/equality-explorer/issues/45#issuecomment-372477647 is more symmetric, "mirror image" around '0': 
`-10x, -10, -9x, -9, ..., -2x, -2, -x, -1, 0, 1, x, 2, 2x, ..., 9, 9x, 10, 10x`
Starting at 1, regardless of whether you go 'up' or 'down', you encounter constant terms before variable terms.  (e.g 2 before 2x, and -2 before -2x).  This feels more predictable around `0`, i.e. `-x, -1, 0, 1, x`.

**Comment by amanda-phet** [comment]
(1) I did design the button to be white because I prefer the appearance, but I'm fine with changing it to yellow or some other prominent color. We could also wait for an interview, but again I'm fine with changing it. @pixelzoom go ahead and make it yellow (to match the erase button yellow). 

(2) Thank you for clarifying. I didn't realize the order didn't match the original specification, and was only referring to the 1, x, 2, 2x, order vs. 1, 2, ..., x, 2x. The order you proposed is the order I would also like to see
`-10x, -10, -9x, -9, ..., -2x, -2, -x, -1, 0, 1, x, 2, 2x, ..., 9, 9x, 10, 10x`

**Comment by pixelzoom** [comment]
[1.0.0-dev.81](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.81/phet/equality-explorer_en_phet.html) has a yellow 'go' button and orders the operands as in https://github.com/phetsims/equality-explorer/issues/45#issuecomment-376324038.

@amanda-phet Any other changes, or can we close this issue?

**Comment by amanda-phet** [comment]
Yes we can close this.
