### ISSUE TITLE
Halos should appear whenever a combination can occur

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#46]
In Equality Explorer, halos are used to:

- show that two terms will combine to zero.

In Expression Exchange (where the halos came from), they are used to:

- show that two terms will combine.....not necessarily to zero.

The Expression Exchange version makes much more sense to me, it shows a halo every time like/inverse terms overlap and can be combined. With Equality Explorer, the only case that has needed halos was when two inverse terms would combine to zero, the "sum to zero" feature. However, this does not make sense to me on the Solving screen.

This screen allows users to combine terms WHENEVER they want, but you only see a halo when they would combine to zero? So:

-x + x -> 0; gets a halo
-x + -x -> -2x; does not get a halo. Why?

The second scenario makes less sense to me. I'd expect the halo to signal that two terms can be combined regardless of what they sum to, like Expression Exchange.

@amanda-phet @pixelzoom what say you?

**Comment by pixelzoom** [comment]
@phet-steele you'll have to discuss this one with @amanda-phet.  I implemented what was requested. Adding halos whenever 2 like terms overlap (regardless of their sum) will take 1-3 hours.

**Comment by pixelzoom** [comment]
Labeling with high priority, since this sim is supposed to be "feature complete" by March 26.

**Comment by pixelzoom** [comment]
3/15/18 design meeting:
Add halo whenever like terms will combine, not just for when they will sum to zero.

**Comment by pixelzoom** [comment]
Implemented in [1.0.0-dev.70](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.70/phet/equality-explorer_en_phet.html).

@amanda-phet @phet-steele please verify.

**Comment by amanda-phet** [comment]
Verified. Looks good to me!

**Comment by pixelzoom** [comment]
@phet-steele feel free to have a look, then close if all is well.

**Comment by phet-steele** [comment]
I like it. Thanks @amanda-phet and @pixelzoom.

**Comment by phet-steele** [comment]
oooooooooh but if I'm to be pedantic, then this function's error (in `Term.js`) should say "isInverseTerm", @pixelzoom. 

```js
 isInverseTerm: function( term ) {
      throw new Error( 'isInverseOf must be implemented by subtype' );
    }
```

**Comment by pixelzoom** [comment]
Good catch. This change required a new function, `isLikeTerm`.  I renamed `isInverseOf` to `isInverseTerm` for symmetry, but neglected to change the Error message.  Fixed in the above commit. Closing.
