### ISSUE TITLE
can't "undo" operations because of precision errors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#49]
In https://github.com/phetsims/equality-explorer/issues/48#issuecomment-373513075, @amanda-phet said:

> So this seems like the scenario I was describing before. If you try to divide by 10 to "undo" all of your previous operations, you can't get back to 1 because of the rounding.

Please provide specific steps that reproduce the problem.

**Comment by amanda-phet** [comment]
If you multiply by 10 (37 times), then divide by 10 (22 times), you will see weird behavior, like this fraction:
![screen shot 2018-03-20 at 2 02 13 pm](https://user-images.githubusercontent.com/7852916/37680071-6c05bab6-2c48-11e8-8cdd-cb49d11c4395.png)

If you continue (I don't remember how many times I did it in this video), you can get back to 1, but the journey isn't pretty, and mathematically doesn't seem correct:

![eqex](https://user-images.githubusercontent.com/7852916/37679963-1bcdd22c-2c48-11e8-9299-8a29b531b72b.gif)

I have not yet found the case of not being able to get back to 1. Should I keep trying, or will the limit I suggested in https://github.com/phetsims/equality-explorer/issues/48#issuecomment-374719522 take care of the rounding issues?

**Comment by pixelzoom** [comment]
The limit you've proposed in https://github.com/phetsims/equality-explorer/issues/48#issuecomment-374719522 is 1E16.  If you haven't been able to reproduce the problem with numbers below that limit (and don't want to continue trying), then feel free to close.  We can reopen if it's reproducible in the future.
