### ISSUE TITLE
emphasize the relational operator in equations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#5]
The relational operator (>, <, =) is important in this sim.  @amanda-phet and I noticed that it's a bit "lost" in equations.   

Related design questions:

(1) How can we emphasize the relational operator?

(2) Should the relational operator be emphasized in both the "Equation or Inequality" and "Snapshots" panels?

(3) Would it help to keep the relational operator centered in the "Equation or Inequality" panel? (The entire equation is currently centered, so the relational operator moves around.)

**Comment by pixelzoom** [comment]
@amanda-phet please review the "Basics" screen in [1.0.0-dev.8](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.8/equality-explorer_en.html).  

Changes include:
(1) The relational operator remains centered in the "content area" of the accordion box.
(2) The relational operator uses a larger, bold font for emphasis.
(3) The equation (EquationNode) has the following options and default values:

```js
// fonts
relationalOperatorFont: new PhetFont( { size: 50, weight: 'bold' } ), // for relational operator
plusFont: new PhetFont( 24 ), // for plus operator
numberFont: new PhetFont( 24 ), // for coefficients and constants

// horizontal spacing
relationalOperatorSpacing: 25, // space around the relational operator
plusSpacing: 8, // space around plus operator
coefficientSpacing: 2 // space between coefficient and icon
```

Does this address the issue? Do you want to change any of the defaults?

**Comment by amanda-phet** [comment]
(1) I really like how it is centered
(2) It might be too large the way it is.. it dwarfs the 0s at startup. However it seems balanced with the fruits. 

Can we increase the size of the equation text, or decrease the size of the fruits? Maybe something comparable to these proportions:
<img width="427" alt="screen shot 2017-09-01 at 12 53 39 pm" src="https://user-images.githubusercontent.com/7852916/29983800-bab11ab0-8f14-11e7-9ae4-24908b5a3085.png">

or here, with a larger and bold inequality symbol, and a little extra space around the symbol:
<img width="429" alt="screen shot 2017-09-01 at 12 57 16 pm" src="https://user-images.githubusercontent.com/7852916/29983903-1e7e6df4-8f15-11e7-8814-251dd0c7adab.png">

**Comment by pixelzoom** [comment]
@amanda-phet said:

> ... fruits ...

You should look at the "polygons" and "spheres" scenes, because "fruits" is not worst case (has only 2 icons that appear in equation).

> It might be too large the way it is.. it dwarfs the 0s at startup. However it seems balanced with the fruits.

I noticed this too.  But as the equation gets "noisier" (more terms, more icons) it does look OK.  So I think this will involve a compromise.

> Can we increase the size of the equation text,  ...

Please clarify. Are you requesting identical font size for _all_ text elements? (numbers, operators) If we make the coefficients/constants larger, we'll need to make the accordion box a bit wider.  The worst case is 3 terms on each side of the equation, with each term having a double-digit coefficient and icon.  

> ... or decrease the size of the fruits?

I can certainly decrease the size of item icons. But I want to verify that you've consider whether the items in the equation should be the same size as they are in the play area. Earlier versions had smaller items in the equation, but I thought it looked a little odd.  For example, compare [1.0.0-dev.7](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.7/equality-explorer_en.html) (smaller items) and [1.0.0-dev.8](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.8/equality-explorer_en.html) (same size items).  If we do decrease the size of the items, that will need to be done uniformly for _all_ items, in _all_ scenes.

**Comment by pixelzoom** [comment]
Here's a "worst case" example with bold relational operator, larger coefficients/constants, and item icons that are the same size as in the play area.  Note that the accordion box is significantly wider. 

![screenshot_371](https://user-images.githubusercontent.com/3046552/29984992-4a6ebdd8-8f1a-11e7-90af-b759e702b0cd.png)

Here's how it looks for "0 = 0":

![screenshot_372](https://user-images.githubusercontent.com/3046552/29985009-624519ac-8f1a-11e7-9c3b-f5a8f4f6d125.png)

**Comment by pixelzoom** [comment]
EquationNode options for the above example are:

```js
// fonts
relationalOperatorFont: new PhetFont( { size: 50, weight: 'bold' } ), // for relational operator
plusFont: new PhetFont( 32 ), // for plus operator
numberFont: new PhetFont( 32 ), // for coefficients and constants

// horizontal spacing
relationalOperatorSpacing: 20, // space around the relational operator
plusSpacing: 8, // space around plus operator
coefficientSpacing: 2 // space between coefficient and icon
```

... so increased font size for '+' and numbers, less space around relational operator.

**Comment by amanda-phet** [comment]
I definitely prefer the larger font for coefficients and operations. It looks more balanced to me. 

I was never bothered by the objects in the equation box being smaller than those in the play area since they aren't interactive and are representative of the play area, so I still think I'd prefer to see everything (at this point) scaled down to make the panel smaller overall. 

Thanks for making these tweaks. Happy to hear others weigh in as well.

**Comment by pixelzoom** [comment]
@amanda-phet please have a look at [1.0.0-dev.9](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.9/equality-explorer_en.html), which includes the following changes to the equation:

• item icons are scaled by 75%
• reduce font size from 32 to 28 for numbers and '+'
• reduce font size from 50 to 40 for relational operator
• "worst case" screenshot shown below

Note that a wide accordion box is still required. It could be a bit narrower, but it's still going to be much wider than shown in the design doc. Fortunately, we have the horizontal space available.

So... Do you think we've addressed the the issue of how to emphasize the relational operator?  If so... I'm happy to make further tweaks, but perhaps we can close this issue and address font sizes, spacing, etc. when we get to the pixel-polishing phase of implementation.

![screenshot_373](https://user-images.githubusercontent.com/3046552/29985818-da884fee-8f1d-11e7-87a1-5f4cb837193b.png)

**Comment by amanda-phet** [comment]
I compared in each scene and like this a lot. When we get to the other scenes that include x I think these sizes will hold up well, but I agree we should probably not spend too much time on this at the moment. Since we addressed emphasizing the relational operator I'll close the issue. Thanks!
