### ISSUE TITLE
translation of "x = ?" check box label

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#50]
In screens that have variable terms, the Snapshots accordion box has a check box with label "_x_ = ?".  

E.g. in the Variables screen:

![screenshot_516](https://user-images.githubusercontent.com/3046552/37794708-e9590b2c-2dd7-11e8-9f4d-075a46718c07.png)

Normally I'd just put `"x {{equals}} ?"` in the translated strings file, let the translator handle the whole label, and fill in the "=" symbol programmatically.  But because the "x" and "= ?" use different fonts, this label is currently implemented as 2 Text nodes (which requires 2 separate strings), and the "x" and "?" are translated as separate strings. The downside of this is that the translator has no control over ordering.   But that may be OK, since there's also no control of the layout of the "x =" picker that appears directly below it.

@amanda-phet Your thoughts? Is this fine as is, or does the translator need complete control over `"x = ?"`.

**Comment by amanda-phet** [comment]
I don't see why they would need complete control over "x=?". However I have some questions about "x" and "?" being translatable at all.

**Comment by pixelzoom** [comment]
> However I have some questions about "x" and "?" being translatable at all.

In all sims to date, I have been asked to make variable symbols translatable. E.g. 'x' and 'y' are translatable in Graphing Lines and Function Builder.  I see similar precedent in Curve Fitting, Least Squares Regression and Trig Tour.  My understanding is that while math symbols (+, -, =,...) are universal, variable symbols are not.   If that is for some reason different for Equality Explorer, let me know.

"?" is not universal -- it needs to be translatable. For example, the Greek equivalent looks like ";".  And in RTL languages, it's "⸮".

**Comment by pixelzoom** [comment]
> However I have some questions about "x" and "?" being translatable at all.

In all sims to date, I have been asked to make variable symbols translatable. E.g. 'x' and 'y' are translatable in Graphing Lines and Function Builder.  I see similar precedent in Curve Fitting, Least Squares Regression and Trig Tour.  My understanding is that while math symbols (+, -, =,...) are universal, variable symbols are not.   If that is for some reason different for Equality Explorer, let me know.

"?" is not universal -- it needs to be translatable. For example, the Greek equivalent looks like ";",  and in Arabic it's "⸮".  Reference: https://www.quora.com/Which-symbols-are-used-as-a-question-mark-in-languages-other-than-English

**Comment by pixelzoom** [comment]
In Slack chat with @amanda-phet:

Translation of "?" is required.  Punctuation is not universal.

The general issue of whether variable glyphs (e.g. 'x', 'y') should be translatable was moved to https://github.com/phetsims/rosetta/issues/183.

There is no need to provide support for ordering of the equation.  And that would be undesirable since layout is LTR throughout PhET sims, with no general ability to adapt to RTL.

No changes are necessary for this sim, at this time.  

Closing.
