### ISSUE TITLE
design level-selection icons for game

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#51]
As the result of https://github.com/phetsims/equality-explorer/issues/45, we now have 4 levels in the game.  Applying the same design used for 3 levels, the mockup currently looks like this:

![screenshot_523](https://user-images.githubusercontent.com/3046552/37985359-c3c1f388-31b5-11e8-9ca4-b36ed82c4060.png)

Slack discussion about changing the design direction for these buttons:

Amanda McGarry [11:23 AM]
I’m not sure about the gradient for the button colors now that there are 4 levels, so I should play around with that a bit

Chris Malley [11:27 AM]
Yeah, getting a little dark.  Also getting a little “mathy”.   Do you think anyone will really look at the equations on the buttons to generalize the type of problem for each level?  Or would something fun on each button (ala Graphing Lines) be more appropriate?
Should probably have the level number on each button too?
… since level number will be displayed on status bar.

Amanda McGarry [11:29 AM]
Right, now that there are 4 I feel like everything has changed. Definitely need to include the level numbers now (I didn’t feel as strongly before because 3 is an easier number I guess)
We could have the scales be tipped more and more, but they are always balanced in the actual challenges so that could be misleading too

**Comment by amanda-phet** [comment]
Here's an idea: we can label the levels with a variable term (although we don't typically show  the coefficient of 1, I would here). 

<img width="681" alt="image" src="https://user-images.githubusercontent.com/7852916/37987393-5111eb8a-31bb-11e8-9a48-e6a9083fcb12.png">

**Comment by pixelzoom** [comment]
I kind of like that idea - simple, effective.

**Comment by pixelzoom** [comment]
I also like the placement of the Info button, to the right of "Choose Your Level".   Good use of proximity.

**Comment by pixelzoom** [comment]
Discussed at 3/29/18 design meeting. Everyone like the icons shown in https://github.com/phetsims/equality-explorer/issues/51#issuecomment-376629920.

**Comment by pixelzoom** [comment]
@amanda-phet The design document needs to be updated to reflect the decision in https://github.com/phetsims/equality-explorer/issues/51#issuecomment-376629920.  I went to the design document, and got confused.

**Comment by pixelzoom** [comment]
Level-selection buttons are implemented in [1.0.0-dev.87](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.87/phet/equality-explorer_en_phet.html).  Screenshot below. They currently don't do anything.  Note that they are using the standard common-code, which does not provide the extreme shading shown in the mockups. 

@amanda-phet please verify.

![screenshot_541](https://user-images.githubusercontent.com/3046552/38277916-5abf08f6-3757-11e8-8422-80cd1f5b0775.png)

**Comment by amanda-phet** [comment]
The "extreme shading" is an approximation we have made in illustrator to get close to matching sims. This screen is looking good to me. Can this be closed?
