### ISSUE TITLE
add an "Info" button to level-selection screen for game?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#52]
This is related to #51, where we are moving away from having "representative equations" on the level-selection buttons.

Should we include an "Info" button on the game's level-selection screen, ala Make A Ten?   The purpose would be to describe the levels.  

Related Slack discussion:

Amanda McGarry [11:30 AM]
We could include an “info” button like we do in Make a Ten (although I’d liek to use an i with a circle for info not a question mark) to describe the types of equations for teachers
and then have fun icons instead of sample equations

Chris Malley [11:31 AM]
info button?

Amanda McGarry [11:31 AM]
Yeah, the game screen of make a ten has a small info button that describes the skills addressed in each level
to help teachers differentiate or focus on a particular skill

Chris Malley [11:31 AM]
Oh… The ‘?’ button in upper right of level selection screen.

Amanda McGarry [11:32 AM]
yes
It should really be an (i)

Chris Malley [11:32 AM]
Yes. There’s an international symbol for a reason :)

Amanda McGarry [11:32 AM]
https://fontawesome.com/icons/info-circle?style=light

Chris Malley [11:32 AM]
The placement is also awkward.

Amanda McGarry [11:33 AM]
oh really? do you think it should be at the bottom with other buttons?
Anyway, is that ok with you to do something similar here for teachers?
since each level can very easily be described
I think it would be really useful

**Comment by amanda-phet** [comment]
This is what I have in mind for the level info:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/7852916/37987716-2fb52f50-31bc-11e8-82cf-4b5cff198838.png">


As for the placement of the button, I don't have any particular leanings. It could go right after "Choose your level", or it could go somewhere at the bottom near other buttons.

**Comment by pixelzoom** [comment]
@amanda-phet In the Info dialog, will you want to show a "representative equation" for each level, like we previously had on the level-selection buttons?  Since we have no common-code support for equations, I need to plan in advance if you want this (or might want this).

**Comment by pixelzoom** [comment]
As I said in https://github.com/phetsims/equality-explorer/issues/51#issuecomment-376636021:
> I also like the placement of the Info button right after "Choose Your Level". Good use of proximity.

**Comment by amanda-phet** [comment]
>will you want to show a "representative equation" for each level, like we previously had on the level-selection buttons?

That won't be necessary. The descriptions here are understood by teachers. Students can play the level, and click refresh, to see the types of challenges that are on each level.

**Comment by pixelzoom** [comment]
3/29/18 design meeting:

Everyone liked having the Info button.

Noted that the same (similar?) descriptions of each level appear in the Status Bar.  @amanda-phet If possible, let's try to make the text the same, to reduce translation requirements.

**Comment by amanda-phet** [comment]
Update to the level descriptions: These are the strings I would like to use in both this dialog and the status bar for games.

![image](https://user-images.githubusercontent.com/7852916/38111820-568bd49c-335d-11e8-84a4-7a9110d723a6.png)

I also like this appearance where the level text is left aligned, and the level descriptions are left-aligned. No colon needed.

**Comment by pixelzoom** [comment]
@amanda-phet From the above comment, it sounds like you're assuming that (e.g.) "Level 1" and  "One-step equations" are separate text.  I can certainly do that.   But it's not going to be very friendly for RTL languages.   What I suggest we do is make "Level 1 One-step equations" one piece of text, with markup to make the "Level 1" bold.  That will result in the same alignment that you specified, but still support RTL languages.  Does that sound acceptable?

**Comment by pixelzoom** [comment]
Info button and associated dialog are implemented in [1.0.0-dev.87](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.87/phet/equality-explorer_en_phet.html).  Screenshot shown below. @amanda-phet please review.

FYI, it's currently impossible to put the "Levels" title at the very top of the dialog.  It's yet-another problem with Dialog common code, see https://github.com/phetsims/joist/issues/477.

![screenshot_540](https://user-images.githubusercontent.com/3046552/38277837-0cda33ae-3757-11e8-9cb5-db141d4fd884.png)

**Comment by amanda-phet** [comment]
The title is fine. Once we have a more robust common code dialog, will we go back to sims with dialogs and update them with the new dialog? (just curious).

One minor change: please make level 3 say "Multi-step equations with fractions"

**Comment by pixelzoom** [comment]
@amanda-phet asked:
> Once we have a more robust common code dialog, will we go back to sims with dialogs and update them with the new dialog? (just curious).

Ideally yes.  But "when" is up to @ariel-phet and @kathy-phet.

> One minor change: please make level 3 say "Multi-step equations with fractions"

Dones.

Closing.
