### ISSUE TITLE
informal dev test

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#53]
Equality Explorer has undergone massive changes over the past several weeks, all for the better.  It would good to have @phet-steele spend an hour or two testing.  No need for a test matrix, or coverage on all platforms - one desktop and a little bit of iPad would be great.  FYI, I've tested it mostly on macOS+Chrome and iPad.

Latest dev version:
https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.86/phet/equality-explorer_en_phet.html

Things to skip, because they're not implemented:
• the "lock" feature
• the entire "Solve It!" screen

Please reference this issue in any issues that you create. Thanks!

@amanda-phet FYI.

**Comment by phet-steele** [comment]
Done.

**Comment by pixelzoom** [comment]
Reopening until I've addressed all the issues.  Reassigning to me.

**Comment by pixelzoom** [comment]
There's one related that's still open, and it's going to require @jonathanolson's assistance, so closing this issue.

@phet-steele Thank you for your quick and thorough testing.
