### ISSUE TITLE
Error when overlapping two non-constant non-variable items

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#54]
On the basics screen, attempt to "combine" two like objects (release one while overlapping another). The below error is thrown.

Note I only get this error when overlapping non-constant non-variable items: apples, animals, shapes, etc.

Combining constant and variable terms is functioning correctly on all screens.

```
Uncaught TypeError: term.plus is not a function
    at end (TermDragListener.js?bust=1522692790791:108)
    at TermDragListener.endDrag (SimpleDragHandler.js?bust=1522692790791:221)
    at Object.up (SimpleDragHandler.js?bust=1522692790791:98)
    at Input.dispatchToListeners (Input.js?bust=1522692790791:901)
    at Input.dispatchEvent (Input.js?bust=1522692790791:871)
    at Input.upEvent (Input.js?bust=1522692790791:720)
    at Input.mouseUp (Input.js?bust=1522692790791:365)
    at Input.pointerUp (Input.js?bust=1522692790791:648)
    at BatchedDOMEvent.run (BatchedDOMEvent.js?bust=1522692790791:57)
    at Input.fireBatchedEvents (Input.js?bust=1522692790791:218)
```

Seen on macOS 10.13.3 Chrome. For #53.

<details>
<summary>Troubleshooting Information</summary>

URL: https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.86/phet/equality-explorer_en_phet.html
Version: 1.0.0-dev.86 2018-04-01 20:11:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"ceb3cc00","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"0f5df428","branch":"master"},"dot":{"sha":"b84c47a5","branch":"master"},"equality-explorer":{"sha":"e5eb7289","branch":"master"},"joist":{"sha":"47db3692","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"d8804eee","branch":"master"},"phet-io":{"sha":"4bbddfaa","branch":"master"},"phet-io-website":{"sha":"397862e0","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"1ecd81a1","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b1c5562c","branch":"master"},"phet-io-wrappers":{"sha":"025cc23d","branch":"master"},"phetcommon":{"sha":"aa928d57","branch":"master"},"query-string-machine":{"sha":"c379f1db","branch":"master"},"scenery":{"sha":"c8bc9dd9","branch":"master"},"scenery-phet":{"sha":"97723fc7","branch":"master"},"sherpa":{"sha":"9c6ec322","branch":"master"},"sun":{"sha":"bb49c2d0","branch":"master"},"tandem":{"sha":"f8147666","branch":"master"},"twixt":{"sha":"b2de1f74","branch":"master"},"vegas":{"sha":"b8ade2ab","branch":"master"},"vibe":{"sha":"2dc20be7","branch":"master"}}
</details>

**Comment by pixelzoom** [comment]
On end drag, if two overlapping terms sum to zero, then they disappear.  But I forgot that mystery terms don't implement `plus`, since they don't generally combine.   So I reverted to using `isInverseOf`. 

Closing.
