### ISSUE TITLE
Restoring a snapshot can place items incorrectly if they were stacked in reverse order

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#55]
@pixelzoom pay special attention to the stacking order in this issue.

If you stack objects in the reverse order that they appear in the toolbox, you get bugginess while restoring a snapshot. Stacking in forward order is fine.

Minimal reproduction case:

1. Enter Basics Screen, first scene.
2. Looking at the tool box from right to left, the constant term is first, then the cube, then the sphere. Take two of them and stack them on top of each other, grabbing the rightmost one first. (Column on the scale doesn't matter). Below is an example. The constant term is rightmost, so it was placed first and had a sphere stacked above it:

<img width="551" alt="screen shot 2018-04-02 at 12 35 28 pm" src="https://user-images.githubusercontent.com/5863899/38209692-66ae3fd2-3672-11e8-8368-13b040c963c8.png">

3. Save a snapshot.
4. Restore that snapshot.

You should see that the stacking positions were not set correctly:

<img width="504" alt="screen shot 2018-04-02 at 12 35 41 pm" src="https://user-images.githubusercontent.com/5863899/38209694-66c34b16-3672-11e8-8557-a34f6642379b.png">

NOTE: Does NOT work with inverse like terms. This will NOT be buggy:

<img width="508" alt="screen shot 2018-04-02 at 12 37 16 pm" src="https://user-images.githubusercontent.com/5863899/38209789-af26c61c-3672-11e8-9e94-bc4766f45bc6.png">

But this will:
<img width="508" alt="screen shot 2018-04-02 at 12 37 41 pm" src="https://user-images.githubusercontent.com/5863899/38209790-af385f80-3672-11e8-821c-7f104e0548ae.png">

NOTE 2: If you take these steps and use more than two items in a stack, interesting things happen. This setup:
<img width="507" alt="screen shot 2018-04-02 at 12 43 21 pm" src="https://user-images.githubusercontent.com/5863899/38210070-81ab4748-3673-11e8-99c9-7ae0cd4de44b.png">

Result; it also looked like it tried to organize some items:
<img width="476" alt="screen shot 2018-04-02 at 12 43 31 pm" src="https://user-images.githubusercontent.com/5863899/38210071-82523472-3673-11e8-88b2-c461478f8759.png">

Seen on macOS 10.13.3 Chrome. For #53.

<details>
<summary>Troubleshooting Information</summary>

URL: https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.86/phet/equality-explorer_en_phet.html
Version: 1.0.0-dev.86 2018-04-01 20:11:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"ceb3cc00","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"0f5df428","branch":"master"},"dot":{"sha":"b84c47a5","branch":"master"},"equality-explorer":{"sha":"e5eb7289","branch":"master"},"joist":{"sha":"47db3692","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"d8804eee","branch":"master"},"phet-io":{"sha":"4bbddfaa","branch":"master"},"phet-io-website":{"sha":"397862e0","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"1ecd81a1","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b1c5562c","branch":"master"},"phet-io-wrappers":{"sha":"025cc23d","branch":"master"},"phetcommon":{"sha":"aa928d57","branch":"master"},"query-string-machine":{"sha":"c379f1db","branch":"master"},"scenery":{"sha":"c8bc9dd9","branch":"master"},"scenery-phet":{"sha":"97723fc7","branch":"master"},"sherpa":{"sha":"9c6ec322","branch":"master"},"sun":{"sha":"bb49c2d0","branch":"master"},"tandem":{"sha":"f8147666","branch":"master"},"twixt":{"sha":"b2de1f74","branch":"master"},"vegas":{"sha":"b8ade2ab","branch":"master"},"vibe":{"sha":"2dc20be7","branch":"master"}}
</details>

**Comment by pixelzoom** [comment]
When run with `?ea`, this will result in an assertion failure when 2 terms are put in the same cell on a plate, for example:

> assert.js:22 Uncaught Error: Assertion failed: cell is occupied, cell: 32
    at window.assertions.assertFunction (assert.js:22)
    at Grid.putTerm (Grid.js?bust=1522774135588:218)
    at Plate.addTerm (Plate.js?bust=1522774135588:112)
    at ConstantTermCreator.putTermOnPlate (TermCreator.js?bust=1522774135588:314)
    at ConstantTermCreator.restoreSnapshot (TermCreator.js?bust=1522774135588:522)
    at PlateSnapshot.restore (Snapshot.js?bust=1522774135588:99)
    at Snapshot.restore (Snapshot.js?bust=1522774135588:54)

**Comment by pixelzoom** [comment]
Good find @phet-steele.  This bug has apparently been around for awhile.  It was not present in 1.0.0-dev.64 (3/2/18) and first appeared in 1.0.0-dev.65 (3/5/18).   That narrows it down to this commit: https://github.com/phetsims/equality-explorer/commit/de349b847aefbfcbc60c858dfe5ded14fb189722 ("generalize Grid.compactColumn...")

The column is undoubtedly being compacted before all terms have been restored to the scale. And in the case of restoring a snapshot, Grid's `compactColumn` should not be called.

**Comment by pixelzoom** [comment]
This has been addressed. @phet-steele please verify.

**Comment by phet-steele** [comment]
Working for me.
