### ISSUE TITLE
Universal operation animation overlaps with terms

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#56]
When the scale is bottomed out, the animation for a universal operation just barely overlaps with the objects on the scale (look at the plus sign on the floating "+ 10x"):

<img width="640" alt="screen shot 2018-04-02 at 1 13 06 pm" src="https://user-images.githubusercontent.com/5863899/38211542-0eebaa9a-3678-11e8-959f-721be9e7aad0.png">

This is only for multiply, add, and divide. The subtraction sign in not very "tall". @amanda-phet @pixelzoom, is there room to move the final destination of the animation up a few pixels?

Seen on macOS 10.13.3 Chrome. For #53.

<details>
<summary>Troubleshooting Information</summary>

URL: https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.86/phet/equality-explorer_en_phet.html
Version: 1.0.0-dev.86 2018-04-01 20:11:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"ceb3cc00","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"0f5df428","branch":"master"},"dot":{"sha":"b84c47a5","branch":"master"},"equality-explorer":{"sha":"e5eb7289","branch":"master"},"joist":{"sha":"47db3692","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"d8804eee","branch":"master"},"phet-io":{"sha":"4bbddfaa","branch":"master"},"phet-io-website":{"sha":"397862e0","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"1ecd81a1","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b1c5562c","branch":"master"},"phet-io-wrappers":{"sha":"025cc23d","branch":"master"},"phetcommon":{"sha":"aa928d57","branch":"master"},"query-string-machine":{"sha":"c379f1db","branch":"master"},"scenery":{"sha":"c8bc9dd9","branch":"master"},"scenery-phet":{"sha":"97723fc7","branch":"master"},"sherpa":{"sha":"9c6ec322","branch":"master"},"sun":{"sha":"bb49c2d0","branch":"master"},"tandem":{"sha":"f8147666","branch":"master"},"twixt":{"sha":"b2de1f74","branch":"master"},"vegas":{"sha":"b8ade2ab","branch":"master"},"vibe":{"sha":"2dc20be7","branch":"master"}}
</details>

**Comment by pixelzoom** [comment]
I moved the end location of the animation up 10 pixels:

![screenshot_533](https://user-images.githubusercontent.com/3046552/38261823-9e675df8-3728-11e8-856f-c1da468e86de.png)

@amanda-phet please verify that this is OK.

**Comment by amanda-phet** [comment]
Thanks for finding this @phet-steele . The change looks good to me.
