### ISSUE TITLE
Oops! dialog dismisses on pointerDown

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#58]
The Oops! dialog is inconsistent (see title of issue). Other dialogs and the barrier rectangle dismiss on pointerUp.

This causes weird behaviour on touch devices. Since `touchToSnag` is enabled, you can grab terms "through" the dialog. In other words, tapping the dialog will both dismiss it and grab the term behind it in quick succession. Not necessarily a bug, but is a poor interaction that we can avoid by waiting for pointerUp.

The second "half" of this gif is just me tapping, which causes this annoying jump since my tap also lifted the term of the scale momentarily.
![eqex02](https://user-images.githubusercontent.com/5863899/38216650-ad06293e-3688-11e8-8a7a-848c980244fe.gif)

Seen on macOS 10.13.3 Chrome. For #53.

<details>
<summary>Troubleshooting Information</summary>

URL: https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.86/phet/equality-explorer_en_phet.html
Version: 1.0.0-dev.86 2018-04-01 20:11:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"ceb3cc00","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"0f5df428","branch":"master"},"dot":{"sha":"b84c47a5","branch":"master"},"equality-explorer":{"sha":"e5eb7289","branch":"master"},"joist":{"sha":"47db3692","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"d8804eee","branch":"master"},"phet-io":{"sha":"4bbddfaa","branch":"master"},"phet-io-website":{"sha":"397862e0","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"1ecd81a1","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b1c5562c","branch":"master"},"phet-io-wrappers":{"sha":"025cc23d","branch":"master"},"phetcommon":{"sha":"aa928d57","branch":"master"},"query-string-machine":{"sha":"c379f1db","branch":"master"},"scenery":{"sha":"c8bc9dd9","branch":"master"},"scenery-phet":{"sha":"97723fc7","branch":"master"},"sherpa":{"sha":"9c6ec322","branch":"master"},"sun":{"sha":"bb49c2d0","branch":"master"},"tandem":{"sha":"f8147666","branch":"master"},"twixt":{"sha":"b2de1f74","branch":"master"},"vegas":{"sha":"b8ade2ab","branch":"master"},"vibe":{"sha":"2dc20be7","branch":"master"}}
</details>

**Comment by phet-steele** [comment]
Maybe it's just on "fire". I can hold my finger down preemptively in the center of the screen before it appears, then cause it to appear, but never see it because it is dismissed immediately.

**Comment by pixelzoom** [comment]
It currently dismisses on 'down', and should dismiss on 'fire'.

**Comment by pixelzoom** [comment]
This is fixed in the above commits, where I also renamed `OperationCanceledDialog` to `OopsDialog` :)

@phet-steele please verify in master. Thanks!

**Comment by phet-steele** [comment]
Looks fixed.
