### ISSUE TITLE
Halo remains when a term is removed via the number limit

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#59]
This is a LOT easier with mutlitouch, but it is not needed. You can use `?speed` if your mouse skills are sub-par.

1. Setup the scale such that dragging a single term onto the scale would put the sim over the number limit and show the Oops! dialog.
2. Make sure you have both a variable and constant term on the scale. Example:
<img width="461" alt="screen shot 2018-04-02 at 3 49 13 pm" src="https://user-images.githubusercontent.com/5863899/38218128-00470e9c-368e-11e8-82ff-ffa674535a56.png">

3.  Grab a term matching the one that would set the sim over the limit (an "x" in the above example).
4. Release the term far above the scale so that it has "air time" before it reaches the scale.
5. BEFORE the flying term makes it to the scale, grab a term from the toolbox. This term MUST be the opposite option from the one that's flying. So if an "x" is flying, grab a "1" and vice versa. Hover this over its counterpart on the scale to create a halo, but don't let go!

Once the flying term pops the dialog, dismiss it. You will see that there is still a halo on the scale, even though you are not holding anything (the dialog removes items not on the scale, including what you are holding).

![eqex03](https://user-images.githubusercontent.com/5863899/38218253-5aaa5452-368e-11e8-858e-29cd93214413.gif)

Seen on macOS 10.13.3 Chrome. For #53.

<details>
<summary>Troubleshooting Information</summary>

URL: https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.86/phet/equality-explorer_en_phet.html
Version: 1.0.0-dev.86 2018-04-01 20:11:12 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.162 Safari/537.36
Language: en-US
Window: 1920x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"ceb3cc00","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"0f5df428","branch":"master"},"dot":{"sha":"b84c47a5","branch":"master"},"equality-explorer":{"sha":"e5eb7289","branch":"master"},"joist":{"sha":"47db3692","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"d8804eee","branch":"master"},"phet-io":{"sha":"4bbddfaa","branch":"master"},"phet-io-website":{"sha":"397862e0","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"1ecd81a1","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"b1c5562c","branch":"master"},"phet-io-wrappers":{"sha":"025cc23d","branch":"master"},"phetcommon":{"sha":"aa928d57","branch":"master"},"query-string-machine":{"sha":"c379f1db","branch":"master"},"scenery":{"sha":"c8bc9dd9","branch":"master"},"scenery-phet":{"sha":"97723fc7","branch":"master"},"sherpa":{"sha":"9c6ec322","branch":"master"},"sun":{"sha":"bb49c2d0","branch":"master"},"tandem":{"sha":"f8147666","branch":"master"},"twixt":{"sha":"b2de1f74","branch":"master"},"vegas":{"sha":"b8ade2ab","branch":"master"},"vibe":{"sha":"2dc20be7","branch":"master"}}
</details>

**Comment by pixelzoom** [comment]
Good catch.  I believe I have addressed this in the above commit.  But it's complicated enough that I'd appreciate it if @phet-steele would verify.

**Comment by phet-steele** [comment]
Looks to be working.
