### ISSUE TITLE
Terms are layered behind the Variable panel...

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#60]
...but they are in front of everything else!

<img width="170" alt="screen shot 2018-04-02 at 4 26 59 pm" src="https://user-images.githubusercontent.com/5863899/38219452-e47fe72e-3692-11e8-91ea-260c118d153f.png">

Seen on macOS 10.13.3 Chrome. For #53.

**Comment by pixelzoom** [comment]
Good catch.  Fixed, closing.
