### ISSUE TITLE
4/16/18 interviews

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#62]
Amanda will doing interviews on Monday, 4/16/18.  

[1.0.0-dev.89](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.89/phet/equality-explorer_en_phet.html) is the dev version for interviews, with the "lock" feature and "Solve It!" screen hidden.

Specific things that I'm interested in from the interviews:
• Does the universal operation control have any usability issues?
• How often was the number limit encountered, and how did the student interpret the "Oops!" dialog?
• Does the Variable accordion box have any usability issues? See issue https://github.com/phetsims/equality-explorer/issues/30.

**Comment by amanda-phet** [comment]
Interviewed an 8th grader 4/16 and will have a 6th grader come in 4/19. 

I will write a summary soon, but quickly: no usability issues with the operation control. The student immediately recognized it as "doing the same thing to both sides". He did not push the limits but when asked to do so, he said the dialog was clear. And he was attending to both the balance and the equation when playing with the variable picker, noting that it was "like substituting". So at this point, I do not have any recommendations for UI changes.

**Comment by amanda-phet** [comment]
Second interview confirms that 6th grade student didn't have any issues with the universal operation controls. The one thing that could be tricky, based on my use and watching others, is that with the operation picker we don't always know where the operation is that we're looking for, so we click a bunch and sometimes pass it but eventually find it. It's not a big deal, people certainly understand it, but it's not the best experience. Student naturally encountered the limit, read the dialog, dismissed it, then did the opposite operation to decrease values on screen. 

The 6th grader was also able to play the game and understood what she was supposed to do, found the refresh and next buttons easily, and seemed to even be learning how to solve with fractions by playing level 3 quite a bit. It seemed like she wanted to start a challenge over when she first clicked refresh, but learned that that button actually gives you a new problem. Then she started to simply "undo" operations that weren't productive and persisted in solving some tough problems :)

**Comment by pixelzoom** [comment]
@amanda-phet said:
> The one thing that could be tricky, based on my use and watching others, is that with the operation picker we don't always know where the operation is that we're looking for, so we click a bunch and sometimes pass it but eventually find it. It's not a big deal, people certainly understand it, but it's not the best experience. 

This has been my concern since we added variable-term operands.  It works, but it's not a great experience.  And that seems like a significant problem in the last 2 screens, where the universal operation is the centerpiece.   If the universal operation control isn't "the best experience", then that's going to reflect on those screens. 

Perhaps we should take some time to brainstorm other possible designs?  Consider radically different designs, get some other people involved, etc.

**Comment by amanda-phet** [comment]
Students seemed really comfortable with the variable-term operands, actually. I just mean, in observing them use the operation picker, it's hard to know how many clicks to get to the operation you are looking for. 

I showed this to the math team last week and David was of course enthusiastic about it but I didn't get much feedback from others and it seemed like they might've had something to add. I will follow up with them about it (in particular Nancy had some thoughts but said she didn't have time to share at the time and I still haven't gotten an email response from her).

**Comment by pixelzoom** [comment]
>  I just mean, in observing them use the operation picker ...

Slack:

Chris Malley [4:34 PM]
Are students having trouble with the operator picker or the operand picker?

Amanda McGarry [4:57 PM]
not really “trouble”, but it’s the operator picker

**Comment by pixelzoom** [comment]
See https://github.com/phetsims/equality-explorer/issues/77 for possible solutions to the operator picker usability issue.

**Comment by amanda-phet** [comment]
All interviews are backed up, notes summarized in design doc, and interview survey filled out.
