### ISSUE TITLE
what to do when user achieves 10 stars in "Solve It!" game?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#63]
From https://github.com/phetsims/vegas/issues/59#issuecomment-379117231:

I asked:
> Is there supposed to be a sound associated with showing the RewardDialog? Does it need to be controlled via soundProperty?

@amanda-phet replied:
> We didn't use a sound in Make a Ten. I don't think it's necessary because they didn't really achieve anything, they simply reached a sizeable number and we are encouraging them to move on to another level.

The "cheering" sound _does_ occur in Make A Ten, whenever you get to 10 stars.  And there's a reward streaming down in the back.   So there is in fact quite a bit of fanfare for getting to 10 stars.  

So... What do you want in Equality Explorer?  
• Do you want a cheering sound? 
• Do you want a "reward" falling in the background? 
• What objects do you want in the reward?
• Do the objects in the reward differ by level?

Top priority, since this affects both Equality Explorer and https://github.com/phetsims/vegas/issues/59#issuecomment-378945761.

**Comment by pixelzoom** [comment]
For now, I've implemented exactly what Make A Ten does. See [1.0.0-dev.90](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.90/phet/equality-explorer_en_phet.html).   So to the "Solve It!" screen, turn on sound, press any level button, then press the "Next" button 10 times to accumulate 10 stars.

**Comment by pixelzoom** [comment]
How about showing stars, smiley faces and variables for the reward? And for the variables, use the level number as the coefficient (1x, 2x, 3x, 4x), like we did on the level-selection buttons.   The screenshots below show the rewards for levels 1 & 2.

![screenshot_544](https://user-images.githubusercontent.com/3046552/38400660-75a77b5e-390e-11e8-8b6c-5e5a440fcc87.png)

![screenshot_545](https://user-images.githubusercontent.com/3046552/38400656-6f7b8e50-390e-11e8-8056-1d85ce3a4d4b.png)

**Comment by amanda-phet** [comment]
I should have checked before saying that, apparently! I usually mute the game sounds. I'm usually in favor of doing the same thing in different sims so thanks for implementing the same behavior. 

This looks good to me. I just tried it out and didn't see the blue variables, only the stars and smiley faces, but I would like the blue variables too those are nice. We could also do some numerals, like random ones from 1-9, but I don't have a strong feeling about it.

**Comment by amanda-phet** [comment]
I also noticed the sound is off by default in Equality Explorer, but on by default in Make a Ten.. I will look around at different games to see if there is a typical behavior but I am thinking we should have the sound on by default.

**Comment by pixelzoom** [comment]
1.0.0-dev.90 was published before I added the variables, hence the screenshot.  

I'm not sure what you mean by "numerals" or what they would look like (constant terms?)... But if you don't feel strongly about them, then I won't add them to the reward.  3 different types of things feels like enough fun :)

Graphing Lines also has sound 'on' by default.  So I'll make it so in Equality Explorer.

**Comment by pixelzoom** [comment]
@amanda-phet [1.0.0-dev.91](https://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.91/phet/equality-explorer_en_phet.html) has variables in the rewards, and sound 'on' by default.   If this looks good and there's nothing else to do here, please close this issue.

**Comment by phet-steele** [comment]
> I'm not sure what you mean by "numerals" or what they would look like (constant terms?)... But if you don't feel strongly about them, then I won't add them to the reward. 3 different types of things feels like enough fun :)

@pixelzoom I completely disagree! The current reward is entirely boring! Even if @pixelzoom and @amanda-phet "don't feel strongly" about adding constant terms, I feel quite strongly that we need them.

Furthermore, I honestly thought it was a bug that I only saw one coefficient value on the falling variables, until I read through this issue. Not including randomization has never been done before in a PhET game's reward (pretty sure). Therefore, I also feel strongly that we NEED to randomize the coefficients on the variable terms (between 1-9). This...

> And for the variables, use the level number as the coefficient (1x, 2x, 3x, 4x), like we did on the level-selection buttons.

...is the second most boring thing I've heard in my life! Have I mentioned the reward is boring?

So again I'd vote to:

- add constants to the reward, valued [-9,9]
- randomize variable coefficient values, valued [-9,9]

(note that I'm also voting to have the range include negatives)

**Comment by pixelzoom** [comment]
This is @amanda-phet's call.  Unassigning myself.  Let me know what (if anything) you'd like to change.

**Comment by pixelzoom** [comment]
A bit more info....

Constant terms would be relative easy to add.  If you want me to add them, let me know what constant values for each level.

@samreid said:
> Not including randomization has never been done before in a PhET game's reward (pretty sure). Therefore, I also feel strongly that we NEED to randomize the coefficients on the variable terms (between 1-9).

Not true.  Other games that I've done have specific objects that are unique to specific levels.  In this case, the variable terms (and their specific coefficient) are unique to each level.    There would be no convention violated for doing the same thing with constant terms. 

> So again I'd vote to:
> 
> • add constants to the reward, valued [-9,9]
> • randomize variable coefficient values, valued [-9,9]

If we do this, then there will be zero difference between the reward for the 4 levels.  And that certainly violates convention, not to mention reduces the motivation to see what reward you get on each level.

**Comment by pixelzoom** [comment]
A bit more info....

Constant terms would be relative easy to add.  If you want me to add them, let me know what constant values for each level.

@phet-steele  said:
> Not including randomization has never been done before in a PhET game's reward (pretty sure). Therefore, I also feel strongly that we NEED to randomize the coefficients on the variable terms (between 1-9).

Not true.  Other games that I've done have objects that are unique to specific levels.  In this case, the variable terms (and their specific coefficient) are unique to each level.    There would be no convention violated for doing the same thing with constant terms. 

@phet-steele said:
> So again I'd vote to:
> 
> • add constants to the reward, valued [-9,9]
> • randomize variable coefficient values, valued [-9,9]

If we do this, then there will be zero difference between the reward for the 4 levels.  And that certainly violates convention, not to mention reduces the motivation to see what reward you get on each level.

**Comment by phet-steele** [comment]
> Not true. Other games that I've done have specific objects that are unique to specific levels.

This is not what I'm referring to. I absolutely know that one level may include one item (like "5x-3") on a level that used slope-intercept form, but then not include that item on a level that doesn't use slope-intercept form (this is a hypothetical game I'm using as an example).

What I AM referring to is that, in the same hypothetical game, that level would never ONLY show "5x - 3". It would be randomized and also show "3x +9", etc.

> If we do this, then there will be zero difference between the reward for the 4 levels. And that certainly violates convention, not to mention reduces the motivation to see what reward you get on each level.

Truth. In general the rewards have been different between levels because there is some notable (visual) difference in the gameplay of each level. However, this sim has hardly any differences between levels, so it's hard to make the rewards different. If we don't include the equations used by a level (the most distinct thing about each level), then there are not many different things we can use for the reward. Maybe we just limit the coefficient range in the early levels, then expand the range for each subsequent level?

**Comment by phet-steele** [comment]
(I deleted a duplicate comment).

**Comment by pixelzoom** [comment]
> What I AM referring to is that, in the same hypothetical game, that level would never ONLY show "5x - 3". It would be randomized and also show "3x +9", etc.

Again, not true in general.  There's no reason why a level couldn't choose to show one (and only one) equation.   There are no conventions for randomization.

>  However, this sim hardly has that so it's hard to make the rewards different right out of the gate. I

We could show objects that are not necessarily related to the challenges.  For example, in RPAL, we show sandwiches for later levels, not because sandwiches are related to the challenges, but because it's something fun that's related to the sim.  We could do the same in this sim with some of the objects from the Basics screen (fruits, animals, etc.)

**Comment by pixelzoom** [comment]
Imo, it's fine to show variable terms with only 1 coefficient for each level's reward precisely because of the association with the level-selection icons.  I.e. "1x" for "Level 1" only.  I think the same should apply to the value of constant terms, if we add them to the reward.  And we should add other objects from the Basics screen to the rewards for more difficult levels.

**Comment by amanda-phet** [comment]
Steele and I discussed at length and I am happy with the following variations for each level. @pixelzoom let me know if any of this sounds like it wouldn't look good or would be difficult. 

random integers should come from the range [-9,9] 

- Level 1: random coefficients with x, random constants, apples, and oranges 
- Level 2: random coefficients with x, random constants, random operations [+,-,•,÷] on integers (e.g., ÷3), stars
- Level 3: random coefficients with x, random fractions a/b (in the same circle as the constants), random operations on integers, stars
- Level 4: random coefficients with x, random constants, cats, and dogs

**Comment by pixelzoom** [comment]
The revised rewards are implemented in [1.0.0-dev.108](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.108/phet/equality-explorer_en_phet.html?rewardScore=1).  Run with `?rewardScore=1` to see the reward after one correct answer.

Revisions took ~2.5 hours. I made one change: in level 3, I substituted smiley faces for stars.  

@amanda-phet @phet-steele please review.

**Comment by phet-steele** [comment]
@pixelzoom we originally shied away from using smiley faces because we thought there was not enough shape contrast between them and the constant terms. Now after see them in context, I "don't feel strongly" either way.

@amanda-phet I think the operations involving negative integers are...sort of ugly. What do you think about restricting that range to [1,9]? The randomized integers for constants and coefficients can still stay [-9,9].

**Comment by pixelzoom** [comment]
I agree about the operations with negative operands.

**Comment by pixelzoom** [comment]
I agree about the operations with negative operands -- they are ugly.    I've made a change to use only positive integers [1,9].  See master.  If you don't like it, I'll change it back.

**Comment by pixelzoom** [comment]
Smiley faces look plenty different than constant terms to me, see screenshot below.  And if you're going for "standardization", nothing is more ubiquitous in games than smiley faces.

![screenshot_600](https://user-images.githubusercontent.com/3046552/39458596-09b5d5b8-4cb3-11e8-99c0-8cabff561419.png)

**Comment by amanda-phet** [comment]
Each level looks nice to me. @phet-steele close if you are happy too.

**Comment by phet-steele** [comment]
So fun.
