### ISSUE TITLE
test for memory leaks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#64]
This issue is to record the results of memory leak testing, and identify any issues.

**Comment by pixelzoom** [comment]
See https://github.com/phetsims/equality-explorer/issues/86 for possible leak in the game.

**Comment by phet-steele** [comment]
@pixelzoom I went ahead and took snapshots while running https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.111/phet/equality-explorer_all_phet.html?fuzzMouse. Looks like you had a steep initial climb (probably from entering all the screens for the first time), but then stabilized over the remaining minutes. The larger snapshots had more things on the screen at the moment of recording, which is a likely explanation.

EDIT: after 30 & 50 min tests, might have a tiny leek.

![leek](https://user-images.githubusercontent.com/5863899/39497458-ac40c89e-4d60-11e8-884a-01f10c05edf5.jpg)


| Minutes | MB |
| --- | --- |
| 0 | 69.1 |
| 1 | 81.1 |
| 2 | 84.8 |
| 3 | 83.1 |
| 4 | 83.7 |
| 5 | 82.8 |
| 6 | 83.9 |
| 7 | 86.6 |
| 8 | 86.3 |
| 9 | 86.9 |
| 10 | 85.5 |
| 30 | 87.0 |
| 50 | 89.3 |

**Comment by pixelzoom** [comment]
I added query parameters `locked` and `lockVisible`, for testing memory profiling with the lock in a specific state.  Not sure yet whether I'll need it, but good to have and it was easy to add.

**Comment by pixelzoom** [comment]
Testing the _Variables_ screen is sufficient for testing the _Basics_, _Numbers_, and _Lab_ screens. They all use the same "code paths".   

Below are Chrome 67 heap snapshots (macOS 10.11.6) for the _Variables_ screen with `?screens=3&fuzzMouse`.   After 30 minutes, heap size stabilized at 27.0 MB.    My conclusion is that this collection of screens has no significant memory leaks.

| Minutes | Heap Size (MB) |
| --- | --- |
| 0 | 21.3 |
| 5 | 26.4 |
| 10 | 26.6 |
| 15 | 27.7 |
| 20 | 27.3 |
| 25 | 27.0 |
| 30 | 27.0 |

**Comment by pixelzoom** [comment]
The _Operations_ screen uses code paths not used in the _Variables_ et al. screens.  Specifically, it adds the universal operation and it combines like terms on the plates (which involves a different drag listener subtype, `CombinedTermsDragListener`).  

Below are Chrome 67 heap snapshots (macOS 10.11.6) for the _Operations_ screen with `?screens=4&fuzzMouse`. After 30 minutes, heap size stabilized at ~30 MB. My conclusion is that this screen has no significant memory leaks.

| Minutes | Heap Size (MB) |
| --- | --- |
| 0 | 22.0 |
| 5 | 28.5 |
| 10 | 28.7 |
| 15 | 29.0 |
| 20 | 29.4 |
| 25 | 29.8 |
| 30 | 29.9 |

**Comment by pixelzoom** [comment]
The _Solve It!_ screen shares code with other screens, but has code paths that are unique to this screen.  

Below are Chrome 67 heap snapshots (macOS 10.11.6) for the _Solve It!_ screen with `?screens=5&fuzzMouse`.  This screen has an overall bigger initial footprint because it contains 4 scenes (levels), and they are all instantiated at startup.  After 30 minutes, heap size stabilized at ~50 MB. This test suggests that this screen has no significant memory leaks. 

But... For this screen, `?fuzzMouse` does not provide a good example of typical use.  Specifically, we didn't solve challenges, we didn't get to the Reward, and we spent an atypical amount of time on the level-selection UI. So I'll do another test that involves playing the game manually, perhaps similar to what @phet-steele did in #86.

| Minutes | Heap Size (MB) |
| --- | --- |
| 0 | 40.9 |
| 5 | 49.0 |
| 10 | 48.4 |
| 15 | 49.2 |
| 20 | 49.9 |
| 25 | 49.9 |
| 30 | 50.0 |

**Comment by pixelzoom** [comment]
To further test the _Solve It!_ screen, I followed a procedure similar to what @phet-steele did in #86.  I manually played all 4 levels, in order.  When I had solved 11 challenges  (and had seen the Reward after the 10th solution) I took a heap snapshot and went on to the next level.  After completing all 4 levels, I pressed the Reset All button, and took another heap snapshot.  Then I repeated the entire process.

Below are Chrome 67 heap snapshots (macOS 10.11.6) for the Solve It! screen with `?screens=5`.  Memory did not grow appreciably, and dropped after pressing Reset All.  I'm confident that this screen has no significant memory leaks.

 | Goal | Heap Size (MB) |
| --- | --- |
| sim started | 39.9 |
| Level 1 completed |  41.9 |
| Level 2 completed | 43.7 |
| Level 3 completed | 45.5 |
| Level 4 completed | 46.6 |
| Reset All button pressed | 45.5 |
| Level 1 completed | 45.5 |
| Level 2 completed | 45.9 |
| Level 3 completed | 46.5 |
| Level 4 completed | 47.0 |
| Reset All button pressed | 46.0 |

**Comment by pixelzoom** [comment]
Finally, I tested with all screens, using `?fuzzMouse`.  Below are Chrome 67 heap snapshots (macOS 10.11.6).  Memory usage started at 71.1MB, reasonable for a sim with 5 screens, and stabilized at ~82MB.    I'm confident that this sim has no significant memory leaks. 

| Minutes | Heap Size (MB) |
| --- | --- |
| 0 | 71.1 |
| 5 | 79.7 |
| 10 | 78.7 |
| 15 | 82.2 |
| 20 | 82.2 |
| 25 | 81.4 |
| 30 | 83.3 |
