### ISSUE TITLE
Improve user experience for "solve it" level descriptions

### ISSUE THREAD

**Issue by samreid** [phetsims/equality-explorer#67]
Currently if you click on the "info" button on the solve it level selection screen, you see this dialog:

![image](https://user-images.githubusercontent.com/679486/38886071-17027dc4-4232-11e8-960a-e158ebfc50c9.png)

This has a few problems:
1. You cannot see the descriptions at the same time you see the level icons
2. The descriptions are stacked vertically--the icons go horizontally
3. The descriptions go by level name, like "Level 3" but there is no level name on the buttons.

It would be a better user experience if pressing the "i" info button showed the text beneath the level selection buttons.  Internationalization could be problematic, but that can be solved by: multiline text, text max width, "leader lines" to the text, etc.

**Comment by pixelzoom** [comment]
> 1. You cannot see the descriptions at the same time you see the level icons

I'm not convinced that that is necessary.  The info dialog is intended for use by teachers, to remind them of the types of challenges in each level.  The same UX is used in Make A Ten.

> 2. The descriptions are stacked vertically--the icons go horizontally

I don't see how we can arrange the text horizontally without making a complete mess. I don't think that arranging the buttons horizontally is an option.  And I don't think it really matters in this case.

> 3. The descriptions go by level name, like "Level 3" but there is no level name on the buttons.

The coefficients on the button icons (1x, 2x, 3x, 4x) corresponds to the level numbers, as requested in https://github.com/phetsims/equality-explorer/issues/51#issuecomment-376629920.  Perhaps a bit too subtle?  We could add "Level 1", etc. title at the top of each button, ala Graphing Lines, but that looks and feels redundant.  

> It would be a better user experience if pressing the "i" info button showed the text beneath the level selection buttons. Internationalization could be problematic, but that can be solved by: multiline text, text max width, "leader lines" to the text, etc.

Cramming that much text under each button will be an absolute eyesore.  The same descriptions appear in the status bar for each level, and duplicating the strings is undesirable. Not using a Dialog means that the info button becomes a toggle button, and users may be less like to turn if off, resulting in visual clutter.

@amanda-phet Let me know what you'd like changed, if anything.

**Comment by pixelzoom** [comment]
@amanda-phet Are we making any changes here?

**Comment by pixelzoom** [comment]
4/26/18 design meeting: 

We decided not to make any changes to the Info dialog. The current presentation is sufficient for the intended purpose, and allows us to reuse the same strings, with same presentation (horizontal) in the game status bar. 

Using coefficient to communicate level number seemed to be fine in interviews.  If it comes up, we'll revisit. 

Closing.
