### ISSUE TITLE
optimize pointer areas

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#68]

**Comment by pixelzoom** [comment]
With the exception of the lock feature, all screens are feature complete.   And the remaining work on the lock feature does not affect pointer areas.  So this issue is ready to be evaluated.    I examined all pointer areas and they look good to me.  

@amanda-phet please review using `?showPointerAreas`.   Describe change requests, or close this issue if there are no changes. 

https://bayes.colorado.edu/dev/html/equality-explorer/1.0.0-dev.100/phet/equality-explorer_en_phet.html?showPointerAreas

**Comment by pixelzoom** [comment]
4/26/18 design meeting, change requests:

In universal operation control:
- [x] increase height of radio button touch areas
- [x] increase height of picker touch areas
- [x] increase Go button touch area

Other:
- [x] increase touch areas for snapshot buttons
- [x] increase touch areas for snapshot load button
- [x] increase height of touch area for 'x' picker a bit, don't get into Snapshot zone
- [x] accordion box expand/collapse buttons

**Comment by pixelzoom** [comment]
Touch area adjustments requested in https://github.com/phetsims/equality-explorer/issues/68#issuecomment-384769118 have been completed, see:

https://bayes.colorado.edu/dev/html/equality-explorer/1.0.0-dev.104/phet/equality-explorer_en_phet.html?showPointerAreas
 
And here's a screenshot:

![screenshot_597](https://user-images.githubusercontent.com/3046552/39341751-d1d30234-4991-11e8-9d47-d1fa87528cb7.png)

**Comment by phet-steele** [comment]
@pixelzoom @amanda-phet I'd request that the following be changed too:

- [x] increase the height of each term's touch area while in the toolbox

I can't see these touch areas with `?showPointerAreas`, but they feel like they match the bounds of a term. I'm finding, more often than I care to admit, I'm failing to grab a term from a toolbox because my finger aimed too high. Can the touch areas be the height of the toolbox?

Not sure if width needs to change, haven't been having issues there.

**Comment by pixelzoom** [comment]
@phet-steele requested:
> increase the height of each term's touch area while in the toolbox

Can do, stand by.

**Comment by pixelzoom** [comment]
Touch areas have been expanded for terms in the toolboxes. Their height is the height of the toolbox, and I added a bit of width too.   See screenshot below.  @phet-steele please review.

![screenshot_606](https://user-images.githubusercontent.com/3046552/39725982-ccf449e0-520a-11e8-95d5-67ac1e95b57c.png)

**Comment by phet-steele** [comment]
That feels a lot better to me, thanks @pixelzoom!

**Comment by amanda-phet** [comment]
All looks good to me.
