### ISSUE TITLE
disabling the Organize button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#7]
This is the Organize button (herein "the button"), found on the scale:

![screenshot_376](https://user-images.githubusercontent.com/3046552/29989325-77313b92-8f2f-11e7-9f03-39470cbb3c17.png)

I believe that we decided that the button should be disabled when (a) the scale is empty, or (b) the scale is already organized.  

I’ve implemented the “scale is empty” requirement, which is very easy to detect.  See for example [1.0.0-dev.9](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.9/equality-explorer_en.html). 

Disabling the button when the scale becomes organized is a bit of a problem. Every time an item is added to (or removed from) the scale, we would need to compute whether the arrangement of items on the scale is organized.  That’s going to be a relatively expensive algorithm. And since it's happening while the user is dragging something, it will impact responsiveness.

My recommendation is to disable the button when (a) the scale is empty, or (b) immediately after the button has been pressed.  After pressing the button, it will be re-enabled as soon as an item is added to (or removed from) the scale, regardless of whether the arrangement of the items is “organized”.   

This is obviously a compromise. Pressing the button may sometimes appear to do nothing.  But (imo) that's preferable to impacting overall responsiveness of the sim. 

@amanda-phet your thoughts?

**Comment by pixelzoom** [comment]
Btw... There's precedent for the compromise that I described above. The "Reset All" button in all sims is in fact _never_ disabled, because it's currently too complicated to determine whether the sim needs to be reset.

**Comment by amanda-phet** [comment]
>My recommendation is to disable the button when (a) the scale is empty, or (b) immediately after the button has been pressed. After pressing the button, it will be re-enabled as soon as an item is added to (or removed from) the scale, regardless of whether the arrangement of the items is “organized”.

That sounds perfectly reasonable to me. Please go ahead and implement the button this way.

**Comment by pixelzoom** [comment]
Done, closing.

**Comment by pixelzoom** [comment]
Disable the button when it pressed: https://github.com/phetsims/equality-explorer/commit/bb9b5dac4500b8b2018feedd447b3bda8b5a4eda
