### ISSUE TITLE
make it easier to select operator for Universal Operation 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#77]
In interviews (https://github.com/phetsims/equality-explorer/issues/62#issuecomment-384423085), @amanda-phet noted that student lost track of the order of operators, so had to scroll around in the operator picker.   Investigate other designs to eliminate/mitigate this problem.

**Comment by pixelzoom** [comment]
The problem here is that (unlike numbers) operators have no standard order, so there's no reference point for where you are in the picker.  Lack of standard order and the fact that we have a small number of operators (4) suggests that a picker is not the correct UI component for this task.   Radio buttons would be a more appropriate choice.  See [1.0.0-dev.101](https://bayes.colorado.edu/dev/html/equality-explorer/1.0.0-dev.101/phet/equality-explorer_en_phet.html) and the screenshot below.  After 30 minutes or so of playing with this, it feels much better to me.

We could also try a 2x2 grid of operators, but a grid layout is not currently supported by common code, and the buttons would be much smaller (perhaps too small).

@amanda-phet your thoughts?

![screenshot_593](https://user-images.githubusercontent.com/3046552/39276790-eaf6f440-48a7-11e8-9ddf-bbe2f089ae07.png)

**Comment by kathy-phet** [comment]
Thanks for the alternative option, Chris. Hopefully we will get to have design meeting to discuss the interview feedback and options. I like that this gives access to know that there are four operations available and select one quickly, but it also feels a bit overwhelming/distracting to have all of them visible at the same time. I liked how the original operand spinner made it very clear what operation I am about to apply. 

My current preference is for the spinner, because of this clarity and visual of one operation, before hitting go.  I also spent time spinning to the right operation but since there are only 4, I had not found it annoying myself.

**Comment by pixelzoom** [comment]
For posterity, here's a "visual summary" of approaches that we've discussed or tried.  To be clear, I'm not advocating, just recording our thoughts and decisions.

---
**DESIGN 1** - Current approach (2 spinners), as in [1.0.0-dev.100](https://bayes.colorado.edu/dev/html/equality-explorer/1.0.0-dev.100/phet/equality-explorer_en_phet.html).  

Pros: 
• Clear (1:1)  correspondence between a control and a part of the operation (operator, operand).
• Identical controls for both parts of the operation (operator, operand)  
Cons:
• Can't see operator choices, must discover them.
• Selecting an operator requires multiple clicks. 
• No clear order to operators, so choosing operator is a little more work than it should be (as evidenced by interviews).

![screenshot_78](https://user-images.githubusercontent.com/3046552/39308480-cb73708c-4922-11e8-81df-423fe093acc7.png)

---
**DESIGN 2** - Radio buttons for operator, as in [1.0.0-dev.101](https://bayes.colorado.edu/dev/html/equality-explorer/1.0.0-dev.101/phet/equality-explorer_en_phet.html).  

Pros: 
• Easy/quick to choose operator, one click.
• Operator choices are clearly visible. 
• More usable on mobile devices.
Cons: 
• More controls, more visual clutter, no 1:1 correspondence.
• Different types of controls for the operator vs operand.

![control1](https://user-images.githubusercontent.com/3046552/39308771-86e436ee-4923-11e8-8b63-2a67fae9548a.jpg)

---
**DESIGN 3** - Similar to DESIGN 2, but the operator radio buttons are arranged in a grid. This is a mockup, not implemented. 

Pros: 
• Same as DESIGN 2
• a more "visually compact" than DESIGN 2, grid starts to feel like 1 UI component, which strengthens the 1:1 correspondence between controls and parts of the equation
Cons: 
• Same as DESIGN 2
• Grid layout of radio button requires a little common-code work.

![control2](https://user-images.githubusercontent.com/3046552/39308821-b02ba438-4923-11e8-9621-d298eb4cc483.jpg)

---
**DESIGN 4** - Similar to DESIGN 2, with radio buttons for term type (variable, constant). This is a mockup, not implemented. 

Pros:  
• Simplifies the number spinner. 
• No need for general "object spinner" which is going to be a major project to migrate to common code 
Cons: 
• Too many controls
• Correspondence between control and parts of the equation has become more unclear 
• Control is getting too wide
• We never did come up with a good icon for the "constant term" radio button, and "blank" is confusing. 
 
![control3](https://user-images.githubusercontent.com/3046552/39308923-fb30d4ee-4923-11e8-8b69-e5d32528d476.jpg)

**Comment by pixelzoom** [comment]
About DESIGN 2, @kathy-phet said:
> ...  I like that this gives access to know that there are four operations available and select one quickly, but it also feels a bit overwhelming/distracting to have all of them visible at the same time. I liked how the original operand spinner made it very clear what operation I am about to apply.

Just brainstorming... What if the operation was visible on the left and right sides of the control as you were "building" it, then dropped to the plates when you pressed the Go button.  E.g.:

![control4](https://user-images.githubusercontent.com/3046552/39310324-5868a350-4927-11e8-86e0-3f865cdd76a2.jpg)

**Comment by pixelzoom** [comment]
About DESIGN 2, @kathy-phet said:
> ...  I like that this gives access to know that there are four operations available and select one quickly, but it also feels a bit overwhelming/distracting to have all of them visible at the same time. I liked how the original operand spinner made it very clear what operation I am about to apply.

Just brainstorming... What if the operation was visible on the left and right sides of the control as you were "building" it, then dropped to the plates when you pressed the Go button.  E.g.:

(EDIT: fixed screenshot)

![control4](https://user-images.githubusercontent.com/3046552/39310551-e3c73d94-4927-11e8-8c7b-1afdd38f7237.jpg)

**Comment by pixelzoom** [comment]
4/26/18 design meeting:

• Kathy has a "soft preference" for DESIGN 1.  
• Amanda, Diana, Chris, and Steele have a preference for DESIGN 2.  
 
TODO:
- [x] We'll do interviews on DESIGN 2 to see if there are any issues. (See #80)
- [x] Test radio buttons on mobile (tablets, phones)
- [x] Chris will leave both DESIGN 1 and DESIGN 2 implementation in the code for now.

Other designs:

• Steele suggested doing away with the Go button, and applying the operation when the operator is selected.  The consensus was that this has "order" problems, since you typically select operator before operand.
• Steele suggested turning the operand control into a new type of combo box. We'd need to do some design work to determine behavior, and common-code work to implement.

**Comment by pixelzoom** [comment]
The universal operation control now supports both radio buttons and picker for the operator control.  In versions >= [1.0.0-dev.105](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.105/phet/equality-explorer_en_phet.html), the default is radio buttons.  Use query parameter `?operatorControl=picker` to switch to a picker.

Interviews on the radio buttons version will be tracked in https://github.com/phetsims/equality-explorer/issues/80.

**Comment by pixelzoom** [comment]
I'll leave this unassigned until interviews are completed in #80.  Depending on which way interviews point, I'll delete either the buttons or picker support from `UniversalOperationControl`.

**Comment by ariel-phet** [comment]
Just my two cents...

Of the designs suggested design 2 seems the best.

My personal preference would be to be more along the lines of @phet-steele suggestion. And then to have the operation BE the "go" button. I have an intellectual preference for reverse polish notation style operations, so to me this is very logical. Choose an operand, then operate. Something along the lines of the mockup below, but with the operations looking more like buttony buttons. But i get that not everyone is cool with RPN. It just seems to me like it would not be that confusing, and a reasonable ordering. Fine with the design team consensus of course, but figure I would throw this out there @amanda-phet 

---
**DESIGN 5**  (CM edit)

![eqex](https://user-images.githubusercontent.com/4051174/39343085-4f2fcc3e-4998-11e8-9a05-3091165ed095.PNG)

**Comment by pixelzoom** [comment]
Let's call the above **DESIGN 5**.

A minor nit with the above mockup....  Since pushing one of the operator buttons would apply the operation, the buttons would be push buttons, not radio buttons as shown in the mockup.  They would all look the same, there would be no button that looks "selected", since there is no selection involved. That said...  I like this, but understand the concerns about RPN.

**Comment by kathy-phet** [comment]
Ariel, I’m not sure about how you would deal with order here. X is only available on + and - so if you selected x and then times it would have to say that was not allowed.

K

Sent from my iPhone

On Apr 26, 2018, at 10:41 PM, Chris Malley <notifications@github.com<mailto:notifications@github.com>> wrote:


A minor nit with the above mockup.... Since pushing one of the operator buttons would apply the operation, the buttons would be push buttons, not radio buttons as shown in the mockup. They would all look the same, there would be no button that looked "selected", since there is no selection involved. That said... I like this, but understand the concerns about RPN.

**Comment by pixelzoom** [comment]
@kathy-phet You'd have to disable operator buttons based on what operand was selected in the picker. I.e.:
• disable the times and divide operator buttons when the operand is a variable term
• disable the divide button when the operand is zero
• in the game, disable the times and divide buttons when the operand is zero

**Comment by kathy-phet** [comment]
That sounds like it could be quite distracting as you scroll through the choices, with things constantly switching between disabled or not. I favor design 2.

Sent from my iPhone

On Apr 26, 2018, at 11:35 PM, Chris Malley <notifications@github.com<mailto:notifications@github.com>> wrote:


@kathy-phet<https://github.com/kathy-phet> You'd have to disable operator buttons based on what operand was selected in the picker. I.e.:
• disable the time and divide operator buttons when the operand is a variable term
• disable the divide button when the operand is zero
• in the game, disable the times and divide buttons when the operand is zero

**Comment by pixelzoom** [comment]
Agreed, distracting.  The other alternative is worse -- let them push any operator button, and display a dialog (like below) when it's not a supported operation.  Yuck.

![screenshot_599](https://user-images.githubusercontent.com/3046552/39346917-b36fd6ac-49ad-11e8-9c62-7000a9a1eafa.png)

**Comment by kathy-phet** [comment]
Agreed, that is worse. I am preferring the go botton.

Sent from my iPhone

On Apr 26, 2018, at 11:59 PM, Chris Malley <notifications@github.com<mailto:notifications@github.com>> wrote:


Agreed, distracting. The other alternative is worse -- let them push any operator button, and display a dialog (like below) when it's not a supported operation. Yuck.

[screenshot_599]<https://user-images.githubusercontent.com/3046552/39346917-b36fd6ac-49ad-11e8-9c62-7000a9a1eafa.png>

**Comment by ariel-phet** [comment]
@pixelzoom @kathy-phet an alternative would be not disabling, but as you scroll it switches between all 4 buttons, and just the "+" and "-" button. The "+" and "-" button would then be centered under the operand.

Right now, with the radio button design, if you have "3x" selected as an operand and choose "multiply" it just changes it to a "3"...that seems subtle. Whereas simply showing the available operations seems clear to the user. I think since the flipping between the available operations would be consistent it would making the interaction feel not at all distracting, and very clear what you could and could not do.

**Comment by pixelzoom** [comment]
@amanda-phet About 2 hours to implement what @ariel-phet has described in https://github.com/phetsims/equality-explorer/issues/77#issuecomment-385298915, if you want to try it.  I think it's worth trying.

**Comment by kathy-phet** [comment]
I am curious pedagogically about what @amanda-phet thinks. The RPN seems problematic pedagogically here - for the age group and the level of learners that these kids. They need to be thinking "+1" not "1+". ... it seems to me.

**Comment by pixelzoom** [comment]
You can test drive @ariel-phet's design (**DESIGN 5**) in [1.0.0-dev.109](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.109/phet/equality-explorer_en_phet.html).  It was trivial to implement, about half the code, no gymnastics required to add/remove operands from the picker.  But the operator buttons appearing/disappearing and jumping around as you scroll through the picker is incredibly distracting (imo).

**Comment by pixelzoom** [comment]
[1.0.0-dev.110](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.110/phet/equality-explorer_en_phet.html) is a variation of @ariel-phet's design.  It disables operator buttons instead of hiding them, so there's less jumping around.  Less distracting, but still distracting.

**Comment by amanda-phet** [comment]
Since it's only implemented in the Operations screen, it's really hard to adequately compare. I really want to know how it feels on the Solve It screen. 

However, I'm pretty sure we cannot use this new design. We just don't think in that sequence, especially when solving equations in the game screen. From two interviews with students, we consistently saw them change the operator first, then the operand. I think it could also be problematic for touch if you are clicking down on the picker and accidentally click an operator button. 

The subtlety of a 3x changing to a 3 is inconsequential. It's not meant to be a teaching moment, it is simply a constraint of the sim. THere's no mathematical reason why you can't multiply by 3x, we just don't allow it in this sim.

**Comment by pixelzoom** [comment]
@amanda-phet See [1.0.0-dev.11](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.111/phet/equality-explorer_en_phet.html), which has @ariel-phet's design in both screens (buttons become disabled, not invisible).  If there's any possibility that you want to try it in interviews, I'll keep it around (with associated cost to keep it in-sync with changes).  Otherwise I'll delete it (recoverable in GitHub in the future.)

**Comment by amanda-phet** [comment]
I would encourage everyone to play with it on the game screen... I played for quite a while and it never felt comfortable to me. My preference is to stick with "design 2" with the horizontal radio buttons.

**Comment by kathy-phet** [comment]
I also prefer "design 2"

**Comment by ariel-phet** [comment]
Thanks @pixelzoom - to me this is a more logical interface, and removes an extra button press. But looks like I am being out voted. Oh well :)

**Comment by pixelzoom** [comment]
Closing this issue.  Interviews on DESIGN 2 are tracked in #80.
