### ISSUE TITLE
Halo sticks when dragging away from an inverse and towards a "like"

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#79]
Go to the Numbers or Variables screen:

1. Place a term and its inverse on one plate, next to each other (stacked or side by side).
2. Take a third term from the toolbox and hover it over it's inverse so that it gets a halo. Don't release the term.
3. Drag the same term over to the non-inverse term. The halo will remain on the one you are dragging. This shouldn't be since you cannot combine them. Releasing the term from here will keep the halo as well.

![eqex06](https://user-images.githubusercontent.com/5863899/39327642-d80d4362-4955-11e8-88dc-d5b12b74cbb8.gif)

Master at https://github.com/phetsims/equality-explorer/commit/4cf64b383c3b8c7f67aa14f00287dc1059550124. Seen on macOS 10.13.4 Chrome.

**Comment by pixelzoom** [comment]
Reproduced. Occurs with both constant and variable terms.

This problem first appears in [1.0.0-dev.70](https://bayes.colorado.edu/dev/html/equality-explorer/1.0.0-dev.70/phet/equality-explorer_en_phet.html), 3/15/18, 5:12 PM.  
It was not present in [1.0.0-dev.69](https://bayes.colorado.edu/dev/html/equality-explorer/1.0.0-dev.69/phet/equality-explorer_en_phet.html), 3/12/18, 2:46 PM.

There is one significant commit between those 2 versions: https://github.com/phetsims/equality-explorer/commit/4ec7b33ab6cd5fff08dca51e404e978bdc415624. 

Most likely in `TermDragListener.refreshHalos`.

**Comment by pixelzoom** [comment]
The problem was indeed in `TermDragListener.refreshHalos`. Fixed in above commit. 

@phet-steele please verify in master.

**Comment by phet-steele** [comment]
Looking better 👍.
