### ISSUE TITLE
query parameters for populating the scale on startup

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#8]
Fully testing this sim requires examining lots of different scenarios.  Dragging items to the scale individually takes a lot of time, and gets old really fast.  So I'm going to add query parameters that allow you to specify how many of each item you want on the left vs right side of the scale.  This will speed up development, and should be useful during testing.  

This feature is intended for debugging and testing only, not for production.

**Comment by pixelzoom** [comment]
In [EqualityExplorerQueryParameters.js](https://github.com/phetsims/equality-explorer/blob/master/js/common/EqualityExplorerQueryParameters.js), I've added 2 query parameters,`leftItems` and `rightItems`. They specify the number of items to put on the scale's left and right weighing platforms respectively.

Let's start with an example. `?showGrid&leftItems=4,3,5&rightItems=12,0,12` looks like this at startup:

![screenshot_379](https://user-images.githubusercontent.com/3046552/30288463-07d4bb66-96e6-11e7-972b-906fe0c4f77a.png)

Now for the details...

The value for these query parameters is an array of 3 numbers. The numbers specify how many of each item type you'd like on the scale.  The order of the numbers matches the order of the items in the panels that appear below the scale.  For example `5,0,6` means "5 apples, 0 oranges, 6 ones".  

You don't have to provide both `leftItems` and `rightItems`, you can provide just one of them.  If you provide neither, the default values are `0,0,0`.

The values that you provide are applied to _all_ scenes.  For the example screenshot above, you'd see the same number of items in all 3 scenes - fruit, polygons and spheres scenes. 

Items are added to the scale in the order that they appear in the panel, and by filling the grid bottom-up, left-to-right.  This was the easiest way to put things on the scale, and (as a bonus) ensures that the "organize" button does something when you press it.

Two conditions for these query parameters to be valid: (1) they must each contain 3 numbers, and (2) the sum of the numbers must be <= 36 (the number of cells on each weighing platform).  If these conditions are not met, an Error is thrown.  Examples of invalid values and their associated Errors:

`?leftItems=4,3` -> `Error: query parameter leftItems must have 3 values`

`?rightItems=15,15,15` -> `Error: query parameter rightItems contains too many items, max is 36`

**Comment by pixelzoom** [comment]
You can test drive these query parameters in [1.0.0-dev.13](http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.13/equality-explorer_en.html).

@amanda-phet @phet-steele Assigning to you as an FYI, so that you're familiar with this feature, since I suspect you'll be using it a lot.  Unassign yourself when you've had a look.  Last one to unassign please close this issue.

**Comment by phet-steele** [comment]
Love it...this breaks in a way you didn't mention above: `?leftItems=0.1,-36,36`, but I love it! I'll try to use it responsibly....

**Comment by amanda-phet** [comment]
Oop, never closed this. I've used it a bunch already and love it. Thanks for making it. I won't have a problem using it responsibly :)

**Comment by pixelzoom** [comment]
@phet-steele said
> Love it...this breaks in a way you didn't mention above: ?leftItems=0.1,-36,36, but I love it! I'll try to use it responsibly....

I added verification that all values are integers that are >= 0.

**Comment by pixelzoom** [comment]
@amanda-phet @phet-steele FYI....

As I've started to flesh out the other screens, I realized that we need similar query parameters for each screen.  So I've changed things quite a bit.  Here are the new query parameters for specifying the number of items on the scale at startup:

// Basics screen (array of 3 integer values)
leftBasics
rightBasics

// Numbers screen (array of 2 integer values)
leftNumbers
rightNumbers

// Variables screen (array of 4 integer values)
leftVariables
rightVariables

Hopefully this is each to remember.  It's the word "left" or "right", followed by the screen name.  If you forget, run with `?log` and all sim-specific query parameters (and their values) will be printed to the browser console.

Use responsibly. Error handling is not as robust as it was previously, but should keep you out of most trouble.

There are current no similar query parameters for the Solving screen, since it's a bit of a different beast and deals with fractions.

**Comment by pixelzoom** [comment]
Reopening.  

@amanda-phet @phet-steele FYI, this test/debug feature was lost as part of rearchitecting for #48.  It was going to be a significant amount of work to rewrite, so (for now? forever?) I simply removed the feature. I found it very useful in the beginning of development, but I haven't used it for awhile.    If anyone misses it, please complain here.  That will help me evaluate whether it's worth the work.   

If it turns out _not_ to be worth doing, then I need to delete the related query parameters in `EqualityExplorerQueryParameters`.

**Comment by pixelzoom** [comment]
For posterity, this is the bit of code that used to live in `TermCreator.initialize`.   I factored it out into its own method here.

```js
/**
 * Populate the plate with initial terms, for debugging.
 * See https://github.com/phetsims/equality-explorer/issues/8
 * @public
 */
populatePlate: function() {
  assert && assert( this.plate, 'plate has not been initialized' );
  assert && assert( this.positiveLocation, 'positiveLocation has not been initialized' );
  
  for ( var i = 0; i < this.initialNumberOfTermsOnPlate; i++ ) {
    var cellIndex = this.plate.getFirstEmptyCell();
    assert && assert( cellIndex !== -1, 'oops, plate is full' );
    this.createTermOnPlate( cellIndex );
  }
},
```

**Comment by amanda-phet** [comment]
I haven't used this query parameter in a while, either. @phet-steele might like it for testing later on, but I don't think we should spend a lot of time right now making this available.

**Comment by pixelzoom** [comment]
@phet-steele Your opinion on how useful this would be for testing and long-term maintenance?

**Comment by phet-steele** [comment]
@pixelzoom this is still very useful. However, I've found it's mostly just maxing out the plate that's useful, not the pre-population. If it's any less amount of time, would it be easier to instead have a query parameter that allows us to change the max number of items on the plate, and not worry about pre-populating the plate at all? That way I can say something like `?maxTerms=6` and only need to drag 6 things to hit a max, instead of 36.

Whether or not we differentiate between left/right scales and between screens I leave up to you @pixelzoom.

**Comment by pixelzoom** [comment]
@phet-steele suggested:
> ... If it's any less amount of time, would it be easier to instead have a query parameter that allows us to change the max number of items on the plate, and not worry about pre-populating the plate at all?  ...

Good idea, I'll investigate.

**Comment by pixelzoom** [comment]
@phet-steele I've added these query parameters. Please test drive in master, let me know if these are useful.

```js
    // Number of rows in the grid on each plate in the 'Basics', 'Numbers' and 'Variables' screens.
    // Set this to a smaller number so you can fill up the plate faster.
    // For internal use only, not public facing.
    rows: {
      type: 'number',
      defaultValue: 6,
      isValidValue: function( value ) {
        return value > 0 && value <= 6;
      }
    },

    // Number of columns in the grid on each plate in the 'Basics', 'Numbers' and 'Variables' screens.
    // Set this to a smaller number so you can fill up the plate faster.
    // For internal use only, not public facing.
    columns: {
      type: 'number',
      defaultValue: 6,
      isValidValue: function( value ) {
        return value > 0 && value <= 6;
      }
    },
```

**Comment by phet-steele** [comment]
@pixelzoom working well in master, and it doesn't look like it took too long. They were useful enough indeed, thanks. Back to you to probably close.

**Comment by pixelzoom** [comment]
Thanks @phet-steele.  Yes, it was relatively easy to add these, and I think they accomplish what we need.  Again, good idea.  Closing.

**Comment by pixelzoom** [comment]
@amanda-phet FYI... If you need to fill the scale up more quickly, reduce the size of the grid using the `rows` and `columns` query parameters.  E.g. `?rows=2&columns=2` will give you a 2x2 grid.
