### ISSUE TITLE
interview on radio buttons for choosing universal operator

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#80]
In https://github.com/phetsims/equality-explorer/issues/77#issuecomment-384765795, we decided to have interim support for 2 different controls that select the universal operator: a set of 4 radio buttons, or a picker.

Interviews have already been done with the picker (see #62), and that motivated the radio buttons. 
Now we need to do interviews on the version that uses radio buttons.

In versions >= [1.0.0-dev.105](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.105/phet/equality-explorer_en_phet.html), the default is radio buttons. Query parameter `?operatorControl=picker` can be used to change to a picker.

If the interview results are positive, we'll remove the picker support. (See `UniversalOperatorControl`.)

**Comment by pixelzoom** [comment]
5/31/18 design meeting: OK to delete the version of this control that involved 2 pickers.

**Comment by amanda-phet** [comment]
I am going to show all three versions (RP notation, pickers, and radio buttons) to some teachers on Monday for feedback.

**Comment by pixelzoom** [comment]
5/31/18 design meeting:
#107 still indicates some potential issues with UOC.  @amanda-phet will show various designs to some teachers during next week's math workshop.

**Comment by pixelzoom** [comment]
@amanda-phet Here are links to dev versions for each of the design options that we've implemented.

[1.0.0-dev.122](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.122/phet/equality-explorer_en_phet.html)
![screenshot_663](https://user-images.githubusercontent.com/3046552/40808382-27a41d66-64e4-11e8-9fa7-f004550ca6a6.png)

[1.0.0-dev.111](https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.111/phet/equality-explorer_en_phet.html)
![screenshot_664](https://user-images.githubusercontent.com/3046552/40808417-4129828a-64e4-11e8-8a7c-8bf2597334ac.png)

[1.0.0-dev.100](https://bayes.colorado.edu/dev/html/equality-explorer/1.0.0-dev.100/phet/equality-explorer_en_phet.html)
![screenshot_662](https://user-images.githubusercontent.com/3046552/40808341-0d6817f4-64e4-11e8-9bab-be2bcf5c795a.png)

**Comment by amanda-phet** [comment]
I spoke with 5 teaches about the options listed above and there were pros and cons of all three options, but by far they all preferred the radio button option (in dev.122).
