### ISSUE TITLE
performance testing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#83]
Test performance on all supported platforms, identify performance issues.

**Comment by phet-steele** [comment]
Just as a reminder for the future: decent performance hit when restoring snapshots that completely fill both plates (early screens).

**Comment by pixelzoom** [comment]
That performance hit is (unfortunately) unavoidable; the time to restore a snapshot's view increases linearly with the number of terms.  It's previously been run past the design team, and the consensus was that the user can tolerate (perhaps might even expect) a bit of time to restore a snapshot.

**Comment by pixelzoom** [comment]
@amanda-phet Please review the performance, let me know if there's anything that's not acceptable.  The only thing that I've noticed is time to restore a snapshot, as noted by @phet-steele above.  But as I said above, that's unavoidable, since restoring involves recreating all of the model and view elements.

**Comment by pixelzoom** [comment]
I should note that I tested performance on an iPad2 (iOS 9.3.5) and my 9-year-old MacBook Pro (macOS 10.11.6), and everything feels snappy.

**Comment by pixelzoom** [comment]
5/31/18 design meeting:  Discussed and demonstrated the delay to restore a snapshot, and it was deemed acceptable.

**Comment by pixelzoom** [comment]
Raising priority of this to "top", because we are now in code review, and any changes to address performance could potentially result in big code changes.

**Comment by amanda-phet** [comment]
I tested this today and decided it was acceptable for iPad 2.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
