### ISSUE TITLE
Game may leak memory on repeated play

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#86]
@pixelzoom I took heap snapshots using https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.111/phet/equality-explorer_en_phet.html?screens=5 (notice `?screens=5` and the lack of `?rewardScore`).

I took one at startup, then one after completion of each level (letting the reward node trickle to the bottom of the sim before pressing "New Level"), then one after Reset All. The snapshot size did NOT decrease to its starting value after the reset, so I'm led to believe that repeated play of the game, or just playing for a long time, would expend our memory.

| | MB |
| --- | --- |
| Start | 38.8 |
| Level 1 | 41.2 |
| Level 1,2 | 42.8 |
| Level 1,2,3 | 44.1 |
| Level 1,2,3,4 | 45.3 |
| Reset All | 43.7 |

Seen on macOS 10.13.4 Chrome. For #76.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.111/phet/equality-explorer_en_phet.html?screens=5
Version: 1.0.0-dev.111 2018-05-01 19:59:18 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
Language: en-US
Window: 894x691
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4ce9d171","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"1ee8228c","branch":"master"},"dot":{"sha":"14cc3d15","branch":"master"},"equality-explorer":{"sha":"3633ae35","branch":"master"},"joist":{"sha":"7874f857","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"752ea737","branch":"master"},"phet-io":{"sha":"45e5b058","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"dfc83c89","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"020f3ed6","branch":"master"},"phet-io-wrappers":{"sha":"a00f4c29","branch":"master"},"phetcommon":{"sha":"9a8756e6","branch":"master"},"query-string-machine":{"sha":"f9def230","branch":"master"},"scenery":{"sha":"dedc0267","branch":"master"},"scenery-phet":{"sha":"2c1ff10e","branch":"master"},"sherpa":{"sha":"abef4445","branch":"master"},"sun":{"sha":"09efcff9","branch":"master"},"tandem":{"sha":"718d8a58","branch":"master"},"twixt":{"sha":"756c0bd8","branch":"master"},"vegas":{"sha":"b30d7150","branch":"master"},"vibe":{"sha":"f2175b9b","branch":"master"}}
</details>

**Comment by pixelzoom** [comment]
Thanks @phet-steele.  Highly possible that there's a memory leak.  No memory leak testing has been done on this sim yet, see #64.

**Comment by pixelzoom** [comment]
@phet-steele I'm confident that the _Solve It!_ screen has no significant memory leaks. See https://github.com/phetsims/equality-explorer/issues/64#issuecomment-394465770 and https://github.com/phetsims/equality-explorer/issues/64#issuecomment-394465770.

Closing.
