### ISSUE TITLE
icon for "organize" button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#9]
According to 5/4/17 meeting notes in the [design document](https://docs.google.com/document/d/1xu9nawWcndFqgg5zyCGm25h-OFUsuFYnXF3QHW42spQ/edit), the icon for the "organize" button is "similar to current one but still needs design work".    Since the "organize" feature is now fully functional (see #4), that design work should be able to proceed.

The current icon (shown in the screenshot below) is implemented programmatically, see [OrganizeButton.js](https://github.com/phetsims/equality-explorer/blob/master/js/common/view/OrganizeButton.js).
 
![screenshot_380](https://user-images.githubusercontent.com/3046552/30290701-99c3126e-96ed-11e7-86fc-97eb610a59c4.png)

**Comment by amanda-phet** [comment]
Here is the design for the organize button. Do you think the circles and squares are too small to be discernible? 
<img width="237" alt="screen shot 2017-09-29 at 11 04 03 am" src="https://user-images.githubusercontent.com/7852916/31027041-ff897f22-a505-11e7-8aff-6d069cb1ac00.png">

**Comment by pixelzoom** [comment]
Size of the circles and squares seems fine.  I'm a little concerned that arrow might be interpretted as "move items from left plate to right plate".  Any reason why it's blue instead of the standard "button yellow"?

**Comment by amanda-phet** [comment]
I changed the color because of all of the yellow, discussed in https://github.com/phetsims/equality-explorer/issues/6#issuecomment-333163546.

**Comment by pixelzoom** [comment]
Think I'd change the item before changing the button color.  Imo, the more colorful a sim is, the more 
important it is to stick to standard/consistent button colors.  But your call.

**Comment by pixelzoom** [comment]
@amanda-phet and I discussed on the phone.  Here's what we came up with, implemented in the above commit:

![screenshot_67](https://user-images.githubusercontent.com/3046552/31037414-0595694e-a52e-11e7-9f5c-03d1bb4e78a5.png)

**Comment by pixelzoom** [comment]
Forgot to mention.... @amanda-phet, I think your mockup of the above had 2 columns of squares on the left.  I tried that and the squares looked very heavy.  Switching the squares and circles made it feel more balanced, and also matches (somewhat) the ordering of the "Shapes" scene.

**Comment by amanda-phet** [comment]
My mockup had 5 circles on the left actually, so the stacks weren't both full. I'm fine with either. Thanks for making the change.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pixelzoom** [comment]
Updated icon appears in http://www.colorado.edu/physics/phet/dev/html/equality-explorer/1.0.0-dev.26/equality-explorer_en.html

**Comment by pixelzoom** [comment]
The organize icon (as shown above in https://github.com/phetsims/equality-explorer/issues/9#issuecomment-333247574) is a pretty ugly bit of code.  I've converted it to an Illustrator (.ai) file, which I then saved as SVG.  Then I'm using the SVG path description directly in the code.  This replaces a big chunk of code with an Illustrator file that can be easily modified, while preserving the rendering quality of the icon.

@amanda-phet If you want to modify the icon further, you can find the .ai file at:
https://github.com/phetsims/equality-explorer/blob/master/assets/organize-icon.ai

**Comment by amanda-phet** [comment]
Thanks @pixelzoom . I have updated the .ai file (deleted one circle). Should I upload it to github? I don't want to mess anything up by doing that so I'm just making sure.

**Comment by pixelzoom** [comment]
You can either push the modified to GitHub, or email me me the file. Whatever is easier for you.

**Comment by amanda-phet** [comment]
ok thank I pushed it.

**Comment by pixelzoom** [comment]
Reopened until I do my piece of the work.

**Comment by pixelzoom** [comment]
New asset files were pushed in https://github.com/phetsims/equality-explorer/commit/342dec42acc68a57647d3ee92e6358fc8ca5b099.    The .svg is incorrect, it needs to be generated as a single path, as described in https://github.com/phetsims/equality-explorer/blob/master/assets/README.md.  I'll handle fixing it.

**Comment by pixelzoom** [comment]
.svg file is fixed, and revised path is integrated into the code.  Closing.
