### ISSUE TITLE
Cannot sum-to-zero on a full plate

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#92]
@pixelzoom it's pretty hard to find documentation on every change from #19; sorry if this isn't an issue...but I find it hard to believe this was on purpose.

This issue was from testing #91, but is totally INDEPENDENT from the lock feature.

1. Numbers or Variables screen.
2. Fill up one side of the plate.
3. Trying to sum-to-zero a term on the filled side of the plate is not possible:

![eqex07](https://user-images.githubusercontent.com/5863899/39718344-3d3d03ee-51f3-11e8-90f9-8584f584544a.gif)

This was not a problem in dev.113, but is in dev.114.

Seen on macOS 10.13.4 Chrome.

<details>
<summary>Troubleshooting Information</summary>

URL: https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.114/phet/equality-explorer_en_phet.html?log
Version: 1.0.0-dev.114 2018-05-07 16:41:54 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
Language: en-US
Window: 1371x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4ce9d171","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"69d483f8","branch":"master"},"dot":{"sha":"070374e3","branch":"master"},"equality-explorer":{"sha":"235e9844","branch":"master"},"joist":{"sha":"7874f857","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"752ea737","branch":"master"},"phet-io":{"sha":"4026843e","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"master"},"phet-io-wrappers":{"sha":"e76385d0","branch":"master"},"phetcommon":{"sha":"9a8756e6","branch":"master"},"query-string-machine":{"sha":"f9def230","branch":"master"},"scenery":{"sha":"7b46dc00","branch":"master"},"scenery-phet":{"sha":"0bf11ae9","branch":"master"},"sherpa":{"sha":"ded365aa","branch":"master"},"sun":{"sha":"09efcff9","branch":"master"},"tandem":{"sha":"beb7d180","branch":"master"},"twixt":{"sha":"756c0bd8","branch":"master"},"vegas":{"sha":"21912f64","branch":"master"},"vibe":{"sha":"f2175b9b","branch":"master"}}
</details>

**Comment by pixelzoom** [comment]
Fixed in master.  @phet-steele please verify.

**Comment by phet-steele** [comment]
Magnificent.
