### ISSUE TITLE
Dragging terms are abandoned while switching screens

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#93]
1. Pick a non-game screen.
2. Start dragging a term with finger A (way more fun if lock is on, but not needed).
3. With finger B, switch to a new screen. This will cancel your drag with finger A, so you can go ahead and release that finger from the screen.
4. Return to the screen you chose in step 1.

The term you were dragging will be floating where you left it. It can be dragged again like normal. Dragging again while the lock is on, then repeating these steps, is really fun!

Seen on iOS 11.3 iPad Air 2. For #91.

<details>
<summary>Troubleshooting Information (not from the iPad)</summary>

URL: https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.114/phet/equality-explorer_en_phet.html?log
Version: 1.0.0-dev.114 2018-05-07 16:41:54 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.117 Safari/537.36
Language: en-US
Window: 1371x1014
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 32 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"928741cf","branch":"master"},"axon":{"sha":"4ce9d171","branch":"master"},"brand":{"sha":"89d28f63","branch":"master"},"chipper":{"sha":"69d483f8","branch":"master"},"dot":{"sha":"070374e3","branch":"master"},"equality-explorer":{"sha":"235e9844","branch":"master"},"joist":{"sha":"7874f857","branch":"master"},"kite":{"sha":"b6071478","branch":"master"},"phet-core":{"sha":"752ea737","branch":"master"},"phet-io":{"sha":"4026843e","branch":"master"},"phet-io-wrapper-classroom-activity":{"sha":"5204ea8e","branch":"master"},"phet-io-wrapper-lab-book":{"sha":"ccaaaa4b","branch":"master"},"phet-io-wrappers":{"sha":"e76385d0","branch":"master"},"phetcommon":{"sha":"9a8756e6","branch":"master"},"query-string-machine":{"sha":"f9def230","branch":"master"},"scenery":{"sha":"7b46dc00","branch":"master"},"scenery-phet":{"sha":"0bf11ae9","branch":"master"},"sherpa":{"sha":"ded365aa","branch":"master"},"sun":{"sha":"09efcff9","branch":"master"},"tandem":{"sha":"beb7d180","branch":"master"},"twixt":{"sha":"756c0bd8","branch":"master"},"vegas":{"sha":"21912f64","branch":"master"},"vibe":{"sha":"f2175b9b","branch":"master"}}
</details>

**Comment by phet-steele** [comment]
The floating term still has a shadow and can still get a halo when it begins to overlap something. Makes me think it is still being "dragged" instead of "cancelled" like I mentioned above.

**Comment by pixelzoom** [comment]
A general deficiency of joist is that Screens are not notified when they are activated/deactivated.  So I'll probably have to resort to something like:

```js
phet.joist.sim.screenIndexProperty.link( function( screenIndex ) {
  self.disposeTermsNotOnPlate();
} );
```

Two problems with this approach:
(1) It relies on a global 
(2) `screenIndexProperty` is currently `@public (joist-internal)`, so should not be used outside of joist.

**Comment by pixelzoom** [comment]
Investigate:

(1) Are active drag sequences interrupted when changing screens?
(2) Use Screen `screenActiveProperty` to `disposeTermsNotOnPlate`.

**Comment by pixelzoom** [comment]
In the above commit, any terms that are not on the scale (i.e., terms that are dragging or animating) are disposed of when switching screens.  @phet-steele please verify.

**Comment by phet-steele** [comment]
@pixelzoom I think this is working 🤞.
