### ISSUE TITLE
?showAnswers lets you score multiple times in one prompt

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#95]
@pixelzoom this is not a public facing bug since it involves `?showAnswers`.

If you click the cheat button FIRST, you can solve for "x" a second time and get two stars for one prompt. Maybe best to fix this? (I don't know)

**Comment by pixelzoom** [comment]
Yep, worth fixing. Done in above commit. @phet-steele please verify.

**Comment by phet-steele** [comment]
👍
