### ISSUE TITLE
Equivalent term loses drop shadow when still being dragged

### ISSUE THREAD

**Issue by phet-steele** [phetsims/equality-explorer#96]
1. Numbers, Variables, or Operations screen.
2. LOCK!
3. Grab a new term from the toolbox with finger A and just hold it on the screen, maybe above the scale so it's easy to see.
4. Take finger B and add something to the scale. As you do this, keep your eyes on the equivalent term you are holding with finger A.

The drop shadow disappears on the equivalent term!

@pixelzoom this is one of many different ways to cause this to occur. My hunch is that any interaction that alters the scale and/or state of equality (adding something new, changing value of x, etc.) will cause this issue.

Seen on iOS 11.3 iPad Air 2 on master at https://github.com/phetsims/equality-explorer/commit/45034868d5a491d53550ebebec59e557c0f981aa. For #91.

**Comment by pixelzoom** [comment]
Reproduced.

`shadowVisibleProperty.value` is set exclusively in TermDragListener (7 places), so start the investigation there.

**Comment by pixelzoom** [comment]
`this.equivalentTerm.shadowVisibleProperty.value = false;` occurs in only 1 place, and it looks correct to me.  In TermDragListener `end`, see line 302:

```js
      // set term properties at end of drag
      this.term.draggingProperty.value = false;
300   this.term.shadowVisibleProperty.value = false;
      if ( this.equivalentTerm ) {
302     this.equivalentTerm.shadowVisibleProperty.value = false;
      }
```

... and if this code were being executed, I would expect the shadow on the dragged term to disappear also (see line 300), but it does not.

**Comment by pixelzoom** [comment]
I commented out [line 302 above](https://github.com/phetsims/equality-explorer/issues/96#issuecomment-387593973) and the problem persists.

**Comment by pixelzoom** [comment]
There are 2 other calls to `shadowVisibleProperty.value = false`, both in `refreshHalos` (private to TermDragListener).  The call on line 779 appears to be the culprit:

`this.term.shadowVisibleProperty.value = false;`

... but `this.term` is the _dragged_ term, so unclear why this is affecting (what should be) the equivalent term.

**Comment by pixelzoom** [comment]
I tried this on the Variables screen, using 'x' terms for step 3, and '1' terms for step 4.   This was to confirm that it's not somehow related to "like" terms.   The problem occurs in that scenario too.

**Comment by pixelzoom** [comment]
All terms have an associated TermDragListener, but the drag listener should be considered "active" only for terms that are being explicitly dragged.  In this case, the equivalentTerm is not being dragged, is following the dragged term.  But regardless of whether the drag listener was active, `refreshHalos` was being called whenever the plate's contents or location changed. 

This was fixed in the above commit, so that `refreshHalos` is performed only if the drag listener is active (i.e., the term is currently pickable).

Another excellent find @phet-steele.  Please verify.

**Comment by phet-steele** [comment]
Looks good, thanks.
