### ISSUE TITLE
what to do with 'x & y' screen?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/equality-explorer#99]
While implementing Equality Explorer, I created a hidden screen that supports multiple variables.  I did this to verify that I wasn't writing code with "single variable" assumptions.  After showing it to @amanda-phet and @kathy-phet, there was some interest in using this screen, possibly in a new sim.  

The screen is currently named "x & y",  and it's hidden behind the `?xy` query parameter.  You can test-drive it here (note the query parameter):

https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.115/phet/equality-explorer_en_phet.html?xy

Assigning to @amanda-phet and @kathy-phet to decide whether to do anything with this screen.  If there are additional requirements that might affect the implementation of Equality Explorer, it would be good to at least make a first pass at identifying those before Equality Explorer enters dev testing.

**Comment by kathy-phet** [comment]
David had a number of learning goals that could be addressed by this screen: 

> So this new screen has excellent potential to help students formulate conjectures about equality between variable representations. This kind of reminds me of some of the questions you would typically get on the SAT, where you had to decide whether one was greater than the other or they were both equal, or if there was no way for you to tell. The difference with this sim is that you can explore some of your conjectures by checking values of X and Y very easily.
> 
> For example, start with a positive value for x and hide the value. Compare x with -x on the balance.
> Is there ever a case where this balance will be equal? Will it ever tip the other way or is x always greater than -x?
> 
> Add in coefficients -- will 2x ever be less than - x? Add in constants... etc.
> 
> There are some good thought provoking problems that could be proposed and then investigated through this sim window. 

> When is x - y > y - x? 
> When are they equal?

**Comment by kathy-phet** [comment]
But what should the sim name be. Here is a brain dump: 

Equality Explorer XY
Equality Explorer: X & Y
Equality Explorer: Systems
Equality Explorer: Two Variables

**Comment by pixelzoom** [comment]
@kathy-phet requested a version with xy screen only, here it is:

https://phet-dev.colorado.edu/html/equality-explorer/1.0.0-dev.116/phet/equality-explorer_en_phet.html

**Comment by amanda-phet** [comment]
Some of David's examples can be achieved in the Variables screen of EqEx and don't need two variables. I think we need to consider the value of having two variables and what that gets us. 

From my perspective, I see this is a more formal version of what students can do with the objects, so the learning goals aren't much different. 

For example, you could set x and y to specific values, and come up with multiple equality statements and save them in the snapshots. This is the definition of a system of equations.

**Comment by pixelzoom** [comment]
Raising priority of this issue to "top".   I need to know immediately if there are any changes/requirements that will impact Equality Explorer.

**Comment by pixelzoom** [comment]
5/24/18 design meeting:

This sim will be named "Equality Explorer: Two Variables".  
Move this to new repo equality-explore-two-variables.

**Comment by pixelzoom** [comment]
Migration to equality-explorer-two-variables is done.   If there are any additional issues or requests, please create issues in that repository.

Closing.
